### ISSUE TITLE
App Crashes when shutting down current notebook

### ISSUE THREAD

**Issue by Arjitc12** [rationalmatter/Juno-Issue-Tracker#10]
The app will crash if you shut down the current running notebook instead of coming back to folders.

**Comment by navoshta** [comment]
Thanks for reporting, @Arjitc12 — I couldn't reproduce this yet, are there any particular steps to get it to crash? Does it happen with a particular notebook, or maybe after importing a specific module?

Also, do you shut it down by selecting "Close and Halt" in the notebook menu, or via "Shutdown" in the Kernel menu?

**Comment by navoshta** [comment]
I've implemented better crash reporting and additional logging in Juno 1.0.2, so should be able to address this in subsequent releases.

**Comment by navoshta** [comment]
This should now be fixed in latest beta (Juno 1.0.3).
