### ISSUE TITLE
Notebook is pushed out of memory after less than a minute of switching to another app

### ISSUE THREAD

**Issue by m-yaghini** [rationalmatter/Juno-Issue-Tracker#100]
**Describe the bug**
When connecting to a custom server using SSH and port forwarding, after opening the notebook and working on it, if you leave the app for a short while (even less than a minute), the notebook (and sometimes the server) can be pushed out of memory and you need to login again and navigate to the notebook again. 

**To Reproduce**
1. Go to Jupyter Server, and add a remote SSH server with port forwarding.
2. Tap on the server, enter login information (e.g. password).
3. Open a notebook, wait for the kernel to be loaded.
4. Navigate to a seprate app for more than a minute.
5. Come back to Juno 

**Expected behavior**
Juno should be kept in the background and the state should be maintained for a much longer period. One should be able to switch to different apps and come back to the pervious state of the notebook with no referesh.

**Screenshots**
If applicable, add screenshots or a screen recording to help explain your problem.

**Environment (please complete the following information):**
 - iPad Pro 12.9 1st Gen
 - iOS version: 13.1.2
 - App version 1.4.1 (3964)

**Comment by navoshta** [comment]
@m-yaghini, unfortunately, this is how iOS treats apps in background; they can remain in background only for so long before they get suspended by the operating system. Suspension also applies to app's networking resources: when the app is suspended, iOS closes all networking connections and claims back networking resources (including ports which Juno Connect uses for tunneling). 

Juno Connect will try to connect to the last server when it's back in foreground, and in most cases you won't need to log in again into your Jupyter server.

**Comment by ccruizm** [comment]
Good day, 

I am having the same issue. Even with just changing the app for 3 or 4 seconds, when I go back to Juno, the connection to the notebook is lost. Hope this can be solved somehow.

**Comment by mulra02** [comment]
Isn’t there any way to implement a better state recovery system. I don’t mind the app reconnecting to server, but the app also erases all the output (not variables but the plots etc).

**Comment by navoshta** [comment]
@mulra02 Sounds like in your case the problem is that notebook is not saved before the client disconnects; Juno Connect should respect the autosave setting on the server, and also save notebook whenever app enters background. So no notebook output should be lost, even if the app disconnects in the background — I'll look into what could cause it to not get saved.

**Comment by m-yaghini** [comment]
@navoshta Thank you for the reply. But with all due respect, I beg to differ. 

I am now using one of many SSH port forwarding apps on iOS to forward my remote server to a local port. I do not need to keep the said app open for the port forwarding to work, and I can carry on with Safari which now supports full desktop-class browsing on iPadOS 13. 

So I do think there is a way to keep the remote session alive in memory. I'm not an iOS developer, but I believe background updates have been a thing since iOS 7 at least.

**Comment by navoshta** [comment]
@m-yaghini Which app is it? If it indeed manages to keep SSH tunnel in background, you could try using _that_ for tunnelling, and then configure a direct server connection in Juno Connect, pointing to `localhost` as server address. 

Let me know if that works — as far as I'm aware, these rules apply to all 3rd party apps, and they will drop the connection once OS suspends it. If some app manages to stay alive, I'll be happy to take a close look and see if I can implement similar behaviour in Juno Connect.

**Comment by mulra02** [comment]
I think @m-yaghini is referring to Blink Shell. It can stay alive in the background by enabling geo-tracking. It kills some battery but manages to keep the app alive.

**Comment by ccruizm** [comment]
The same happens now with Teminus. It is able to keep alive in the background a terminal session connected to an HPC and doesn’t kill it. It would be nice if you can have a look at it and implement that feature into Juno :)

**Comment by navoshta** [comment]
@mulra02, @ccruizm My understanding was that this geo-location workaround no longer works in iOS 13 — but perhaps I'm wrong! Let me see if this could be done in Juno Connect, too. 🙂

**Comment by davidcorbin** [comment]
I know the app Textastic has SSH sessions that last relatively long compared to Juno. Might be worth checking out.

**Comment by navoshta** [comment]
@m-yaghini @mulra02 @ccruizm Yep, looks like I was wrong, and location tracking workaround does still work for keeping background networking connections active, even on iOS 13 — thanks for bringing this to my attention! This will likely be added in the next minor Juno Connect update (1.5.0).

**Comment by ccruizm** [comment]
Thanks for letting us know and digging into it @navoshta !

**Comment by m-yaghini** [comment]
Fantastic. Thanks @navoshta and others.

**Comment by navoshta** [comment]
@m-yaghini @mulra02 @ccruizm Juno Connect 1.5 is now in beta with an option to use location in background for better SSH tunnel persistene — if anyone wants to help test it, please send the e-mail address you use with your Apple ID to beta@juno.sh!

**Comment by caryfitz** [comment]
This also happens with the native Juno app.

Many other apps on IOS maintain their state between invocations.

THis bug renders Juno nearly unusable for me.  If I want to collect any data, do any analysis with my browser, *anything*, I have a mini-task in front of me to re-establish my context.  Using multiple application while developing software is a basic use case.

**Comment by navoshta** [comment]
@caryfitz I'd usually suggest opening a separate issue for Juno — however, it's not necessary here as this behaviour has already been reported in #48, #79 and #83. 

The good news is that Juno 1.2 will remain in background for a bit longer, and even when restarted will attempt to restore its context, just like what you are describing. I can add you to TestFlight when Juno 1.2 is in beta so that you can help us test it! We're currently working on finishing #25 and would like to get it done first, so will start beta-testing when SciPy is in relatively stable state.

**Comment by caryfitz** [comment]
Yes, please add me to the beta. 

Cary.

**Comment by navoshta** [comment]
The background location workaround is now available in Juno Connect 1.5 (live on App Store). It is an opt-in feature, and is not enabled by default. 

Please, mind that Juno Connect will try to automatically re-connect to last server the next time it's launched. If it happens to be an SSH server and location access is enabled, you may find Juno Connect a bit too persistent. However, Juno Connect will not automatically reconnect to servers which you explicitly disconnect before sending the app to background — so if you don't want a connection kept alive and auto-restored, simply disconnect your server as soon as you finish working with it.
