### ISSUE TITLE
Add tensorflow

### ISSUE THREAD

**Issue by stephan-jacobs** [rationalmatter/Juno-Issue-Tracker#104]
Tensorflow is pretty crucial to the stuff I work on. I can see that it would be difficult to get it working on iOS but if it’s possible to get any part of tensorflow working at all it would be an absolute game changer. Love your work!

**Comment by navoshta** [comment]
Duplicates #39 — please, upvote/comment on the original issue @stephan-jacobs. Either way, TensorFlow is certainly on the list. 🙂
