### ISSUE TITLE
Authentication fails with ECDSA ssh key

### ISSUE THREAD

**Issue by undefdev** [rationalmatter/Juno-Issue-Tracker#106]
As the title says, I wasn’t able to connect to my server after adding an ECDSA private key, I get the error message “authentication failed’. It works with RSA though.
 - Device: iPad Pro 11

**Comment by navoshta** [comment]
@undefdev I'm afraid Juno Connect currently only supports DSA and RSA keys, but I certainly would like to add support for ECDSA/Ed25519 keys eventually. Don't have any ETA right now though, sorry.

**Comment by algal** [comment]
I would suggest it might help if this were better documented. I have been scratching my head wondering about passphrase failures with my Ed25519 keys for quite a while.

**Comment by undefdev** [comment]
That‘s why I reported it, it shouldn’t even accept a key it can’t use and let the user know they’re not supported.

**Comment by navoshta** [comment]
@algal @undefdev Yes, good point — I'll make sure the private key screen explicitly states which keys (and key formats) are supported, currently it's DSA and RSA as Putty/OpenSSH keys.

**Comment by navoshta** [comment]
Juno Connect should support ECDSA keys for SSH connections now.
