### ISSUE TITLE
view csv files

### ISSUE THREAD

**Issue by barelyherenorthere** [rationalmatter/Juno-Issue-Tracker#107]
**Describe the bug**
I am using Juno Connect via local ssh into my Macbook. My script produces a csv file which is stored in the same folder. I tried to view the csv file by checking the box and clicking view.

However, nothing happens. Is this feature working?

 - Device: [iPad Pro 12.9"]
 - iOS version: [iPadOS 13.3]
 - App version [1.4.1]

**Comment by navoshta** [comment]
@barelyherenorthere, viewing/editing of text-based files is switched off for now, but this is something I want to look into sooner rather than later. I'll close this issue as a duplicate, as this has already been reported in #46.
