### ISSUE TITLE
import matplotlib.animation failed

### ISSUE THREAD

**Issue by CZspf** [rationalmatter/Juno-Issue-Tracker#110]
**Describe the bug**
import matplotlib.animation got traceback,
returning message “ cannot use a string pattern on a bytes-like object”

**To Reproduce**
I run juno jupyter on iPad Pro with ipados13, or iphone with ios13, simply import the module caused traceback

**Screenshots**
If applicable, add screenshots or a screen recording to help explain your problem.
![43217F4D-E5DE-47D6-85DC-7A7B96E67521](https://user-images.githubusercontent.com/59115006/71307871-86b08680-242f-11ea-827d-1c091cd20e26.png)

**Environment (please complete the following information):**
 - Device: [iPad Pro 11"]
 - iOS version: [ipadOS 13.2.3]
 - App version [1.1.1]

**Comment by navoshta** [comment]
Thanks for reporting @CZspf — I'm assuming this is related to Juno, not Juno Connect, I will look into this.

**Comment by navoshta** [comment]
@CZspf Juno 1.2 is now waiting for TestFlight review, and should be available in the next few days — please send an e-mail to beta@juno.sh if you would like to help test it! It should fix several issues around matplotlib animation module, among other things.

**Comment by navoshta** [comment]
This should be fixed in Juno 1.2 (now live on App Store)
