### ISSUE TITLE
Add cryptography

### ISSUE THREAD

**Issue by Povezi** [rationalmatter/Juno-Issue-Tracker#111]
Any idea how go make connection to mysql via ssh tunnel? I cannot install dependancy “cryptography”

**Comment by navoshta** [comment]
Hi @Povezi, which app are you trying to connect from, Juno or Juno Connect? If it's Juno, then cryptography being not a pure Python package will need to be ported and included in the bundle first (please, submit a package request issue for this).

**Comment by Povezi** [comment]
> Hi @Povezi, which app are you trying to connect from, Juno or Juno Connect? If it's Juno, then cryptography being not a pure Python package will need to be ported and included in the bundle first (please, submit a package request issue for this).

I am using Juno. I understand that it does not support non-Python libraries, but it would be really useful to have possibility to connect to remote mysql databases?

Thank you

**Comment by navoshta** [comment]
Ah OK @Povezi I think I see what you mean. Is it only cryptography module that's missing, or is there anything else that is required for mysql connection? Please, add separate package requests for individual packages with native extensions.

**Comment by Povezi** [comment]
> Ah OK @Povezi I think I see what you mean. Is it only cryptography module that's missing, or is there anything else that is required for mysql connection? Please, add separate package requests for individual packages with native extensions.

Not sure until we resolve cryptography.

I really think that mysql tunnel is essential for panadas on Juno.

Here is link to python mysql tunnel code that I want to try:

https://stackoverflow.com/questions/21903411/enable-python-to-connect-to-mysql-via-ssh-tunnelling

import pymysql
import paramiko
import pandas as pd
from paramiko import SSHClient
from sshtunnel import SSHTunnelForwarder
from os.path import expanduser

**Comment by navoshta** [comment]
Ah OK @Povezi, it does seem like this will require more packages. I suggest that we revisit when `cryptography` is added — other packages will need separate tickets anyway.

**Comment by navoshta** [comment]
Juno 1.3 with Cryptography is now live on App Store 🚀
