### ISSUE TITLE
Floating menu makes impossible to use the app

### ISSUE THREAD

**Issue by undiabler** [rationalmatter/Juno-Issue-Tracker#113]
**Describe the bug**
Floating menu disappears and makes running cells completely impossible.

**To Reproduce**
1. Go to python notebook
2. Tap on edit cell (source code)
3. Tap back to hide keyboard
4. Floating menu disappears. Now you can do nothing with notebook.

**Expected behavior**
Floating menu should be fixed, or moved somewhere (header is ok).

**Screenshots**
![dissapeared-menu](https://user-images.githubusercontent.com/4733217/71481312-a5cb6180-27fd-11ea-8976-c8d988dfeedd.jpg)
![jumping-menu](https://user-images.githubusercontent.com/4733217/71481314-a8c65200-27fd-11ea-8763-a1ec8afbc58a.jpg)

**Environment:**
 - Device: iPad Pro 11"
 - iOS version: iOS 13.3
 - App version 1.4.1 (3964)

**Comment by navoshta** [comment]
Thanks for reporting @undiabler — I couldn't reproduce this unfortunately, so I may need some additional info from you. Juno's notebook editor should respect all software keyboard transitions, so I'm not sure off the top of my head what could go wrong. Any further details on the following will help:

1. When you say "tap back", do you mean the "Hide Keyboard" button on the on-screen keyboard?
2. Do you experience this with every notebook, every time? Is it the same for code/markdown cells?
3. Do you have any hardware keyboard connected, or are you only using the on-screen keyboard?
4. Which international keyboards to you have installed? Do you have any 3rd party software keyboards enabled by any chance?

If you could provide a screen recording illustrating the issue, that would help immensely — but worry not, I will look into this either way.

**Comment by undiabler** [comment]
1. I mean just tap on any space except code cell.
2. On any cells with editable content. Every time.
3. No, i'm using only on-screen keyboard.
4. I have installed google gboard, but there is the same problem with naitive keyboard too, attached video with illustration with native apple keyboard.

https://youtu.be/abrManih_wU

P/s Maybe it is somehow connected with new floating mode for keyboards in ios 12+
If you turn you keyboard into floating mode on ipad you can see jumping menu all over the screen.

**Comment by navoshta** [comment]
Thanks @undiabler! I don't think it's related to floating mode: Juno should handle this gracefully and simply stick the buttons to the bottom. 

I couldn't reproduce anything close to this on the same device running same iOS version, so I have a strong feeling this is related to google gboard being registered in the system, and therefore OS incorrectly reporting keyboard position and layout (even for system keyboards). There are several odd things in your screen recording, which make me think it's a system-level issue: the keyboard extension is not displayed (unless you switched it off in Juno Connect settings?), keyboard extension actions are not displayed either (they should appear in the clipboard actions area), and also those overlay buttons shouldn't jump all over the screen while keyboard is in floating mode. It seems to indicate that the system is failing to reliably report current keyboard state and transitions.

I'll tinker with some 3rd party keyboards on my test device and see how Juno's editor responds to them — hopefully I'll be able to retrieve something consistent to work around these issues. Once again, thanks for reporting!

**Comment by undiabler** [comment]
I've deleted all custom keyboards - same problem.
Here is the example how "buttons are sticked to the bottom" in floating mode.
![photo5201847734041161988](https://user-images.githubusercontent.com/4733217/71528923-8fe39c80-28e2-11ea-8593-5eaa1698c444.jpg)

Do you have any other languages installed in your system?

**Comment by undiabler** [comment]
> the keyboard extension is not displayed (unless you switched it off in Juno Connect settings?), keyboard extension actions are not displayed either (they should appear in the clipboard actions area)

This option was switched on.
After disabling Keyboard Extension everything looks working even with custom keyboards.

So for me the issue now looks like:
- Juno Keyboard Extension is doing something wrong with my keyboards (maybe because of two languages)
- System is failing to reliably report current keyboard state
- Floating menu dissapears

**Comment by navoshta** [comment]
> Do you have any other languages installed in your system?

Yep I have a number of international keyboards enabled (that's why I thought it's the 3rd party one).

> After disabling Keyboard Extension everything looks working even with custom keyboards.

Ah OK — thanks, I'll keep an eye on that, too. Sounds like it's some sort of a workaround for now at least!

**Comment by navoshta** [comment]
Hi @undiabler — could you please check if this is now working in Juno Connect 1.5? A few things around how keyboard is handled have been updated and fixed, so I'm hoping it improved or fixed your issue, too. 🤞

**Comment by undiabler** [comment]
Confirmed, on 1.5.5 (5304) everything works fine.
There is no smooth iOS animation for the floating buttons when keyboard appears (with keyboard extension on), but main problem was solved, buttons don't disappear. Thanks!
