### ISSUE TITLE
Exporting Jupyter Notebooks

### ISSUE THREAD

**Issue by aarondcopeland** [rationalmatter/Juno-Issue-Tracker#117]
Would be nice to be able to export Jupyter Notebooks to different formats from the Juno app.

**Comment by navoshta** [comment]
Yep it's in development already, should be released with the next minor update of both Juno and Juno Connect.

**Comment by aarondcopeland** [comment]
Hell yeah, keep up the good work man.

**Comment by haselnut** [comment]
nbconvert 5.4.1 is already pre-installed in Juno. Can it, in some way, be used to export  a notebook as  a pdf for example?

**Comment by navoshta** [comment]
@haselnut My guess is not yet, as even if a file gets exported somehow, Juno wouldn't know to display a sharing sheet, etc. It will be added in the next release though.

**Comment by haselnut** [comment]
OK, Thanks a lot. Congratulations though for the great job! Juno is really fantastic!!

**Comment by navoshta** [comment]
Export menu is now available in Juno 1.2 and Juno Connect 1.5 (both live on App Store). Mind that for Juno Connect it will use the available exporters on your Jupyter server, i.e. you will be able to use the same export options that normally work when you connect to your server elsewhere.
