### ISSUE TITLE
Add psutil

### ISSUE THREAD

**Issue by goodbull** [rationalmatter/Juno-Issue-Tracker#121]
Is psutil available? It offers the option to download, but says “installation from source failed” after it downloads.

**Comment by navoshta** [comment]
@goodbull Unfortunately it has native extensions, so needs to be ported and embedded in the app, similar to NumPy, Matplotlib and Pandas. What happens is Juno finds a distribution that could _potentially_ work (source), tries installing from it, but then realises that installation actually involves compiling native extensions, which is not possible on iOS — so aborts and reports failure. 

I'll mark this issue as a package request.

**Comment by goodbull** [comment]
Got it, thanks! This is the only thing keeping me from exporting plot.ly graphs as images to a directory.

**Comment by alexstaravoitau** [comment]
Psutil is now available in Juno 3.2 as a pinned package—although reporting is limited to public APIs (which in case of iOS means reporting is *very* limited).
