### ISSUE TITLE
Loading local .csv using pandas shows git-lfs type of data, not actual contents

### ISSUE THREAD

**Issue by cheval1201** [rationalmatter/Juno-Issue-Tracker#123]
**Describe the bug**
I'm using Microsoft Azure notebook on Juno Connect. When I try to load a local (uploaded on Azure Notebook server) csv file using pandas.read_csv() function, the result table includes a git-lfs type of content instead of data.

**To Reproduce**
1. upload a csv file on Microsoft Azure Notebook server
2. load the csv file using pandas 
    e.g.) data = pandas.read_csv('test.csv')

**Expected behavior**
I expect to see the actual contents of the csv file as a table.

**Screenshots**
If applicable, add screenshots or a screen recording to help explain your problem.
![image](https://user-images.githubusercontent.com/6489017/72576969-7eefdf00-3914-11ea-8e7f-2ee3597990ce.png)

**Environment (please complete the following information):**
 - Device: [e.g. iPad Pro 3 12.9"]
 - iOS version: [e.g. iOS 12.4.1]
 - App version [e.g. 1.4.1]

**Comment by navoshta** [comment]
@cheval1201 How does this work on desktop, i.e. when you access Azure Notebooks from your desktop browser?

**Comment by cheval1201** [comment]
@navoshta It shows the same results when I run it on desktop. It seems the csv file I downloaded contains a git-lfs link in the first place. This issue doesn't have to do with Juno Connect, so I'll close it. Thank you.
