### ISSUE TITLE
Widgets - Buttons not displayed

### ISSUE THREAD

**Issue by nmall2020** [rationalmatter/Juno-Issue-Tracker#126]
**Describe the bug**
installed package ipywidgets and defined several  buttons with methods ‘display’ and ‘on-click’.  However buttons are not displaying.

**To Reproduce**
1. Call method display for a defined button widget.

**Expected behavior**
To see the buttons displayed after code compilation 

**Screenshots**

**Environment (please complete the following information):**
 - Device: iPhone 7
 - iOS version: iOS 13.3
 - App version  1.1.1

**Comment by navoshta** [comment]
Thanks for reporting @nmall2020 — I'll close this as #92 duplicate. Both Juno and Juno Connect need improvements in how they support ipywidgets, and I'm planning to include ipywidgets by default with Juno when this support is added.
