### ISSUE TITLE
SSL error

### ISSUE THREAD

**Issue by njagh** [rationalmatter/Juno-Issue-Tracker#129]
I am trying to connect to an AWS DLAMI (Ubuntu 16.04) Version 26.0 but the connection isn’t working

The Jupyter notebook server says “SSL error on XX (‘127.0.0.1’, XXXXX): [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:841) when I try to connect from the app

**Comment by navoshta** [comment]
Hi @njnnja, are you connecting using direct connection or port forwarding?

Looks like you are connecting to your Jupyter server over HTTPS, so I'm going to assume you connect directly. If that's the case, you likely have the SSL certificate misconfigured — please, follow [this guide](https://juno.sh/ssl-self-signed-cert/) on how you can create a self-signed certificate that will work with iOS. However, I highly suggest connecting via port forwarding instead, where you can use plain HTTP.

**Comment by navoshta** [comment]
@njagh Closing this for now — feel free to reopen if you need any further assistance (or send an e-mail to help@juno.sh and I'll be happy to help).
