### ISSUE TITLE
Open external Python Packages in place

### ISSUE THREAD

**Issue by BrianChevalier** [rationalmatter/Juno-Issue-Tracker#13]
When developing Python packages I like using Jupyter to test new functions/classes and automatically reload packages (using the autoreload extension). Working Copy is used to version control my packages, and it can automatically sync files to external folders (including the Juno site-packages directory). However, this requires having Working Copy in the foreground to keep files in sync and I would rather use Pythonista (to use advanced IDE features) and Juno in a split.

It would be nice to have Juno directly look at the external folder in Working Copy to read changes as they are being made. It would also be nice to open external .ipynb files in place since I have example notebooks I want to work on directly.

**Comment by navoshta** [comment]
Should be available in Juno 1.0.2
