### ISSUE TITLE
Dark Mode - Jupyter Commands unreadable in Dark Mode

### ISSUE THREAD

**Issue by nothingto** [rationalmatter/Juno-Issue-Tracker#130]
**Describe the bug**
The menu is completely bright even in the dark theme

**To Reproduce**
Toggle Dark Mode
Go to notebook
Click the “Jupyter Commands” button

**Expected behavior**
Supposed to show a readable list of items

**Screenshots**
If applicable, add screenshots or a screen recording to help explain your problem.

**Environment (please complete the following information):**
 - Device: [e.g. iPad Pro 12.9"]
 - iOS version: [e.g. iPadOS 13]

**Comment by navoshta** [comment]
@nothingto Thanks for reporting — there seems to be an issue with the latest Jupyter Notebook releases. This will be fixed in the next minor Juno Connect update.

**Comment by navoshta** [comment]
This should be fixed in Juno Connect 1.5 (now live on App Store)
