### ISSUE TITLE
Pandas does not properly display data frames with complex numbers

### ISSUE THREAD

**Issue by John-Rule-Bose** [rationalmatter/Juno-Issue-Tracker#132]
**Describe the bug**
Pandas supports complex numbers, and Juno [correctly] allows for the creation of data frames containing complex numbers.  However, display functions other than for a single cell do not work.

**To Reproduce**
1. Create a complex numpy array and turn it into a pandas dataframe:

import numpy as np
import pandas as pd
tmpRe = np.random.normal(size=(5,5)); #tmpRe
tmpIm = np.random.normal(size=(5,5));
tmpCplx = tmpRe+1j*tmpIm; # tmpCplx
df = pd.DataFrame(data=tmpCplx)

2. Look at a single cell to show that construction worked:

df.iloc[0,0]     # Should succeed

3. Try to display the whole dataframe:

df     # Should fail!

4) Tail of the error:

/var/mobile/Containers/Data/Application/3BC357C4-4ED2-4D1B-B75E-B2D76EE36EBB/Library/Application Support/com.rationalmatter.junoapp/python-home/lib/python3.6/site-packages/pandas/io/formats/format.py in separate_and_trim(str_complex, na_rep)
   1592             + ["+"]
   1593             + _trim_zeros_float([num_arr[1][:-1]], na_rep)
-> 1594             + ["j"]
   1595         )
   1596 

IndexError: list index out of range

5) Note that other array operations on the dataframe succeed:

20*np.log10(abs(df))     # Succeeds, with array of magnitudes

**Expected behavior**
Should be able to display a complex array.

**Screenshots**

**Environment (please complete the following information):**
 - Device: [e.g. iPad Pro 12"]
 - iOS version: [e.g. iOS 13.3.1]
 - App version [e.g. 1.1.1]

**Comment by navoshta** [comment]
Thanks for reporting @John-Rule-Bose, I will look into this.

**Comment by John-Rule-Bose** [comment]
Can confirm that this is fixed on latest beta, 1.2.5.  Thanks!

**Comment by navoshta** [comment]
The fix has also been released to App Store in a recent update.
