### ISSUE TITLE
Local port forwarding through a jump server

### ISSUE THREAD

**Issue by ho-oto** [rationalmatter/Juno-Issue-Tracker#134]
I desire to connect with my jupyter server through a jump server.

Now, I make SSH tunnel by using [Blink Shell](https://apps.apple.com/jp/app/blink-shell-mosh-ssh-client/id1156707581) (in which I can configure proxy command like `ssh -CW %h:%p foo`) and use Juno with Direct connection mode. But, it is troublesome...

**Comment by navoshta** [comment]
Hi @ho-oto — thanks for reporting, I'll see what we can do here. I suppose meanwhile you could try doing this by somehow establishing a tunnel from the jump server to final destination _first_, and then connecting via tunnel to that jump server? I'm not 100% sure this will work though, just something off the top of my head.

Either way, I will see if this is something we could add in Juno Connect.

**Comment by navoshta** [comment]
Instruction added to Juno Connect FAQ: https://juno.sh/troubleshooting-juno-connect#can-i-connect-to-a-jupyter-server-sitting-behind-another-gatewayproxy-machine
