### ISSUE TITLE
Connection failure in iPadOS 13.4 using self signed SSL cert

### ISSUE THREAD

**Issue by hingsar** [rationalmatter/Juno-Issue-Tracker#137]
**Describe the bug**
Connection failure in iPadOS 13.4 using self signed SSL cert.
I followed your doc to setup cert. It worked well in iPadOS 13 to 13.3, but failed in 13.4. I tried re-installed my cert which didn’t work either.

I suspect Apple changed their security policy again just like iPadOS 13, but didn’t find any doc in apple’s website.

**Environment (please complete the following information):**
 - Device: [e.g. iPad Pro 12.9"]
 - iOS version: [e.g. iOS 13.4]
 - App version [e.g. 1.4.1]

**Comment by navoshta** [comment]
@hingsar I've tried re-creating a certificate and it seems to still work on iPadOS 13.4. Apple did change a few things in iOS 13, but this has been taken care of in the instructions. Could you please try following again — also please make sure to enable full trust to installed certificates after installing them (that's an extra step after the usual iOS confirmation dialogues to install it first).

**Comment by navoshta** [comment]
@hingsar Closing this for now — feel free to reopen if you need any further assistance (or send an e-mail to help@juno.sh and I'll be happy to help).
