### ISSUE TITLE
Please add yfinance

### ISSUE THREAD

**Issue by webcontrols** [rationalmatter/Juno-Issue-Tracker#138]
**What is the name of the package?**
Yfinance for stock market data from yahoo

**Comment by navoshta** [comment]
@webcontrols Yfinance seems to be a pure Python package, so you should be able to install using Juno's package installer. Please, mind that it won't install dependencies automatically.

Closing this issue for now — if you identify a dependent package with native extensions that need to be ported, please, open a new issue for it.
