### ISSUE TITLE
Restart and Run All Cells not work

### ISSUE THREAD

**Issue by mieqq** [rationalmatter/Juno-Issue-Tracker#14]
Restart and Run All Cells not work along with Restart and Clear Output.

Environment (please complete the following information):

Device: iPhone Xr
iOS version: iOS 12.3
App version: 1.0.0

**Comment by navoshta** [comment]
This will be _a bit_ tricky with Juno's kernel management, but still doable. I have disabled the "Restart and Run All Cells" action for now, and will re-enable when the underlying issue is fixed.
