### ISSUE TITLE
Add urllib

### ISSUE THREAD

**Issue by webcontrols** [rationalmatter/Juno-Issue-Tracker#140]
URL parsing dependent on requests package

**Comment by navoshta** [comment]
@webcontrols I managed to successfully install `urllib` with Juno's package installer — perhaps some dependencies with native extensions are missing? If so, please open a separate issue for whichever package can't be installed.

**Comment by webcontrols** [comment]
The app couldn’t find URLLIB it finds URL but fails to install.Please see attached

**Comment by navoshta** [comment]
@webcontrols Actually, urllib is a part of standard library now, so should be available without installation. Which error exactly are you getting?
