### ISSUE TITLE
Juno Connect keeps getting killed in background when switching to another app for more than a few seconds

### ISSUE THREAD

**Issue by rohitsrao** [rationalmatter/Juno-Issue-Tracker#142]
**Describe the bug**
I am connecting to a remote jupyter server on my laptop via local port forwarding. If I open another app and come back to Juno Connect, the app has disconnected from the server and needs to reconnect and I need to load the notebook again. Unsaved progress is lost. 

**To Reproduce**
Just switch to another app for more than a few seconds. 

**Expected behavior**
Expected program to keep running in the background and I come back to the updated state when I switch back to the app.

**Environment (please complete the following information):**
 - Device: iPad Pro 2018 - 12.9”
 - iOS version: iPad OS 13.4
 - App version: Juno Connect 1.4.1 (3964)

**Comment by navoshta** [comment]
Thanks for reporting @rohitsrao, the SSH tunnel disconnecting has been discussed here: #100, it will be addressed in Juno Connect 1.5 via location tracking. Let me know if you would like to try Juno Connect 1.5 beta and see if it improves things for you.

That said, it's odd that your unsaved changes are lost, as Juno Connect should save changes automatically when entering background — I'll look into that.

**Comment by rohitsrao** [comment]
Oops. My bad. Didn’t search thoroughly. Have just signed up for beta. Will report back.

**Comment by rohitsrao** [comment]
Problem still persists. I fired up Juno connect and switched to YouTube for a few seconds. When I came back to Juno Connect the app had to reconnect to my jupyter server again.

**Comment by navoshta** [comment]
@rohitsrao Does the location workaround help at all? You can enable it in app settings.

**Comment by rohitsrao** [comment]
Yes it does. I put the app in background for 5 and 12minutes and it was still active in the background. Thanks!

Would have been nice to have a small welcome screen showing what is new in the app as I had no idea something had changed in the settings app. 

Also how much of a battery drain is this going to cause and is there no better workaround than having to keep using location services ?!

**Comment by navoshta** [comment]
@rohitsrao Great, glad it works! Yep a "What's New" screen makes sense, I was planning to add something like this eventually. As per battery drain — I'd say yes, it will likely consume battery a bit more agressively, so make sure to disconnect port forwarding connections when you don't need them anymore. 

I don't think there's a better workaround for now unfortunately, as iOS is pretty strict with reclaiming OS resources from 3rd party apps in background, including networking resources like ports, etc. I'll close this issue for now, as this duplicates what's discussed in #100 — but please feel free to reopen or open a new one if I've missed anything.
