### ISSUE TITLE
Local Port Forwarding Authentication Failure

### ISSUE THREAD

**Issue by CLFV** [rationalmatter/Juno-Issue-Tracker#145]
I've been successfully using Juno Connect and local port forwarding to connect to a Jupyter server I have running on an Ubuntu 18.04 LTS machine and I recently installed a similar setup on a Raspberry Pi 4 (running Raspbian Buster).

I'm able to connect to the Jupyter server on the pi locally from the pi itself and I'm also able to connect to it from a Mac on the local network after forwarding port 7777 (where the server is running) from the pi to the Mac's local port 8888 using:

`ssh -L 8888:localhost:7777 pi@raspberrypi.local`

However, when I try to connect to it using local port forwarding from Juno Connect on my iPad Pro 11" (2018 model, running iOS 13.4), I get the error: "Authentication Failed":

![IMG_9150](https://user-images.githubusercontent.com/63271671/78622063-04f73400-7839-11ea-8d4c-8b5e67bc1ae1.jpeg)

My configuration is in the attached screenshots. Although the password field is cropped out of the screenshots, I should just note that I don't seem to have the issue described in https://github.com/rationalmatter/Juno-Issue-Tracker/issues/60 since I see the bullet points in the password field after saving my password.

I've checked the /var/log/auth.log on my pi and confirmed that when I get the "Authentication Failed" message on my iPad, the Pi does register a failed connection attempt that it reports as due to an incorrect password, even though I've verified that I used the right password:

![IMG_9155](https://user-images.githubusercontent.com/63271671/78622629-78e60c00-783a-11ea-8cde-3a8d593c8b04.jpeg)

Also, I'm able to log into the pi from my iPad using ssh in the blink terminal and the same user and password that I'm attempting to use for the port forwarding.

Thanks in advance for your help.

Configuration:

![IMG_9151](https://user-images.githubusercontent.com/63271671/78622148-3a038680-7839-11ea-9041-2498bde84c5b.jpeg)

![IMG_9152](https://user-images.githubusercontent.com/63271671/78622157-4091fe00-7839-11ea-8763-db690808c758.jpeg)

**Comment by navoshta** [comment]
@CLFV There is an issue in Juno Connect that could result in similar symptoms — could you please send your email to beta@juno.sh? I'll add you to Testflight so that you can give Juno Connect 1.5 a go, it's currently in beta and it should have this issue resolved.

**Comment by CLFV** [comment]
Thanks - the Juno Connect 1.5 beta has fixed the bug.
