### ISSUE TITLE
Cannot connect to Jupyter Server over VPN

### ISSUE THREAD

**Issue by austingreisman** [rationalmatter/Juno-Issue-Tracker#146]
**Describe the bug**
I have a remote Jupyter Server which I am connecting to using a VPN. Using Termius, I can manually port forward and SSH into my remote machine (while my VPN is connected). However, using your app, I get a “Authentication Failed” using the same credentials and ports.

**To Reproduce**
I cannot give the server for security reasons but I’ll generalize
1. Set type to local port forwarding
2. Enter Host URL name (of the machine which works in Termius)
3. Port for host is set to 22
4. Authentication settings are set to my username and password for that machine.

**Expected behavior**
It to connect.

**Screenshots**
![09FB9278-EF31-4541-9C75-63EF0EB02DCF](https://user-images.githubusercontent.com/16636670/79022405-d1bfe800-7b4b-11ea-8cb1-77a230310bf5.jpeg)

**Environment (please complete the following information):**
 - Device: iPad Pro 12.9“ (2020)
 - iOS version: IOS: 13.4.1
 - App version: 1.4.1

**Comment by austingreisman** [comment]
I worked around the issue by using a private key instead of the password... Not sure if that means this should be closed.

**Comment by navoshta** [comment]
Hi @austingreisman, this looks similar to a Juno Connect bug that has been recently fixed in  beta  (see #145) — would you like to try Juno Connect 1.5 beta and see if it fixes your issue? If that's OK please send an email to beta@juno.sh.

**Comment by austingreisman** [comment]
Sure! Email sent.

**Comment by navoshta** [comment]
Hopefully this has been fixed in a recent release — please feel free to reopen if the issue still persists.
