### ISSUE TITLE
Dark mode contrast issues with command palette

### ISSUE THREAD

**Issue by austingreisman** [rationalmatter/Juno-Issue-Tracker#147]
**Describe the bug**
The command palette options displayed are a light shade of grey. It’s very hard to see the options.

**To Reproduce**
1. Start Dark mode
2. Open Notebook
3. Press “p”

**Expected behavior**
Colours of text have high contrast. (Works fine in light mode)

**Screenshots**
Can’t seem to attach photos at the moment.

**Environment (please complete the following information):**
 - Device: iPad Pro 12.9" (2020)
 - iOS version: IOS 13.4.1
 - App version 1.4.1

**Comment by austingreisman** [comment]
![IMG_0009](https://user-images.githubusercontent.com/16636670/79034436-d1dbda00-7b83-11ea-8e33-1bbb1ef3cea3.png)

**Comment by navoshta** [comment]
Thanks for reporting @austingreisman — this should work fine on recent Jupyter Lab/Notebook releases, but not sure for older ones. Which version are you running?

**Comment by navoshta** [comment]
This should be fixed in Juno Connect 1.5 (now live on App Store)
