### ISSUE TITLE
Simpy fails while running import simpy 

### ISSUE THREAD

**Issue by mp2011** [rationalmatter/Juno-Issue-Tracker#149]
**Describe the bug**
Simpy package fails when running import simpy

**To Reproduce**
1. Download and install simpy 4.0.0
2. Open a Jupyter notebook session
3. Write import simpy
4. Execute Run Cell
5. A series of error is displayed 

**Expected behavior**
Cell should be executed without errors.
<img width="834" alt="Immagine PNG" src="https://user-images.githubusercontent.com/63677951/79276796-ecc28d00-7ea8-11ea-8f68-30496b5ea30a.png">

**Screenshots**
If applicable, add screenshots or a screen recording to help explain your problem.

**Environment (please complete the following information):**
 - Device: iPad Pro 11"
 - iOS version: iOS 13.3.1
 - App version 1.1

**Comment by mp2011** [comment]
Installing an older version 3.0.11 apparently solved the problem.

**Comment by navoshta** [comment]
@mp2011 Thanks for reporting, this is a bug in Juno. Looks like `pkg_resources` doesn't always find packages installed from wheel distributions — I'll take a look.

**Comment by navoshta** [comment]
@mp2011 This should now be fixed — Juno 1.2.2 is live on App Store
