### ISSUE TITLE
 Unexpected Behaviour in pynb

### ISSUE THREAD

**Issue by Arjitc12** [rationalmatter/Juno-Issue-Tracker#150]
**Describe the bug**
\b while being used in pynb shows behaviour of a backspace. 

```
print("HELLO\b\bD")
should produce output as HELDO
```
but rather it prints 

> HELD

 working similar to a backspace. 

![image](https://user-images.githubusercontent.com/28424828/79285937-ab4bd500-7edc-11ea-857c-18d3f5e08768.png)

**Environment :**
 - Device: [iPhone 7]
 - iOS version: [e.g. iOS 13.3.1]
 - App version [1.2.0(5156)]

**Comment by navoshta** [comment]
@Arjitc12 That's an interesting observation, I didn't notice this before — but it looks like Jupyter has the same behaviour on desktop (as well as Python interpreters in general). Could you please explain further why it should be `HELDO`?

**Comment by Arjitc12** [comment]
@navoshta 
\b works in a way to overlap characters
If it is 
`print(“HELLO\b\bD”)`
Then cursor would move two characters back ie it will reach HEL**L**O and then overwrite the characters after O which is in this case D.
Similarly, `print(“HELLO\b\b\bD)` would produce 
`HEDLO`

**Comment by navoshta** [comment]
Ah OK that makes sense @Arjitc12. 

I saw that you opened an issue with Jupyter (https://github.com/jupyter/notebook/issues/5381), which was a good call I think: Juno embeds standard Jupyter for the backend, so if/when this issue is fixed there, it will be picked up in Juno, too.
