### ISSUE TITLE
Documentation mistype : https://juno.sh/ssh-tunnel-to-jupyter-server/

### ISSUE THREAD

**Issue by 87bdharr** [rationalmatter/Juno-Issue-Tracker#151]
**Describe the bug**
I think there’s a typo in your guidance documentation for connecting to Juno via ssh: https://juno.sh/ssh-tunnel-to-jupyter-server/. 

“Now detach from this session by pressing Ctrl + D, and then pressing B“. I believe to detach a tmux session the command is Ctrl + B then D.

**Comment by navoshta** [comment]
Thanks @87bdharr, should be fixed now! 🤦‍♂️😁
