### ISSUE TITLE
Add **torch** and **torchvision**

### ISSUE THREAD

**Issue by PowderHan** [rationalmatter/Juno-Issue-Tracker#152]
Can you add torch and torchvision in Juno? As I know, more and more people use JupyterNotebook to learn Machine Learning, and PyTorch is really useful, I know many friends want to use Juno in iPad Pro to code, but it can’t use PyTorch, this is really regrettable. So can you make it pre-installed? Thank you very much.

**Comment by navoshta** [comment]
@PowderHan PyTorch has been requested here: https://github.com/rationalmatter/Juno-Issue-Tracker/issues/35 — I'll close this issue as a duplicate if you don't mind.

**Comment by plucaci** [comment]
5 years on, and it says "not compatible". What happened?
