### ISSUE TITLE
Access to folders is lost after killing the app

### ISSUE THREAD

**Issue by ancientbuho** [rationalmatter/Juno-Issue-Tracker#154]
**Describe the bug**
After granting access to a folder using the document picker, then killing Juno, access to the folder is lost. 

Access to the folder should be saved (via a [bookmark](https://developer.apple.com/documentation/uikit/view_controllers/providing_access_to_directories)) so that it can be restored when the app relaunches.

**To Reproduce**
1. Open a file outside of Juno’s folder (for instance, in Working Copy).
2. Grant access to the folder by tapping the lock button and selecting the folder.
3. Kill Juno and open the file again.

**Expected behavior**
There’s no lock icon and Juno has access to the folder

**Actual behavior**
The lock icon is visible again and you have to re-grant access.

**Environment**
 - iPad Pro 11
 - iPadOS 13.4.1
 - Juno 1.1.1  (4128)

**Comment by navoshta** [comment]
Thanks for reporting @ancientbuho! Yep you are right, it's been implemented a while back, but hasn't been released yet. It's coming in Juno 1.2, which will remember cwd and directory permissions for each notebook. It is currently in beta — please send an e-mail to beta@juno.sh if you would like to help test it, or simply would like to take an early look, and I'll you to our TestFlight. 😉

**Comment by ancientbuho** [comment]
@navoshta I emailed to get access to the beta builds via TestFlight. Thanks!

**Comment by ancientbuho** [comment]
@navoshta  This is working in 1.2.2 correctly, permissions get restored on re-launch. 👍🏻

**Comment by navoshta** [comment]
Closing the issue as Juno 1.2 is now live on App Store. 🚀
