### ISSUE TITLE
Completer suggestions not responding to touch

### ISSUE THREAD

**Issue by kerryeva** [rationalmatter/Juno-Issue-Tracker#156]
**Describe the bug**
Update to 1.5.4, ios 13, ipad mini5.
I can not choice the keyword-alternative by finger touching. But use pencil can did choice.

**Expected behavior**
Make a choice not just by pencil but also by finger touch.

**Environment (please complete the following information):**
 - Device: [iPad mini5] [iPad pro 12.9]
 - iOS version: [iOS 13.2][iOS 13.1.2]
 - App version [1.5.4]

**Comment by navoshta** [comment]
Thanks for reporting @kerryeva — I'm assuming this is related to completer suggestions?

**Comment by kerryeva** [comment]
> Thanks for reporting @kerryeva — I'm assuming this is related to completer suggestions?

yes, when I touch the suggestions list , Juno will shows select, select all, comment, etc. not input my choice.

**Comment by navoshta** [comment]
@kerryeva OK got it, this will be addressed in a follow-up release soon.

**Comment by navoshta** [comment]
This should now be fixed in both Juno and Juno Connect.
