### ISSUE TITLE
Add **scikit-learn**

### ISSUE THREAD

**Issue by Neny90** [rationalmatter/Juno-Issue-Tracker#159]
**What is the name of the package?**
A name or link to the Python package you think should be pre-installed in Juno. Mind that you can install pure Python packages from PyPI in Juno — those that can be successfully installed won't be embedded in the app.

**Comment by haselnut** [comment]
Thanks for you anwswer Neny90. I finally found the package manager under the options that
appear when one clicks on the notebook name. I looked at different places and did not find it the
first. 
I know that extra packages should be pure python.

**Comment by haselnut** [comment]
astropy would be nice to have!

**Comment by Neny90** [comment]
Yeah, I tried searching for scikit-learn but they are not supported even though it is a pure python package. I also tried to unlock whl package and page contents in Juno’s site-packages directory but got an error that scikit-learn was not built properly :(

**Comment by Neny90** [comment]
Clearer instructions for manually installing pure python packages would be nice

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by navoshta** [comment]
Hi @Neny90, scikit-learn does seem to have native extensions, so needs to be pre-compiled. There is already a ticket for it here: https://github.com/rationalmatter/Juno-Issue-Tracker/issues/3 (I'll close this one as duplicate). There are instructions on installing packages that are linked from the app's package installer (https://juno.sh/juno-pypi-package-installer/), although perhaps there's a better place in the app to link them, I'll try to think of something.

@haselnut There is also a request for astropy here: https://github.com/rationalmatter/Juno-Issue-Tracker/issues/144 — feel free to upvote/comment. 🙂
