### ISSUE TITLE
deleted file is crash

### ISSUE THREAD

**Issue by zachary-zhang** [rationalmatter/Juno-Issue-Tracker#16]
<sub>Sent from <a href="https://itunes.apple.com/cn/app/id1314212521">PPHub For GitHub</a></sub>

**Comment by navoshta** [comment]
Thanks for reporting @zachary-zhang, is it similar to #6 and #7 by any chance, or does the app actually crash?

**Comment by zachary-zhang** [comment]
The first installation of app appears .the app actually crash

**Comment by navoshta** [comment]
Should be fixed in Juno 1.0.2
