### ISSUE TITLE
Add Statsmodels

### ISSUE THREAD

**Issue by tolgadiz** [rationalmatter/Juno-Issue-Tracker#160]
I know this may be a niche request but I think adding Statsmodels module would be very helpful for those of us that work with statistical models. Since scipy has already been implemented, I imagine this module can be added without a lot of work.

PyPI link: [https://pypi.org/project/statsmodels/](https://pypi.org/project/statsmodels/)
Github link: [https://github.com/statsmodels/statsmodels](https://github.com/statsmodels/statsmodels)

**Comment by navoshta** [comment]
Yep, it's certainly on the list. 👍

**Comment by lmatute** [comment]
Would like to second the request ( Statsmodels)

**Comment by jmbenedetto** [comment]
+1

**Comment by navoshta** [comment]
Statsmodels will be available in the next TestFlight build for Juno 1.3.3 (currently in review) — if anyone would like to help test it, please reach out to beta@juno.sh, and I'll add you to our beta list. 😉

**Comment by f1se4** [comment]
Hi ++++1 :D

In fact all requirements of the packages seems to be possible to install, so it should be something ‘near’ to be implemented or possible to be implemented by installing the package.

**Comment by navoshta** [comment]
Juno 1.3 with Statsmodels is now live on App Store 🚀

**Comment by f1se4** [comment]
> Juno 1.3 with Statsmodels is now live on App Store 🚀

Yeahhhhhhhhhhhhhhhhhhhhhhhhh!! It works perfect :)
