### ISSUE TITLE
No package downloader

### ISSUE THREAD

**Issue by vinodkotagiri** [rationalmatter/Juno-Issue-Tracker#161]
**Describe the bug**
Package installer not available after recent update

**To Reproduce**

**Expected behavior**
Install additional libraries using the provided installer

**Screenshots**
![8A4A019C-80F5-4C76-A3E9-F4B7A7B4779C](https://user-images.githubusercontent.com/64140279/81811276-00aded00-9542-11ea-8db3-19c3eb56022f.png)

**Environment (please complete the following information):**
 - Device: iphone XR
 - iOS version: ios 13.3.1
 - App version: 1.2.3[5304]

**Comment by navoshta** [comment]
Hi @vinodkotagiri, package installer is available via notebook menu — tap notebook title in the editor and select Install Python Package.

The package installer button used to be in the file browser, but there were a couple of issues with that component (and 3rd party developers can't really customise it much), so I thought it would make sense to be able to install a missing package without leaving the notebook.
