### ISSUE TITLE
Add lxml

### ISSUE THREAD

**Issue by thipokKub** [rationalmatter/Juno-Issue-Tracker#162]
Please add lxml support for xml parsing

Official site: https://lxml.de/
Official PyPi: https://pypi.org/project/lxml/
Official Github: https://github.com/lxml/lxml

**Comment by thipokKub** [comment]
It seems like there is an open issue a few months ago

https://github.com/rationalmatter/Juno-Issue-Tracker/issues/66

Closing due to duplicate issue

**Comment by navoshta** [comment]
Yep you are right @thipokKub — LXML is already on the list 😉
