### ISSUE TITLE
The function ‘select all’ seems not work

### ISSUE THREAD

**Issue by kerryeva** [rationalmatter/Juno-Issue-Tracker#163]
**Describe the bug**
touch and hold, then shows ‘select, select all...’. Touch ‘select all’, the cursor moves to end of cell. Not select anything.

p.s.And I think ‘select a line‘ is more useful than ‘select all’

**Environment (please complete the following information):**
 - Device: [iPad Pro 12.9, iPad mini5]
 - iOS version: [iOS 13.2]
 - App version [1.5.5]

**Comment by navoshta** [comment]
Thanks for reporting @kerryeva — yep this will be fixed in a follow-up release shortly. Ping me at beta@juno.sh if you would like to take an early look when beta becomes available.

**Comment by navoshta** [comment]
This issue should now be fixed (and text selection greatly improved in general) in Juno 1.2.4 and Juno Connect 1.5.6 available on TestFlight (not on App Store yet).

**Comment by navoshta** [comment]
This should now be fixed on the App Store, too.
