### ISSUE TITLE
Please Include Seaborn

### ISSUE THREAD

**Issue by marshal0224** [rationalmatter/Juno-Issue-Tracker#164]
Hi, 

I love the Juno app, but it would be great if you guys could include seaborn in the package list! 

Regards,

**Comment by navoshta** [comment]
Hi @marshal0224, Seaborn seems to be a pure Python package, so you should be able to install whichever version you prefer via package installer. Or are there some issues with it perhaps?

<img width="543" alt="Screenshot 2020-05-22 at 09 15 28" src="https://user-images.githubusercontent.com/1111935/82646608-cb259580-9c0c-11ea-802f-1f466406657c.png">

**Comment by marshal0224** [comment]
Oh, Gee, I did not realize the app came with a package installer! Now I like the app even more. I have been able to install seaborn with no issue. Great work making this app!

**Comment by Yashk1997** [comment]
Hello,

I don't really know how to download the seaborn package on Juno. I did try to used the Pyhton package installer but it does not seem to find the seaborn package.

Best regards,
Yash Kapoor ![image](https://user-images.githubusercontent.com/88632932/128705162-e65bbf5d-4652-45b4-a849-a0cffc4adee0.png)

**Comment by alexstaravoitau** [comment]
@Yashk1997 What happens when you tap in the text field to bring the focus to it, and hit return? Doesn't it load the package details?

**Comment by Yashk1997** [comment]
It does not respond basically, even when I hit return.

**Comment by alexstaravoitau** [comment]
@Yashk1997 What iPadOS is installed on your device? Does this happen with the on-screen keyboard, or a hardware keyboard, or both? This seems like an issue not related to seaborn to be honest, so I suggest that you submit a separate issue and we can discuss there.

**Comment by Yashk1997** [comment]
I was able to fix it, it seems that for some reason Juno is not responding to the physical keyboard like to Copy, paste or enter it is only responding to the digital keyboard. I hope this can be fixed

**Comment by Yashk1997** [comment]
That's correct I would raise it next time but just to mention it only happens on the physical keyboard.

**Comment by alexstaravoitau** [comment]
@Yashk1997 Sure I'll be happy to fix, but I may need some additional details like iOS version, version of Juno and what kind of keyboard you have connected. This will help a lot.

**Comment by Yashk1997** [comment]
IPAD OS 15
Bluetooth apple keyboard 
Juno 1.3.9
