### ISSUE TITLE
Add Quandl

### ISSUE THREAD

**Issue by jammin0921** [rationalmatter/Juno-Issue-Tracker#17]
**What is the name of the package?**
A name or link to the Python package you think should be pre-installed in Juno.

https://pypi.org/project/Quandl/

Maybe not necessary to have it pre-installed when someone downloads the app but would be nice to have the option to add it. It does require pandas so it would have to come after that too.

**Comment by navoshta** [comment]
Juno now ships with Pandas, and this package seems to install OK with Juno's [new package installer](https://github.com/rationalmatter/Juno-Issue-Tracker/issues/37#issuecomment-529098898). Please, reopen if it doesn't work as expected.
