### ISSUE TITLE
Juno connects to server but not to kernel

### ISSUE THREAD

**Issue by NawfalTachfine** [rationalmatter/Juno-Issue-Tracker#172]
I am setting up a Python development environment using the Blink shell, a DigitalOcean droplet and Juno Connect. I’m using an 11” 2018 iPad Pro with iOS 13.5.
I followed the instructions in the official guide to setup SSH port forwarding and produce the self-signed SSL/TLS certificate.
Juno connects to the server but cannot reach the notebook kernel. I get the red warning strip on top, saying “Server has invalid SSL certificate. Tap here to fix” but tapping the link just opens the guide I have already followed.
I tried disabling HTTPS in the connection parameters. It did not help.
Jupyter notebook is fully accessible via Safari by the way.
I’d more than happy to provide any additional information about my environment.
Thank you Juno team. You’re really onto something here :)

**Comment by navoshta** [comment]
Hi @NawfalTachfine — apologies for a late reply.

> Jupyter notebook is fully accessible via Safari by the way.

Is it accessible without SSH tunnel, i.e. by simply using server's address? Does the kernel connect in Safari, too? Also, could you please clarify if you are connecting to your Jupyter server directly (i.e. direct connection in Juno Connect), or via port forwarding? 

You typically don't need HTTPS if you connect via port forwarding, although nothing is stopping you from using HTTPS, of course (see more on port forwarding connections [here](https://juno.sh/ssh-tunnel-to-jupyter-server/)). However, keep in mind that if you do plan to use both port forwarding _and_ HTTPS, your SSL certificate needs to be issued for the domain Juno Connect will be connecting to, i.e. "localhost".

**Comment by NawfalTachfine** [comment]
I changed my setup so I cannot reproduce this anymore. Thanks!
