### ISSUE TITLE
Add GDAL

### ISSUE THREAD

**Issue by MarconiS** [rationalmatter/Juno-Issue-Tracker#174]
GDAL ( https://pypi.org/project/GDAL/) is the core library for pretty much any geospatial - gis library in python. Again, thanks for the amazing job you all are doing in developing Juno!

**Comment by alexstaravoitau** [comment]
GDAL should now be available in the last TestFlight build of Juno (1.3.12). Please let me know if you spot any issues — if you're not on TestFlight and would like to help test it, ping me at beta@juno.sh.

**Comment by alexstaravoitau** [comment]
GDAL has now been added as a part of Juno 1.3.14 update 🎉
