### ISSUE TITLE
AttributeError: module 'os' has no attribute 'fork'

### ISSUE THREAD

**Issue by Delta22627** [rationalmatter/Juno-Issue-Tracker#177]
**Describe the bug**
Show ```AttributeError: module 'os' has no attribute 'fork'``` instead of printing the results.

**To Reproduce**
```python
from multiprocessing import Pool
def f(x):
    return x*x

with Pool(5) as p:
    print(p.map(f, [1, 2, 3]))
p.close()
```
**Environment (please complete the following information):**
 - Device:  iPad Pro 11" gen 1
 - iOS version: iPadOS 13.5.1
 - App version 1.2.6 (5446)

**Comment by navoshta** [comment]
Hi @Delta22627, I'll try to make the error a bit more user-friendly — however, I'm afraid you wouldn't be able to spawn new processes anyway, due to OS restrictions. Neither iOS nor iPadOS currently allows multi-processing.
