### ISSUE TITLE
Add regex

### ISSUE THREAD

**Issue by Sven-git** [rationalmatter/Juno-Issue-Tracker#178]
**What is the name of the package?**
A name or link to the Python package you think should be pre-installed in Juno. Mind that you can install pure Python packages from PyPI in Juno — those that can be successfully installed won't be embedded in the app.

I would like to install nltk and all packages it depends on. Regex is one of those, but there might be others.

**Comment by dimapaloskin** [comment]
Seems it's possible to use a monkey patch to run `nltk`.
Not sure if this works in all cases but looks like basic operations works fine.

```python
import sys

# monkey patch
sys.modules["regex"] = __import__("re")
```

```python
import nltk

nltk.data.path.append(".")
```

```python
nltk.download("punkt", download_dir=".")
```

```python
nltk.download("averaged_perceptron_tagger", download_dir=".")
```

```python
sentence = "seems working"

tokens = nltk.word_tokenize(sentence)
tags = nltk.pos_tag(tokens)

tags
```

Of course  it's not the solution for this particular issue

**Comment by argenismartinez** [comment]
It's a workaround, but a pretty nice one. I will def try it out.

**Comment by argenismartinez** [comment]
> Seems it's possible to use a monkey patch to run `nltk`.
> 
> Not sure if this works in all cases but looks like basic operations works fine.
> 
> 
> 
> ```python
> 
> import sys
> 
> 
> 
> # monkey patch
> 
> sys.modules["regex"] = __import__("re")
> 
> ```
> 
> 
> 
> ```python
> 
> import nltk
> 
> 
> 
> nltk.data.path.append(".")
> 
> ```
> 
> 
> 
> ```python
> 
> nltk.download("punkt", download_dir=".")
> 
> ```
> 
> 
> 
> ```python
> 
> nltk.download("averaged_perceptron_tagger", download_dir=".")
> 
> ```
> 
> 
> 
> ```python
> 
> sentence = "seems working"
> 
> 
> 
> tokens = nltk.word_tokenize(sentence)
> 
> tags = nltk.pos_tag(tokens)
> 
> 
> 
> tags
> 
> ```
> 
> 
> 
> Of course  it's not the solution for this particular issue


It's a workaround, but a pretty nice one. I will def try it out.

**Comment by navoshta** [comment]
Juno 1.3 with Regex is now live on App Store 🚀
