### ISSUE TITLE
AWS SageMaker Notebook Support

### ISSUE THREAD

**Issue by sandeepmistry** [rationalmatter/Juno-Issue-Tracker#182]
**Is your feature request related to a problem? Please describe.**
I'm currently using [AWS SageMaker Notebook](https://docs.aws.amazon.com/sagemaker/latest/dg/nbi.html), however I'm unable to use them with Juno Connect on my iPad.

I believe it's because the AWS SageMaker web console attempts to open the Jupyter notebook in a new window.

**Describe the solution you'd like**

The ability to use Juno Connect on iPad with AWS SageMaker :)

**Comment by navoshta** [comment]
Thanks for reporting @sandeepmistry, I'll take a look — if it's something minor, I'll update the way Juno Connect handles new tabs/windows to support SageMaker, too (although we do have plans to integrate with SageMaker in a more user-friendly manner, eventually).

**Comment by jjay0258** [comment]
what is the progress on this issue?

**Comment by navoshta** [comment]
Apologies @jjay0258, I didn't get a chance to look into this yet. Porting more libraries to Juno is the main priority right now, although we do work on some Juno Connect specific features as well in the meantime.

**Comment by navoshta** [comment]
Juno Connect 1.6.3 adds experimental Amazon SageMaker support — it's currently in beta, but if you would like to help test it, please send an email to beta@juno.sh and I will add you to our TestFlight! 😉

**Comment by navoshta** [comment]
Experimental SageMaker support has been released to App Store, so I'm closing this ticket for now — feel free to reopen or submit a new one if you spot any issues with it.
