### ISSUE TITLE
Add keyboard shortcut to run all cells

### ISSUE THREAD

**Issue by multinormal** [rationalmatter/Juno-Issue-Tracker#183]
While there is a keyboard shortcut for running the current cell, there does not appear to be one for running all cells (i.e., from first to last, sequentially). This would be incredibly useful for getting real work done.

I suggest the shortcut Command+Shift+R or Command+Option+R.

It may be sensible to add UI for this, too. For example, a long press on the run button could bring up a pop-up menu with an option to run all cells.

**Comment by navoshta** [comment]
Thanks for reporting @multinormal — yep the keyboard shortcut is missing, but I'll add it. The UI you have described is already available in both Juno and Juno Connect. 😉 The pop-up menu will let you switch default run button action (e.g. run and select next, run all cells, etc.).

**Comment by navoshta** [comment]
Juno 1.3 with a new key shortcut is now live on App Store 🚀 — use Control+Shift+Alt+Enter to run all cells (seems like this key combination is already used to run all cells in several alternative Jupyter editors, hence the choice).
