### ISSUE TITLE
Juno sometimes crashes on launch

### ISSUE THREAD

**Issue by dkirkby** [rationalmatter/Juno-Issue-Tracker#184]
Just installed Juno yesterday from the app store.

**Describe the bug**
When returning to an earlier Juno session, using the icon from the home screen, the program immediately exits and I am back at the home screen.  Touching the Juno icon a second time works and displays the correct nb but with a restarted kernel.

**To Reproduce**
1. Open a new notebook
2. Execute a few cells to generate some kernel context (was trying it out for the first time)
3. Use other apps.
4. Return to Juno.

**Expected behavior**
Juno should launch with the current notebook displayed and kernel restored to its previous state

**Screenshots**
**Environment (please complete the following information):**
 - Device: iPad Pro (12.9-inch) (3rd generation)
 - iOS version: 13.5.1
 - App version 1.2.6

**Comment by dkirkby** [comment]
A bit more info: I have experienced 2 crashes like this since I installed for the first time yesterday.  Both were after the iPad had been closed for a while, in addition to running other apps.

Here is an asciidoc of the nb I had open, in case that's relevant:
```
+*In[1]:*+
[source, ipython3]
----
# Welcome to Juno!
#
# This document is called Jupyter notebook. 'Run' button will evaluate selected cell, and code output will appear in the cell output area below.
#
# Give it a go:
print("Hello, world!")
----


+*Out[1]:*+
----
Hello, world!
----


+*In[3]:*+
[source, ipython3]
----
%pylab inline
----


+*Out[3]:*+
----
Populating the interactive namespace from numpy and matplotlib
----


+*In[4]:*+
[source, ipython3]
----
import scipy.optimize
----


+*In[9]:*+
[source, ipython3]
----
import requests
----


+*In[11]:*+
[source, ipython3]
----
r = requests.get('https://www.python.org')
----


+*In[14]:*+
[source, ipython3]
----
r.status_code
----


+*Out[14]:*+
----200----


+*In[15]:*+
[source, ipython3]
----
plt.plot(np.sin(np.linspace(0, 5)))
----


+*Out[15]:*+
----[<matplotlib.lines.Line2D at 0x11cc7d7b8>]
![png](Untitled_files/Untitled_6_1.png)
----


+*In[16]:*+
[source, ipython3]
----
def solve(X):
    print(X.shape)

solve(np.zeros((5, 3)))
----


+*Out[16]:*+
----
(5, 3)
----


+*In[20]:*+
[source, ipython3]
----
np.isin([1, 3], np.arange(10))
----


+*Out[20]:*+
----array([ True,  True])----


+*In[1]:*+
[source, ipython3]
----
solve(np.ones(3))
----


+*Out[1]:*+
----

    ---------------------------------------------------------------------------

    NameError                                 Traceback (most recent call last)

    <ipython-input-1-c48ba52ff802> in <module>
    ----> 1 solve(np.ones(3))


    NameError: name 'solve' is not defined

----

latexmath:[\[
\int_0^\infty r\rightarrow \infty + \ldots \alpha, \beta, \gamma
\]]


+*In[21]:*+
[source, ipython3]
----
sys.version
----


+*Out[21]:*+
----'3.6.6+ (default, Sep 19 2019, 20:17:55) \n[GCC 4.2.1 Compatible Apple LLVM 11.0.0 (clang-1100.0.33.5)]'----


+*In[22]:*+
[source, ipython3]
----
1+1
----


+*Out[22]:*+
----2----


+*In[ ]:*+
[source, ipython3]
----
import
----
```

**Comment by navoshta** [comment]
Thanks for reporting @dkirkby! Looks like Juno is crashing when returning from background just before it gets suspended by the OS — I will look into this.

**Comment by alexstaravoitau** [comment]
Juno 2.0 and 2.1 releases address a whole suite of crashes related to background persistence — hopefully, including this one.
