### ISSUE TITLE
Add cryptography

### ISSUE THREAD

**Issue by mohabouje** [rationalmatter/Juno-Issue-Tracker#186]
I’m trying to install several packages from pip that rely on the cryptography package but somehow Juno does not allow me to install the package. It does mention that there is no supported distribution. I’ve tried several versions, no success so far.

Juno; 1.2.6
iPad Pro 2020

**Comment by navoshta** [comment]
Thanks for reporting @mohabouje — cryptography has native extensions, which need to be ported to iOS and embedded in the app bundle, similar to what we did with NumPy, Pandas, Scipy etc. to get them to work. I'll change this issue labels to a package request.

**Comment by navoshta** [comment]
Actually sorry, I just realised there is already an open ticket for `cryptography` package — see #111. I'll close this one as a duplicate.
