### ISSUE TITLE
Add **regex**

### ISSUE THREAD

**Issue by argenismartinez** [rationalmatter/Juno-Issue-Tracker#188]
**regex**
For nltk package to be imported successfully, regex python package needs to be available.

I have installed nltk package through Juno installer but when importing, I am getting a error stating that there is no regex module.

Steps to reproduce:
- Use Juno Package installer to install nltk
- Import nltk to a notebook
- Error message should show saying that there is no regex module

Regards.

And thank you very much for this awesome app...:)

**Comment by zekekoch** [comment]
just hit this one myself. thanks!

**Comment by navoshta** [comment]
Yep thanks @zekekoch — I'll close this issue as a duplicate, feel free to upvote #178 instead.
