### ISSUE TITLE
Authorisation to Azure notebooks via institutional login

### ISSUE THREAD

**Issue by risa** [rationalmatter/Juno-Issue-Tracker#191]
When authorizing to Azure notebooks, I want to use my university Microsoft account. Into the login page I enter my university email (you can try e.g. somebody@upol.cz). I get redirected to the university page, which responds with HTTP 401 and expects the browser to raise a login dialog. Juno connect does not display this dialog, so the login is not possible. 

**To Reproduce**
1. Go to Azure Networks 
2. Enter an address for ms account with company authorization - e.g. somebody@upol.cz
3. Watch the redirection
4. See HTTP 401 Error which you should see a login dialog.

The login process works well in normal browser. 

**Expected behavior**
See the login dialog for username and password.

**Screenshots**
If applicable, add screenshots or a screen recording to help explain your problem.

**Environment (please complete the following information):**
 - Device: iPad Pro 11"
 - iOS version: IPadOS 14.0 (18A5319i)
 - App version 1.5.8 (5446)

<img width="1194" alt="Juno connect screenshot" src="https://user-images.githubusercontent.com/1949242/87859319-a3b12780-c934-11ea-87f8-f7d63f94d837.png">

**Comment by risa** [comment]
However I just found out that the Azure notebooks are being retired soon, so I do not know if it is worth solving anyway :-(

**Comment by navoshta** [comment]
Thanks for reporting @risa — yes you are right, Azure Notebooks will get decomissioned soon, unfortunately... I'll look into this in case it's something easy to fix though. Meanwhile, I'd give CoCalc a go, or if your university is using Azure Notebooks specifically, let me know what they plan to switch to when AN are retired.
