### ISSUE TITLE
Cannot open Jupyter extension files after iOS update 13.6

### ISSUE THREAD

**Issue by wb19529** [rationalmatter/Juno-Issue-Tracker#192]
**Describe the bug**
I cannot longer able to open Jupyter files (extension .IPYNB) after I upgraded iOS to version 13.6; the files can be locally saved on my iPad or on iCloud Drive, it doesn’t matter.

**To Reproduce**
1. Launch Juno for Jupyter
2. Tap on any file with extension .IPYNB, but all of them are dimmed (so, not able to tap on them).
3. No error, just files show dimmed and cannot be clicked or selected to be open.

**Expected behavior**
Before upgrading to iOS version 13.6, I was able to open any Jupyter file without issues.

**Screenshots**
![Juno for Jupyter issue](https://user-images.githubusercontent.com/36242828/87963142-44fbc300-ca86-11ea-8eac-f43639be44e7.jpeg)

**Environment (please complete the following information):**
 - Device: iPad Pro 11"
 - iOS version: iOS 13.6
 - App version 1.2.6 (5446)

**Comment by navoshta** [comment]
Hi @wb19529 — looks very odd! I have tried iOS 13.6 and iOS 14 beta, and it seems to be working fine on both. In fact, looks like in your case notebook file type association is broken entirely: there isn't even a Jupyter icon on the file, which Juno provides if the document type is associated with it — if you haven't already, try restarting device and re-installing Juno from scratch. 

Have you installed any other apps working with Jupyter notebooks recently? Take a look at #55, perhaps it's the same issue?

**Comment by wb19529** [comment]
Hi Alex:

	Yes, my issue was exactly the same as #55: I had the “Notebook Master for Jupyter” installed, but the funny thing is: I had that installed maybe like a year ago (way before I installed Juno, but it showed now, after iOS 13.6 update), but anyhow, that was my exact issue. I deleted the app, restarted the iPad, and now I’m able to see the Notebook files again, etc.

	Thanks again for your help/advices on resolving this; the case can be close now.

**Comment by navoshta** [comment]
Awesome — glad it's resolved!
