### ISSUE TITLE
Code Completion UI Error

### ISSUE THREAD

**Issue by Molin-L** [rationalmatter/Juno-Issue-Tracker#193]
**Describe the bug**
When I run the first line of code, the code completion panel pop at the left-top of notebook.

**To Reproduce**
Simply run the first code block.

**Expected behavior**
It should not appear.

**Screenshots**

![IMG_0151](https://user-images.githubusercontent.com/25400909/88495601-54ad6700-cfb2-11ea-9f58-024c6c56e2c7.png)

**Environment (please complete the following information):**
 - Device: iPad Pro 2020
 - iOS version: iOS 13.6
 - App version 1.5.8

**Comment by navoshta** [comment]
Thanks for reporting @Molin-L, I will look into it! Does this happen on every notebook, or just this one, or maybe intermittently on various notebooks?

Either way it's a bug of course — notebook is in command mode and shouldn't display code completion at all.

**Comment by Molin-L** [comment]
> Thanks for reporting @Molin-L, I will look into it! Does this happen on every notebook, or just this one, or maybe intermittently on various notebooks?
> 
> Either way it's a bug of course — notebook is in command mode and shouldn't display code completion at all.

Hi Navoshta!

Yes, it happens in every notebook, not just this one. Especially `torch`, because there three options for code completion. I mean it may happen in any block as long as it triggers code completion.

Check this screen record on google drive:
[screen record](https://drive.google.com/file/d/1UYWybmOyzhMVxO8H7GrauNCLFUF7V9uj/view?usp=sharing)

Here are some tips for reproduction:
1. _Restart and clear output_. But it seems not very necessary. Sometimes at the first run, it will also happen. 
2. Make sure your curse is exactly at the position which has code completion options. In my case, it was at the end of `import torch`.

**Comment by navoshta** [comment]
Thanks for the detailed info @Molin-L — looks like completion suggestions are arriving with a slight delay from the server's kernel, when notebook is already in command mode. Juno Connect should ignore those delayed suggestions, I'll fix this in the next update.
