### ISSUE TITLE
Add pandas

### ISSUE THREAD

**Issue by desilinguist** [rationalmatter/Juno-Issue-Tracker#2]
**What is the name of the package?**

http://pandas.pydata.org/

**Comment by Sakelariev** [comment]
Hi @navoshta I tried adding pandas using the suggested method by copying the folder into site-packages, but when I try to `import pandas as pd` I get this error - ImportError: Missing required dependencies ['pytz']

On iPad 6 
pandas 0.24.2

Should I add a separate issue for this?

**Comment by navoshta** [comment]
Hi @Sakelariev, unfortunately, you can't install Pandas by simply copying it into site-packages, as Pandas has some native extensions that need to be compiled into native code. It needs to be included in Juno in a way similar to NumPy and Matplotlib. 

I'm certainly going to look into adding Pandas though, as this is requested a lot.

**Comment by wolf71** [comment]
+1 Pandas

**Comment by navoshta** [comment]
Pandas 0.25 added in Juno 1.0.4 🎉
