### ISSUE TITLE
Kernel not starting

### ISSUE THREAD

**Issue by antony-frolov** [rationalmatter/Juno-Issue-Tracker#200]
**Describe the bug**
Was trying to open a file in a folder named in Russian and the Python kernel didn’t start

**To Reproduce**
1. Go to folder name in Russian
2. Tap on any ipython notebook
4. See kernel loading forever

**Expected behavior**
For the kernel to start

**Screenshots**
If applicable, add screenshots or a screen recording to help explain your problem.

**Environment (please complete the following information):**
 - Device: [e.g. iPad Pro 12.9"]
 - iOS version: [e.g. iOS 14 public beta 4]
 - App version [e.g. 1.2.8
![77BD9235-9D96-4F6E-8569-2012268DF286](https://user-images.githubusercontent.com/69483357/89828072-370b0080-db61-11ea-9179-833433750384.jpeg)
![F4639923-1C1E-4BD6-B0FD-5091A5B50C09](https://user-images.githubusercontent.com/69483357/89828082-396d5a80-db61-11ea-962e-80877def6670.jpeg)

]

**Comment by navoshta** [comment]
Thanks for reporting @antony-frolov, I will take a look! Most likely this is related to how Jupyter handles file paths. I'm pretty sure I've tried it with non-English Unicode characters before, and it seemed to work... Perhaps something changed in iOS 14 — I will investigate.

**Comment by navoshta** [comment]
@antony-frolov This should now be fixed in the most recent beta build, Juno 1.3.0 on TestFlight. If you're not on our TestFlight and would like to help test Juno, please ping me at beta@juno.sh, and I'll add you to our beta list. 😉

**Comment by navoshta** [comment]
Juno 1.3 with a fix is now live on App Store 🚀
