### ISSUE TITLE
Local port forwarding insecure exposing jupyter notebook port

### ISSUE THREAD

**Issue by xxsl** [rationalmatter/Juno-Issue-Tracker#204]
**Describe the bug**
I found that if I use the Local port forwarding, iPhone will listen a new port (in my case 49831) on 0.0.0.0 and forward all traffic to jupyter server port (default 8888).

This behavior will be a big security hole as most of time user mobile phone will be in WiFi lan (Also in some country mobile provider even give each 4G link a dedicated public ip !), bad guy can then connect to jupyter secretly by connecting that port. 

**To Reproduce**
1. Using Local port forwarding to connect a jupyter server.
2. Tap on server title and you will find a url such as "http://localhost:49831"
3. Note the port number "49831"
4. Discover other ip address your iPhone have, such as WiFi lan or 4G link, let's pretend 192.168.1.100.
5. Access from other host to http://192.168.1.100:49831

**Expected behavior**
App should listen on 127.0.0.1 instead of 0.0.0.0 inside local port forwarding implement. Or give a parameter to let use determine listen addr.

**Screenshots**
If applicable, add screenshots or a screen recording to help explain your problem.

**Environment (please complete the following information):**
 - Device: iPhone
 - iOS version: iOS 13.6.1
 - App version 1.5.10 (5553)

**Comment by navoshta** [comment]
Apologies for a late reply @xxsl — thanks for reporting, this will be fixed in the next release. Yes, Juno Connect binds a random available port while establishing a tunnel, and looks like the library we are using binds on `0.0.0.0` by default (which is quite surprising, frankly). Once again, thanks for reporting!

**Comment by navoshta** [comment]
This should be fixed in Juno Connect 1.5.11, which is now live on App Store.
