### ISSUE TITLE
Bokeh library

### ISSUE THREAD

**Issue by MarcoLeder** [rationalmatter/Juno-Issue-Tracker#206]
Dear Juno devs

Nice app, however, I am not able to install bokeh 2.x.x library. 

This should however work, since I was able to install it in Pythonista3 (which indicates that it is a pure-python library).

As far as I am concerned, the error lies in the pillow imaging library.

Thank you for taking the time to solve this
Best, Marco Leder

**Comment by navoshta** [comment]
Hi @MarcoLeder — yep, looks like it has a dependency on Pillow, which has native extensions and needs to be ported first. There is already a ticket for it #190, so most likely when it's resolved, bokeh should just start working right away. I'll keep this issue open for now, just in case.

I don't have any ETA for PIL (#190) I'm afraid, but we will likely start looking into it shortly after we include LXML (#66).

**Comment by navoshta** [comment]
@MarcoLeder Pillow (PIL fork) will soon be available in Juno beta — ping me at beta@juno.sh if you would like to help test it, and I'll add you to our TestFlight. 😉

**Comment by MarcoLeder** [comment]
Thank you ever so much and that you thought of me! Eycited to try it soon!

Best regards
Marco Leder

**Comment by navoshta** [comment]
Juno 1.3 with Bokeh is now live on App Store 🚀
