### ISSUE TITLE
Plotly can't work in Juno Connect

### ISSUE THREAD

**Issue by odie2630463** [rationalmatter/Juno-Issue-Tracker#208]
Hi Juno dev

Plotly can work on safari with my iPad Pro , but can't draw plot in Juno Connect
Hope can fix it , thanks a lot

**Environment (please complete the following information):**
 - Device: iPad Pro 12.9
 - iOS version: iOS 14.2
 - App version: latest

**Comment by odie2630463** [comment]
Hi , all 
I fixed this problem by change render on iPad Pro

``` python
import plotly.io as pio
pio.renderers.default = "notebook_connected"
```

**Comment by navoshta** [comment]
Great, glad you worked it out @odie2630463 — this does indeed look like a plotly configuration issue. I'll close the issue for now. 🙂
