### ISSUE TITLE
Failed to display notebook

### ISSUE THREAD

**Issue by muammar** [rationalmatter/Juno-Issue-Tracker#209]
**Describe the bug**
Any time I try to open a notebook (or create one), I receive an error: `Failed to display notebook`. 

**To Reproduce**
1. Connect to a server.
2. Tap on existing notebook or create a new one. 
3. Juno connect reports `Failed to display notebook`.

**Expected behavior**
Reder a notebook to interact with. 

**Environment (please complete the following information):**
 - Device: iPad Pro 12", 2018
 - iOS version: 14.0.1
 - App version: 1.5.11

** Screenshot
![F0BF5753-BDEE-4781-BAF5-F0E00CA9524D](https://user-images.githubusercontent.com/954209/96197968-4cf1c480-0f08-11eb-9731-30e8204a79c4.png)

**Comment by muammar** [comment]
JFTR, I just verified I had the certificate correctly installed on my iPad. I can confirm that I can interact with the notebook on the Safari web browser.

**Comment by muammar** [comment]
I fixed it; after verifying that the certificate was correctly installed, I found this error on my server: 

```
AttributeError: module 'nbconvert.exporters' has no attribute 'WebPDFExporter'
```

After a ` pip install nbconvert`And cleaning the cache of the connection, the problem got fixed.

**Comment by navoshta** [comment]
Great! Glad you fixed it @muammar 🙂
