### ISSUE TITLE
How to delete Jupyter servers?

### ISSUE THREAD

**Issue by craldaz** [rationalmatter/Juno-Issue-Tracker#211]
I’m not sure if this is a bug because just starting with Juno connect. 

But  I created a bunch of Jupyter servers to try to get it to connect and now I can’t figure out how to delete the ones that were bad.

Your help is appreciated.

**Comment by navoshta** [comment]
Hi @craldaz — you should be able to delete/edit connections if you swipe left on the item in the list of servers. I'll think of a way to make this a bit more intuitive (or perhaps at least mention this in the FAQ!).

**Comment by craldaz** [comment]
Thank you! It works :)
