### ISSUE TITLE
Add google-cloud-bigquery

### ISSUE THREAD

**Issue by christopherseaman** [rationalmatter/Juno-Issue-Tracker#214]
Requesting support or inclusion of `google-cloud-bigquery[pandas]`

The google-cloud-bigquery package does not successfully load using `%load_ext google.cloud.bigquery` or `from google.cloud import bigquery` even when all dependencies are present in site-packages bc it depends on a newer version of six than included in Juno. There may be a workaround for this using `require`, but I couldn't convince pkg_resources to load the newer one from site-packages instead of built-in.

**Comment by navoshta** [comment]
Thanks for reporting @christopherseaman — am I correct assuming that the outdated version of `six` is the only issue that prevents `google-cloud-bigquery` from getting imported correctly?

I'll certainly try to upgrade it in next release (hopefully there won't be any dependency issues with Jupyter or Juno internals). Meanwhile, I'm not sure myself how you could force Python to use the one in /site-packages — it will likely require an app update.

**Comment by christopherseaman** [comment]
Thanks for the quick response.

I'll admit that I haven't run down the list of deps to see what else may need to be upgraded. Obviously, if you can get either of those load statements running without error, that'd be a great start. I installed a working set of site-packages on Ubuntu 18.04 (closest match to Juno versions I could find) and put it in the cloud to make it easier to get onto the iPad; if it helps to work through dependencies, you can find it here: https://www.dropbox.com/s/vo6lgmks05s65ux/site-packages.tar.xz?dl=0

Happy to help test if that would be helpful.

**Comment by navoshta** [comment]
No worries @christopherseaman — I'll add an internal task to update `six` and will leave this issue as is for now. 

Also, I've tried to prepare a environment.yml file with the packages that come with Juno pre-installed — perhaps you will find it useful. It lists `pip`, which is in fact not available in Juno, but only because some packages are not available in `conda`, so you would need `pip` to prepare a conda environment from this file: [environment.yml.zip](https://github.com/rationalmatter/Juno-Issue-Tracker/files/5502356/environment.yml.zip)

**Comment by christopherseaman** [comment]
Started from a clean slate and used your environment.yml. Looks like `six` was the only package with a version conflict (1.12 → 1.15, but 1.13 should suffice).

> %pip install --upgrade 'google-cloud-bigquery[pandas]' --no-cache

```
Collecting google-cloud-bigquery[pandas]
...
Installing collected packages: pycparser, cffi, google-crc32c, six, google-resumable-media, protobuf, proto-plus, pyasn1, pyasn1-modules, cachetools, rsa, google-auth, urllib3, idna, chardet, requests, googleapis-common-protos, grpcio, google-api-core, google-cloud-core, pyarrow, google-cloud-bigquery
  Found existing installation: six 1.12.0
    Uninstalling six-1.12.0:
      Successfully uninstalled six-1.12.0
Successfully installed cachetools-4.1.1 cffi-1.14.3 chardet-3.0.4 google-api-core-1.23.0 google-auth-1.23.0 google-cloud-bigquery-2.4.0 google-cloud-core-1.4.3 google-crc32c-1.0.0 google-resumable-media-1.1.0 googleapis-common-protos-1.52.0 grpcio-1.33.2 idna-2.10 proto-plus-1.11.0 protobuf-3.14.0 pyarrow-2.0.0 pyasn1-0.4.8 pyasn1-modules-0.2.8 pycparser-2.20 requests-2.25.0 rsa-4.6 six-1.15.0 urllib3-1.26.2
```

**Comment by navoshta** [comment]
Thanks for checking @christopherseaman — I'll make sure to update `six` in the next Juno release. I don't have any ETA for it I'm afraid, but hopefully it will arrive in a matter of weeks alongside LXML addition to Juno.

**Comment by navoshta** [comment]
Apologies it took a while @christopherseaman — I've updated `six` in the most recent beta build, Juno 1.3.0 on TestFlight. If you're not on our TestFlight and would like to help test Juno, please ping me at beta@juno.sh, and I'll add you to our beta list. 😉

**Comment by christopherseaman** [comment]
Thanks for the follow-up. Emailed to request access.

**Comment by christopherseaman** [comment]
Tested loading the google-cloud-bigquery module and it worked!

Actually querying is running into an error with pyarrow but that _may_ be solvable with some site-packages work.

**Comment by navoshta** [comment]
Thanks for verifying @christopherseaman — I'll close this issue, but feel free to open a new one if you find that `google-cloud-bigquery` has some other dependencies which are unavailable.
