### ISSUE TITLE
Help functions not working

### ISSUE THREAD

**Issue by method-marco** [rationalmatter/Juno-Issue-Tracker#217]
**Describe the bug**
The help() function is not working correctly. Sometimes the output is not shown.

**To Reproduce**
Execute:
	help(abs)

**Expected behavior**
Prints the help for the abs function

**Environment (please complete the following information):**
 - Device: iPad Pro 12" 2020
 - iOS version: iOS 14

**Comment by navoshta** [comment]
Thanks for reporting @method-marco — I'm assuming this is for Juno, not Juno Connect? Could be something with how we embed those modules then.

**Comment by method-marco** [comment]
> Thanks for reporting @method-marco — I'm assuming this is for Juno, not Juno Connect? Could be something with how we embed those modules then.

Yes, it’s with Juno and not with Juno Connect. I can reproduce it with builtins and other imports.

**Comment by navoshta** [comment]
Juno 1.3 with a fix is now live on App Store 🚀

Looks like Jupyter doesn't work well with `help()` in general, so I suggest that you use a built-in magic `?`, e.g.:

```py
abs?
```

...Or just put your cursor to the abs function, tap the screen and select 'Help'.
