### ISSUE TITLE
Ipynb files are grayed out. I tried everything on your forums but it does not work

### ISSUE THREAD

**Issue by ozsilahtar** [rationalmatter/Juno-Issue-Tracker#219]
**Describe the bug**

**To Reproduce**
2. Tap on '....'

**Expected behavior**

**Screenshots**
If applicable, add screenshots or a screen recording to help explain your problem.

**Environment (please complete the following information):**
 - Device: [e.g. iPad Pro 11"]
 - iOS version: [e.g. iOS 12.2]
 - App version [e.g. 1.0.0]

**Comment by navoshta** [comment]
Hi @ozsilahtar, you probably saw this already, but just in case please take a look at #55 — perhaps you have another app installed, which is abusing iOS file association? A likely candidate is [Notebook Master](https://apps.apple.com/app/id1326802832).

**Comment by navoshta** [comment]
Closing for now, but feel free to reopen or submit a new issue if you are still experiencing this issue with the latest release.
