### ISSUE TITLE
Enable Split View mode

### ISSUE THREAD

**Issue by kappesLab** [rationalmatter/Juno-Issue-Tracker#224]
I would like to have the possibility to view both Juno and Safari on iPad at the same time.

This would be very useful in order to make full and optimal use of Juno's (Jupiter's) extraordinary capabilities.

**Comment by navoshta** [comment]
Hi @kappesLab, this should be possible in both Juno and Juno Connect — both apps support iPadOS's split screen mode. Please, reopen and let me know if I misunderstood your request, or if it's not working for you.

**Comment by kappesLab** [comment]
Thank you for the quick response. You did not misunderstand, it was my mistake. It confirms that the Split View works.
