### ISSUE TITLE
Editable configurations

### ISSUE THREAD

**Issue by hschellman** [rationalmatter/Juno-Issue-Tracker#227]
**Is your feature request related to a problem? Please describe.**
I just started using juno connect and so far have created 3 profiles trying to connect to my server.  There seems to be no way to view or edit a profile (port connection) once it is set up.  Not being able to even view  what failed means I keep repeating mistakes

**Describe the solution you'd like**

I’d like a way to view the configuration i set and if possible edit it instead of making a new one. 

Being able to delete the failures would also be nice.  

I may be missing something but I can’t find any way to manipulate profiles after they are made.  I see my screen filling with dead ones, which are now being called try again 1, try again 2 ....

**Comment by navoshta** [comment]
Hi @hschellman — you should be able to edit or delete existing configurations by swiping it in the list, swipe will reveal available actions (e.g. edit, delete or disconnect active SSH tunnel).
