### ISSUE TITLE
When I try to open a new document my iPad is not able to do so.

### ISSUE THREAD

**Issue by M3SHack** [rationalmatter/Juno-Issue-Tracker#228]
**Describe the bug**

**To Reproduce**
2. Tap on '....'

**Expected behavior**

**Screenshots**
If applicable, add screenshots or a screen recording to help explain your problem.

**Environment (please complete the following information):**
 - Device: [e.g. iPad Pro 11"]
 - iOS version: [e.g. iOS 12.2]
 - App version [e.g. 1.0.0]

**Comment by navoshta** [comment]
Thanks for reporting @M3SHack — what is exactly the problem? Does it give you an error, or what exactly happens? Are you trying to create a new document from Juno's file browser, in Juno's directory, or somewhere else?

**Comment by M3SHack** [comment]
I am able to create a new document, but once it is made it grays out and will not allow me to do anything with it. Furthermore, once the file is made a pop up will appear stating that the file can not be opened.
