### ISSUE TITLE
I get a prompt saying:

### ISSUE THREAD

**Issue by M3SHack** [rationalmatter/Juno-Issue-Tracker#229]
Failed to open notebook
The operation couldn't be completed. (Com.apple.DocumentManager error 1.)

**Describe the bug**

**To Reproduce**
2. Tap on '....'

**Expected behavior**

**Screenshots**
If applicable, add screenshots or a screen recording to help explain your problem.

**Environment (please complete the following information):**
 - Device: [e.g. iPad Pro 11"]
 - iOS version: [e.g. iOS 12.2]
 - App version [e.g. 1.0.0]

**Comment by navoshta** [comment]
Hi @M3SHack — is this related to the issue you submitted earlier, #228, or is it a separate one?
