### ISSUE TITLE
Juno shows empty docstring

### ISSUE THREAD

**Issue by talexxx** [rationalmatter/Juno-Issue-Tracker#234]
**Describe the bug**
I would expect to get the docstring for python functions when pressing "shift+tab", instead the docstring window pops up but it is empty. This is a key functionality for me. Looking for feedback if this is something that can be fixed or it is not planned... 

**To Reproduce**
1. Open a new notebook in Juno
2. write print(3)
3. move cursor between letters n and t
4. press "shift+tab"

**Expected behavior**
I would expect to see the full docstring for the function print. Instead there is a pop-up, but it does not contain the docstring info for the function.

**Screenshots**
https://ibb.co/qrRLfjZ

**Environment (please complete the following information):**
 - ipad pro 12.9" running latest ios and juno versions

**Comment by navoshta** [comment]
Thanks for reporting @talexxx, I will look into this — this is probably related to #217, too.
