### ISSUE TITLE
Side panel for servers does not close.

### ISSUE THREAD

**Issue by pumplerod** [rationalmatter/Juno-Issue-Tracker#236]
**Describe the bug**
I can no longer get a full window of my Jupyter session.  The left side panel showing optional servers to connect with always remains open.  Is there a way to close that?

**To Reproduce**
1. Go to local jupyter server
2. The side panel does not go away

**Expected behavior**
I expect, once I’m connected that the side panel for server options would slide away and only come back if I want to connect to a new server.

**Screenshots**

I cannot paste the screen shot because iOS will not let that happen, and there’s no way to access it from the form.

**Environment (please complete the following information):**
 - Device: iPad Pro 11"
 - iOS version: iOS 14.3
 - App version 1.5.11

**Comment by navoshta** [comment]
Thanks for reporting @pumplerod — does the panel remain open even when you edit a notebook? The left panel should remain visible in file browser only, and only if there is enough space for it (e.g. it will collapse on iPhone, or if you open Juno Connect in split-screen mode).

**Comment by navoshta** [comment]
Closing this issue for now, but feel free to reopen and submit a new one if the panel remains open when you edit a notebook.
