### ISSUE TITLE
Azure Notebooks option missing

### ISSUE THREAD

**Issue by harveydov** [rationalmatter/Juno-Issue-Tracker#238]
**Describe the bug**
In the main sidebar, I only see three cloud computing options, Azure notebooks is not one of them. Inside the settings, under ‘Hide Cloud Services’ Azure notebooks appears and is not ticked.

**To Reproduce**
1. Uninstall and Re-Install app (optional but tried)
2. Open the app

**Expected behavior**
Four options should be displayed as per screenshots on main website

**Screenshots**
![1E320F88-D7AF-4570-B179-4EBCDEAC286E](https://user-images.githubusercontent.com/50531169/107200590-cf3e5100-69ef-11eb-9e3f-a426fde538b6.png)
![6E05CFB8-5694-4BA5-846E-05E548B8633E](https://user-images.githubusercontent.com/50531169/107200598-d1a0ab00-69ef-11eb-9e5f-b807ab3edcfd.png)

**Environment**
 - Device: iPad Pro 12.9" 2018
 - iOS version: 14.4
 - App version 1.5.12

**Comment by navoshta** [comment]
Apologies @harveydov, I may need to update screenshots on the website — Azure Notebook has been discontinued by Microsoft, and is no longer available (neither in Juno Connect, nor on desktop), so I had to disable it in the app. I'll also clean up remaining references to Azure Notebooks in the app, thanks for reporting.

**Comment by harveydov** [comment]
Thanks for the clarification @navoshta
