### ISSUE TITLE
Can’t Rename any archive

### ISSUE THREAD

**Issue by rieszbanach** [rationalmatter/Juno-Issue-Tracker#24]
**Describe the bug**
Can’t Rename any archive 

**To Reproduce**
2. Tap on '....'

**Expected behavior**

**Screenshots**
If applicable, add screenshots or a screen recording to help explain your problem.

**Environment (please complete the following information):**
 - Device: [e.g. iPad Pro 11"]
 - iOS version: [e.g. iOS 12.2]
 - App version [e.g. 1.0.0]
iPad Pro 11”
IOS 11.2

**Comment by navoshta** [comment]
Juno should provide same file-managing functionality as iOS's Files app — but IIRC it will only let you rename the notebooks, not other types of files. You should be able to rename an archive in the Files app, though.

Please, feel free to reopen if I misunderstood.
