### ISSUE TITLE
Installed packages not found

### ISSUE THREAD

**Issue by baus8650** [rationalmatter/Juno-Issue-Tracker#243]
**Describe the bug**
After using the built in package installer to install the music21 package, I was notified that the install was successful but when trying to import the package the notebook indicates that the module was not found. 

**To Reproduce**
1. Search for music21 in the package installer
2. Click install
3. Return to notebook and run “from music21 import *”

**Expected behavior**
I expected the package to be installed correctly and being able to use the package in a Juno jupyter notebook. 

**Screenshots**

**Environment (please complete the following information):**
 - Device: [iPad Pro 11" and iPhone 12 Pro]
 - iOS version: [iOS 14.4]
 - App version [1.2.9]

**Comment by navoshta** [comment]
Hi @baus8650, what does the error message say exactly? 

Please, mind that Juno's package installer will _not_ install dependencies automatically. Perhaps `music21` is missing some dependencies?

**Comment by baus8650** [comment]
Thank you so much for your reply and the reminder about the dependencies. Looks like installing the dependencies manually solved the missing module problems but now I am getting the attached error message. I’m sure it’s some form of user error (relatively new to this kind of stuff). If you have any suggestions that would be wonderful, but if not I completely understand!

Thank you again!

**Comment by navoshta** [comment]
Hi @baus8650 — sorry I can't find the attachment, could you post the error message again please? Perhaps safer to add it via comment on GitHub issue page.

**Comment by baus8650** [comment]
So sorry about that! The error miraculously solved itself so I’m all set. Thank you so much for your time and your help! This app is wonderful!

Tim

**Comment by navoshta** [comment]
No worries — glad you sorted it out! 🙃
