### ISSUE TITLE
Cannot load notebook on Google drive, file is not selectable.

### ISSUE THREAD

**Issue by JCalaunan** [rationalmatter/Juno-Issue-Tracker#245]
**Describe the bug**
Trying to access notebook in google drive, but cannot open it.

**To Reproduce**
Steps to reproduce the behaviour:
1. Open iPad
2. Sync Google Drive
3. Open Juno
4. Scroll to Google drive folder with notebook file, on Juno 
5. Unable to select notebook as it is grey out.

**Expected behavior**
I was expecting to be able to open the notebook and run it locally.

**Screenshots**
https://imgur.com/a/hg8dGpO

**Environment (please complete the following information):**
 - Device: iPad Pro 11" 2020
 - iOS version: iOS 4.4
 - App version: Latest

**Comment by navoshta** [comment]
Hi @JCalaunan — yep, this is a known issue I'm afraid. Juno integrates with the file system via Apple’s Files app, and some cloud storage providers don’t integrate with Files in full for some reason. Usually you can still open notebook documents, but Google Drive specifically seems wildly misconfigured, and doesn't even let you open file formats not on the Google's "allowed" list. Hopefully, they will eventually resolve this on their side of things, but we are looking into workarounds, where we could potentially integrate with Google Drive bypassing Files app.
