### ISSUE TITLE
Juno cannot connect to notebook server

### ISSUE THREAD

**Issue by Minion3665** [rationalmatter/Juno-Issue-Tracker#248]
**Describe the bug**
I can’t connect to notebook server

**To Reproduce**
1. Open a notebook
2. See error

**Expected behavior**
I expected the app to connect to the notebook server, allowing me to use a jupyter notebook.

**Screenshots**
![0330E3B4-F774-4F67-B2AB-7868D14E5B12](https://user-images.githubusercontent.com/34243578/114989195-1a149300-9e8f-11eb-950e-4b064b253919.jpeg)

**Environment**
 - Device: iPad (5th generation)
 - iOS version: 14.4.2
 - App version: Juno 1.3.4 (6039)

**Comment by navoshta** [comment]
Thanks for reporting @Minion3665 — am I correct assuming you're using beta? Does this happen every time, or only with some notebooks, e.g. in some directories? Any chance there are Unicode characters in the notebook path?

**Comment by Minion3665** [comment]
> Thanks for reporting @Minion3665 — am I correct assuming you're using beta? Does this happen every time, or only with some notebooks, e.g. in some directories? Any chance there are Unicode characters in the notebook path?

Yes, it happens on every notebook as far as I know. I don't think there are any unicode characters in the path name: even when I create a notebook in 'on my iPad' or in 'iCloud drive' it doesn't seem to work.

**Comment by navoshta** [comment]
Thanks @Minion3665 I will look into this, and hopefully this will be addressed in the next beta build. Meanwhile, I suggest that you try to reinstall the app from scratch (also from TestFlight) and see if this fixes the issue.

**Comment by Minion3665** [comment]
> Thanks @Minion3665 I will look into this, and hopefully this will be addressed in the next beta build. Meanwhile, I suggest that you try to reinstall the app from scratch (also from TestFlight) and see if this fixes the issue.

Alright so I've taken a look at stuff further and realised something else that may be relevant: this is an iPad owned by my school, and they require a global HTTP proxy in order to access the internet. Could it be that Juno is going through that and therefore not being able to find its server?

**Comment by navoshta** [comment]
@Minion3665 I'm not sure, but that's a great guess — in theory local traffic shouldn't go through a proxy I suppose, but it seems like it does in this case. Actually, it seems like it's specifically the socket that can't connect, which Jupyter uses to communicate with the kernel. I will need to simulate this proxy behaviour and look deeper into this — thanks for the info, and let me know if you see anything else odd on that proxied device.

**Comment by alexstaravoitau** [comment]
Juno 2.0 should address this (2.1 is now live on App Store) — feel free to reopen if it still happens.
