### ISSUE TITLE
Qiskit 0.25

### ISSUE THREAD

**Issue by vsprasannaa** [rationalmatter/Juno-Issue-Tracker#249]
I already found one request for qiskit, but since it is a year old and the comments there did not help (which said that we install each of the modules separately, for example, qiskit-aer, but that does not work either for me! :-( ), may I request you for qiskit 0.25?

**Comment by navoshta** [comment]
Closing as a duplicate of #118 — I will update the original ticket when there are any updates (I didn't get to Qiskit yet, sorry).
