### ISSUE TITLE
cannot connect Cocalc,

### ISSUE THREAD

**Issue by ShunOtsuka** [rationalmatter/Juno-Issue-Tracker#253]
**Describe the bug**
I cannot connect Cocalc, although I can connect via Safari.

**To Reproduce**
2. Tap on '....'

**Expected behavior**

**Screenshots**
If applicable, add screenshots or a screen recording to help explain your problem.

**Environment (please complete the following information):**
 - Device: [e.g. iPad Air 3"]
 - iOS version: [e.g. iOS 14.6]
 - App version [e.g. 1.6.5]

**Comment by navoshta** [comment]
Thanks for reporting @ShunOtsuka — this has been addressed on the CoCalc's side, so it should be working again now. 🚀
