### ISSUE TITLE
Return button does nothing on iPad with Magic Keyboard on iOS Beta

### ISSUE THREAD

**Issue by timarnold** [rationalmatter/Juno-Issue-Tracker#257]
**Describe the bug**
When editing a code cell, I push the return key on my magic keyboard. Nothing happens.

**To Reproduce**
Open a code cell. Hit return

**Expected behavior**
A newline is produced

**Actual Behavior**
The cell loses focus

Note: the software keyboard seems to work fine.

**Screenshots**
If applicable, add screenshots or a screen recording to help explain your problem.

**Environment (please complete the following information):**
 - Device: iPad Pro (12.9-inch) (4th generation) , MY3J2LL/A
 - iOS version: 15.0 (19A5281j)
 - App version: 1.3.8 (6231)

**Comment by navoshta** [comment]
Thanks for reporting @timarnold — this indeed seems like an iPadOS 15 beta issue. I'm planning to look into this soon (unless Apple fixes this in the next beta).

**Comment by navoshta** [comment]
I've implemented a temporary workaround in Juno 1.3.9, which should be now available on App Store. Let me know if you spot any issues in the new build!
