### ISSUE TITLE
Can’t Rename Juno (Jupyter) Files

### ISSUE THREAD

**Issue by tojasonk** [rationalmatter/Juno-Issue-Tracker#258]
**Describe the bug**
There’s no way for me to rename a file.  There’s no option in the Juno app to do so.  And when I go into the Files app and rename it, Juno won’t re-open it after the rename.  I just get an internal server error.

**To Reproduce**
1. Create a new file; enter some text or code
2. Save it and exit to the Files app (by hitting “Notebooks”)
3. Rename it, and double-click it to launch the notebook
4. Get a 500:  internal server error

**Expected behavior**
I expected it to open the file after rename; or a way to rename it within the app.

**Screenshots**
If applicable, add screenshots or a screen recording to help explain your problem.
![4AC2CBDA-A040-4B8D-99CA-79AE2E42AD9C](https://user-images.githubusercontent.com/82727671/125139881-55fe7380-e0df-11eb-9486-547fe6ed9f44.png)
![F914D3E6-3019-4D7B-BF8A-1D3C2EDB0F62](https://user-images.githubusercontent.com/82727671/125139884-572fa080-e0df-11eb-97d2-1a2b9160f052.png)

**Environment (please complete the following information):**
 - Device: iPad Pro 11”
 - iOS version: iOS 14.6
 - App version 1.3.8

**Comment by tojasonk** [comment]
Well, I’m definitely opening and saving files to iCloud.  Not sure if it’s a location thing or not, but I could try it.  I also don’t have the option in Juno to rename the notebook; I thought I saw it once when I first opened the app, but then it seemed to disappear.  That’s what led me to rename it in the Files app itself.

I took the files that Juno wouldn’t open and opened them in Carnets plus and they opened just fine.  So, the file is fine.  I’ve also deleted and re-installed the app and that seems to fix it for a bit, but then it returns.  So, not sure what’s going on.

**Comment by alexstaravoitau** [comment]
Thanks @tojasonk — I'll look into this. The option in Juno I was referring to is in the notebook editor itself: if you tap notebook name in the top bar, there should be an option to rename it. Although file browser in Juno also allows renaming using standard iOS UI (hence this could be confusing). And please let me know if you can think of anything else that could help me reproduce this.

**Comment by tojasonk** [comment]
Yeah, not sure what it is.  When I install Juno new and the Welcome to Juno notebook opens up, the Rename option is in the toolbar.  But, once I go to create my own, it disappears.

**Comment by alexstaravoitau** [comment]
@tojasonk OK I *think* I figured it out: you won't see 'Rename' option for notebooks outside of Juno's directory (i.e. outside of app's sandbox), as you don't have enough permissions from the OS to rename notebook file at this point. However, if you later grant access to notebook directory (folder-with-a-lock icon in the top bar), you should be able to rename the notebook too, but Juno doesn't display a 'Rename' option regardless. And *this* now sounds like a bug! 😅 I'll look into this.

**Comment by alexstaravoitau** [comment]
Juno 2.0 should address this (2.1 is now live on App Store).
