### ISSUE TITLE
Juno captures keystrokes wrong

### ISSUE THREAD

**Issue by racoonfused** [rationalmatter/Juno-Issue-Tracker#259]
**Describe the bug**
When I use enter key - instead of starting a new line of code, I close the block (just as I would with § key (my esc))

**To Reproduce**
Simply try to use “enter” key during writing your code

**Expected behavior**
Just start a new line, like a good ol’ enter key should. 

**Screenshots**
If applicable, add screenshots or a screen recording to help explain your problem.

**Environment (please complete the following information):**
 - Device: iPad Gen. 6th
 - iOS version: iPadOS 15 beta 2
 - App version 1.3.8(6231)

**Comment by navoshta** [comment]
Thanks for reporting @racoonfused — this very much looks like a beta bug, but I've implemented a temporary workaround in Juno 1.3.9, which should be now available on App Store. Let me know if you spot any issues in the new build!

**Comment by racoonfused** [comment]
Now it works just fine. Thank you so much!

Regards, Krzysztof Zbińkowski

**Comment by kadaliao** [comment]
I’ve updated to version 1.3.9, the enter key works just fine but Cmd+A/V/C don’t.

**Comment by racoonfused** [comment]
I see, but I can manage. 
The lack of the enter key was much worse than cmd+a/c/v

Regards, Krzysztof Zbińkowski

**Comment by navoshta** [comment]
Yep there are still some issues with hardware keyboards in iPadOS 15 beta — as @kadaliao pointed out, Cmd+X/C/V don't work, and arrow cells navigation doesn't seem to work either. I've looked into it, but the issue appears to be somewhere deeper in WebKit, and is most likely a beta bug or a combination of bugs — I'm really hoping Apple will fix this in later betas! 

I couldn't find a reasonable workaround so far (without prematurely rewriting too many things), and if Apple eventually decides to ship new iPadOS as is, we will need to re-implement a few things in Juno closer to the iPadOS 15 release.

**Comment by alexstaravoitau** [comment]
@racoonfused @kadaliao Juno 1.3.10 is now available on TestFlight, which should fix the remaining shortcuts — please, let me know if you spot any that still won't work.
