### ISSUE TITLE
Add connection to remote jupyter

### ISSUE THREAD

**Issue by eoss-tw** [rationalmatter/Juno-Issue-Tracker#26]
The recent version of juno supports the config/connection of remote jupyter instances. The beta version only supports local notebooks. Please provide an additional config section to connect the app to a remote jupyter server. I think its a nice idea to perform local analysis only on the pad itself but for larger datasets / more dependencies a remote server would provide all advantages.
thanks

**Comment by navoshta** [comment]
Thanks @eoss-tw, the app currently in beta is not meant to replace the app currently in the store — those will be two separate apps. The app currently in the store (i.e. Jupyter client) will be rebranded as "Juno Connect" and will receive a cool new icon, whereas the app currently in beta (with embedded Jupyter) will be released as "Juno".

I have considered merging both into one app, but that would complicate a lot of things for Juno users, and would be quite a challenge usability-wise.

**Comment by eoss-tw** [comment]
Ok, that clarifies it – thanks for the info. Two apps are the better approach, too – I think.


Von: Alex Staravoitau <notifications@github.com>
Antworten an: rationalmatter/Juno-Issue-Tracker <reply@reply.github.com>
Datum: Montag, 8. Juli 2019 um 17:30
An: rationalmatter/Juno-Issue-Tracker <Juno-Issue-Tracker@noreply.github.com>
Cc: Thilo Wehrmann <twehrmann@eoss.cloud>, Mention <mention@noreply.github.com>
Betreff: Re: [rationalmatter/Juno-Issue-Tracker] Add connection to remote jupyter (#26)


Thanks @eoss-tw<https://github.com/eoss-tw>, the app currently in beta is not meant to replace the app currently in the store — those will be two separate apps. The app currently in the store (i.e. Jupyter client) will be rebranded as "Juno Connect" and will receive a cool new icon, whereas the app currently in beta (with embedded Jupyter) will be released as "Juno".

I have considered merging both into one app, but that would complicate a lot of things for Juno users, and would be quite a challenge usability-wise.
