### ISSUE TITLE
Add requests

### ISSUE THREAD

**Issue by Denko** [rationalmatter/Juno-Issue-Tracker#260]
**What is the name of the package?**
A name or link to the Python package you think should be pre-installed in Juno. Mind that you can install pure Python packages from PyPI in Juno — those that can be successfully installed won't be embedded in the app.

**Comment by Denko** [comment]
Can it be that you don’t support requests? This would make my iPad useless!

**Comment by navoshta** [comment]
Please see #237 — you can install `requests` (and any other pure Python package) using Juno's package installer: tap notebook name in the editor's top bar -> _Install Python Package_.
