### ISSUE TITLE
Can’t install Beautiful Soup

### ISSUE THREAD

**Issue by Axcyn** [rationalmatter/Juno-Issue-Tracker#261]
Hello,

I also commented this issue here : [Errors installing BeautifulSoup](https://github.com/rationalmatter/Juno-Issue-Tracker/issues/136) in case the thread need to be merged.

I’m not a regular user of Juno nor an advanced user in Python so maybe I did something wrong. Below is what I did :

**Describe the bug**
Installation with built-in manager or manual installation failed

**To Reproduce**
When I tried to install the package using the built-in installation manager I got the following error : `Failed to install bs4 installation from source failed`.

So I downloaded the package directly from the website : `beautifulsoup4-4.9.3-py3-none-any.whl` and put it directly into `site-packages` and I can’t use it.

```---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-1-d99746be2408> in <module>
----> 1 from bs4 import BeautifulSoup

ModuleNotFoundError: No module named 'bs4'
```

**Expected behavior**
working package.

**Environment :**
 - Device: iPad Pro 12.9"
 - iOS version: iOS 14.6
 - App version: 1.3.9

**Comment by navoshta** [comment]
Hi @Axcyn — please make sure you install it as `beautifulsoup4` (i.e. from here: https://pypi.org/project/beautifulsoup4/#description) — _not_ as `bs4` or `bs`. 

Placing files into _site-packages_ should also work, but you do need to unarchive them first, as `.whl` is a zip compressed archive.

**Comment by Axcyn** [comment]
Hello @navoshta ! It worked I downloaded a wrong package `bs4`

Thank you !

ps: the manual install worked well too
