### ISSUE TITLE
Can't connect to CoCalc

### ISSUE THREAD

**Issue by SeanMaths4EAL** [rationalmatter/Juno-Issue-Tracker#263]
**Describe the bug**
Juno Connect won't connect to my CoCalc account. 
I just get 'Failed to retrieve account information'

**To Reproduce**
I've tried logging out, deleting and reinstalling the app, "Clear all sessions"

**Expected behavior**

**Screenshots**
If applicable, add screenshots or a screen recording to help explain your problem.

**Environment (please complete the following information):**
iPad Pro 12" 2018 iOS 14.7
Same on iPhone

**Comment by SeanMaths4EAL** [comment]
> **Describe the bug**
> 
> Juno Connect won't connect to my CoCalc account. 
> 
> I just get 'Failed to retrieve account information'
> 
> 
> 
> **To Reproduce**
> 
> I've tried logging out, deleting and reinstalling the app, "Clear all sessions"
> 
> 
> 
> **Expected behavior**
> 
> A clear and concise description of what you expected to happen.
> 
> 
> 
> **Screenshots**
> 
> If applicable, add screenshots or a screen recording to help explain your problem.
> 
> 
> 
> **Environment (please complete the following information):**
> 
> iPad Pro 12" 2018 iOS 14.7
> 
> Same on iPhone 
> 
> 

It's finally managed to open it. I wonder if its an issue with the large number of projects (given that I'm using it for teaching, so there's a lot of student projects).

**Comment by navoshta** [comment]
Hi @SeanMaths4EAL — typically, this can happen when your CoCalc session expires, but logging out and it again should resolve this. Sounds like this didn't help at all in your case, which is a bit worrying! 

Either way, glad it's working now — perhaps this was just a temporary glitch on CoCalc. Feel free to reopen this ticket if the issue comes back.
