### ISSUE TITLE
Add fmp_python

### ISSUE THREAD

**Issue by AquibaB** [rationalmatter/Juno-Issue-Tracker#265]
Thanks!

https://pypi.org/project/fmp-python/#description

**Comment by alexstaravoitau** [comment]
Hi @AquibaB — this looks like a pure Python package, so you should be able to install it using Juno's package installer (keep in mind you need to install dependencies manually though). Feel free to reopen this ticket if it doesn't work (I've tried briefly and the package seemed to import OK).
