### ISSUE TITLE
juno file server error

### ISSUE THREAD

**Issue by 61675** [rationalmatter/Juno-Issue-Tracker#267]
on ipad juno.  i created a new notebook.
then tried to do a change directory to the
numbers directory.

got 

500 server error

now get this whenever i start juno again and open
existing notebooks and immediately get this error 

**To Reproduce**
Steps to reproduce the behavior

open juno
open new notebook
enter some python
change directory to ipad numbers directory 
…..

**Expected behavior**

list of numbers file s

**Screenshots**
If applicable, add screenshots or a screen recording to help explain your problem.

**Environment (please complete the following information):**
 - Device: [e.g. iPad Pro 11"]
 - iOS version: [e.g. iOS 12.2]
 - App version [e.g. 1.0.0]

ipad air 4th generation
ios 14.6
juno 1.3.8

**Comment by alexstaravoitau** [comment]
Thank you for reporting @61675 — I _think_ this should be fixed in the next release. I don't have any ETA when it will become available, but you can send me an email to help@juno.sh, and I'll add you to our TestFlight (it will appear there first).

**Comment by alexstaravoitau** [comment]
@61675 Juno 1.3.10 is now available on TestFlight, which should *hopefully* fix this. Please let me know if it still happens in 1.3.10 — reopen the issue and I will investigate further.
