### ISSUE TITLE
!Failed to display notebook

### ISSUE THREAD

**Issue by vinaykudari** [rationalmatter/Juno-Issue-Tracker#268]
**Describe the bug**
When I try to open notebook which is hosted in the cloud (Jupyter Lab) I get 'Failed to display notebook' error. The same notebook can be accessed via Safari on the same iPad

**To Reproduce**
1. Go to Home
2. Tap on <Jupyter Server Name> (HTTPS) (Tried via SSH Port forwarding too)
3. Select notebook
4. Notebook loads half
5. See error 'Failed to display notebook'

**Expected behavior**
I should be able to access the notebook

**Screenshots**

### Loading Screenshot
![IMG_0294](https://user-images.githubusercontent.com/34424769/127751988-df9272c7-b08e-43dd-a738-92cf66e5c46b.PNG)

### Failed Screenshot
![IMG_0293](https://user-images.githubusercontent.com/34424769/127751954-ed4ccc46-6350-4fcd-aa29-4ff8ef114c1f.PNG)

**Environment:**
 - Device: iPad Pro 2020 11'
 - iOS version: iOS 14.7.1
 - App version 1.6.5

**Comment by alexstaravoitau** [comment]
Hi @vinaykudari — looks worrying, but I couldn't reproduce this I'm afraid. Could you please check what version of Jupyter is running on your server, and also if there are any error messages in the Jupyter console (i.e. in the terminal where Jupyter is running)?

**Comment by vinaykudari** [comment]
@navoshta thanks for your suggestion its an [issue](https://github.com/jupyter/nbconvert/issues/1430#issuecomment-872039410 ) with nbconvert 6.1.0, downgrading to 5.6.1 fixes the issue.

**Comment by akuendig** [comment]
I am having the same issue.

Juno Connect 1.6.13
Notebook server 7.0.3
Python 3.11
nbconvert 7.8.0

I was not able to downgrade nbconvert as above.
I am connecting to the notebook server over ipv6 (also tried ipv4) on http (not https).

Any idea how to fix this issue?

**Comment by alexstaravoitau** [comment]
@akuendig This may be the Jupyter Notebook rather than nbconvert issue, see here: #365. You should be able to get it to work by installing `nbclassic`:

1. Install "classic" Notebook web app with `pip install nbclassic`.
2. Update the server's URL in Juno Connect to `{SERVER_ADDRESS}/nbclassic/tree`.

**Comment by akuendig** [comment]
Hey @alexstaravoitau 
Thank you for your quick reply. Changing the url fixed this issue. I am now hitting a separate error:

403 POST /api/sessions (<redacted>): '_xsrf' argument missing from POST

Should I file a separate issue?

**Comment by alexstaravoitau** [comment]
@akuendig Yes, please file a separate issue. 

I can't think off the top of my head what could go wrong here, so if you could please include some additional info that would help a lot: i.e. where do you see the 403 error, what's in the Jupyter server's console (or what else is there if this is where 403 is), the versions of Jupyter Notebook / nbclassic and jupyterlab packages... I would also try clearing all sessions data in Juno Connect (in app settings) and see if that makes any difference.

**Comment by Saton-anger** [comment]
Hey @alexstaravoitau 
Thanks for your help, but I'm having some confusion in setting it up as you described, in junno connect I'm connecting to my server via port forwarding, in connection setting section, i set the host as the server's IP address, as shown in the picture, where should I add /nbclassic/tree, just after the IP address? 
![5161723796385_ pic](https://github.com/user-attachments/assets/8be63598-3aee-46f6-bc50-346c673f84f7)

**Comment by alexstaravoitau** [comment]
@Saton-anger Yes, after the IP address should be fine I believe. If this doesn't work, try checking the URL in the top bar when you connect to the server.
