### ISSUE TITLE
reconnect looping 

### ISSUE THREAD

**Issue by odie2630463** [rationalmatter/Juno-Issue-Tracker#271]
**Describe the bug**
Restart kernel cause “connecting, connected ” and “kernel ready” looping forever

**Environment (please complete the following information):**
 - Device:  iPad Pro 12.9
 - iOS version: iOS 15 beta 5
 - turn off icloud privacy 
 - use http and ssh connection have same issue

**Comment by alexstaravoitau** [comment]
Thank you for reporting @odie2630463 — sounds like it's likely a network connectivity issue. Does this happen with every server / cloud service, or only with a particular one? If you don't use any cloud service, you can try the demo notebooks (i.e. *Try Jupyter* tab): they are powered by Binder under the hood. Also, if you could try connecting to the same server on another network, that would help too (perhaps there is some odd proxying situation, or something like that).

**Comment by alexstaravoitau** [comment]
This is likely fixed as a part of https://github.com/rationalmatter/Juno-Issue-Tracker/issues/280 — closing the issue.
