### ISSUE TITLE
BeautifulSoup

### ISSUE THREAD

**Issue by ndhumal360** [rationalmatter/Juno-Issue-Tracker#279]
The package is called BeautifulSoup imported as bs4
https://pypi.org/project/beautifulsoup4/
The link for the package.
This is a HTML or XML parser.

**Comment by ndhumal360** [comment]
Please add this package to Juno

**Comment by alexstaravoitau** [comment]
Hi @ndhumal360 — BeautifulSoup is a pure Python package, so you should be able to install it using Juno's package installer (whichever version you need). Just make sure you search PyPI for the correct package name `beautifulsoup4`.
