### ISSUE TITLE
Endless Kernel Reconnecting

### ISSUE THREAD

**Issue by ajennings6767** [rationalmatter/Juno-Issue-Tracker#280]
**Describe the bug**
When using Juno Connect to connect to a Jupyter Notebook on my home PC, if I navigate away from Juno Connect on my iPad, say to use a browser to look up some documentation, when I return to Juno Connect my kernel indicator flashes orange and green and will not re-establish a stable connection.

I have tried this running Jupyter via Powershell and as an independent Docker container.

If I exit the notebook and open it again, the issue is resolved. Clearly, this isn’t a long term solution as I would have to rerun my notebook every time I check an email or look something up.

My precise location history is on as well.

**To Reproduce**
1. Set up a connection to Jupyter Server on Windows 10 PC via SSH port forwarding
2. Connect to the Server
3. Open a notebook
4. Navigate away from Juno Connect (go to iPad Home Screen and open Safari)
5. Return to Juno Connect
6. Observe kernel connection (can be seeing from the stdout of Jupyter or directly in Juno)

**Expected behavior**
Expected to reconnect to kernel/server without issue.

**Screenshots**
Jupyter side of the equation:
![image](https://user-images.githubusercontent.com/30580411/136016915-247ba0ac-7f44-4788-8d81-7475715deb77.jpg)

**Environment (please complete the following information):**
 - Device: iPad Pro 12.9” 2021
 - iPadOS version: 15.01
 - App version 1.6

**Comment by alexstaravoitau** [comment]
Thanks for the detailed description @ajennings6767! So when Juno Connect returns from background (e.g. if you are navigating away from it and then navigate back), and the app has not been suspended by the OS, it will attempt to reconnect to the Jupyter server, same as what Jupyter would try to do in a browser. 

Judging by the logs from your screenshot, the socket connection, which Jupyter establishes with the kernel on your server, gets closed for some reason. I don't think this should happen normally, but I'm not 100% sure it's Juno Connect either — do you have any particular non-default connection settings in your Jupyter Notebook installation? Perhaps something related to connection heartbeat, or something like that?

I would try connecting in a browser (say on iPad) and see if behaviour is the same there. If it is, then I would look into the Jupyter server configuration first. Also, could you check the version of the Jupyter Notebook and PyZMQ installed on your server?

**Comment by yyao22** [comment]
I have the same issue with version 1.6.9(6557).

**Comment by alexstaravoitau** [comment]
Hi @yyao22 — as recommended above, could you please check if behaviour is the same when you connect from a browser? Also, could you try upgrading Jupyter and PyZMQ? Perhaps you have something useful in the Jupyter logs?

**Comment by yyao22** [comment]
> Hi @yyao22 — as recommended above, could you please check if behaviour is the same when you connect from a browser? Also, could you try upgrading Jupyter and PyZMQ? Perhaps you have something useful in the Jupyter logs?

The behavior is normal when I connect from a browser. I tried upgrading Jupyter and PyZMQ and the issue remains. Here's what's in the Jupyter logs
![Screenshot from 2021-12-02 19-28-14](https://user-images.githubusercontent.com/87083619/144524195-e428a618-453f-470f-8a23-54e40c0af447.png)
:

**Comment by alexstaravoitau** [comment]
Thank you for sharing @yyao22 — looks odd and I can't tell off the top of my head what could be wrong, if it's in the app or on the networking side. I'll look into this and see if it's something that can be worked around in Juno Connect.

**Comment by dugamarian** [comment]
Same thing here. I end up on using the browser.

**Comment by alexstaravoitau** [comment]
@ajennings6767 @yyao22 @dugamarian Thanks everyone for helping me investigate this — Juno Connect 1.6.10 is now out on the App Store with a fix. Please, feel free to reopen this issue if it still doesn't work for you, or if you spot similar behaviour in non-SSH connections (looks like only those were affected).
