### ISSUE TITLE
Unable to change directory

### ISSUE THREAD

**Issue by mhbl3** [rationalmatter/Juno-Issue-Tracker#281]
**Describe the bug**
Nothing happens when clicking on the folder icon when inside a notebook. 

**To Reproduce**
1. install ios 15.1
2. Tap on any notebook
3. Click on the upper right folder icon to change the directory

**Expected behavior**.
Being able to select a directory 

**Screenshots**
If applicable, add screenshots or a screen recording to help explain your problem.

**Environment (please complete the following information):**
 - Device: iphone Pro 12
 - iOS version: iOS 15.1
 - App version 1.3.14.0

**Comment by alexstaravoitau** [comment]
Thanks for reporting @mhbl3, could you please check this still happens on beta 4? This seems to be working for me, at least on the latest 15.1 beta.

Does this happen on every notebook outside of Juno's on device storage? Or only in other apps' folder, or iCloud or other particular location?

**Comment by alexstaravoitau** [comment]
This should be addressed in one of Juno 2.0/2.1 releases (2.1 is now live on App Store).
