### ISSUE TITLE
Cannot run actions from “Jupyter Commands” menu when on-screen keyboard is hidden

### ISSUE THREAD

**Issue by afedotov** [rationalmatter/Juno-Issue-Tracker#283]
**Describe the bug**

When opening “Jupyter Commands” combobox, iPadOS on-screen keyboard appears. One can press bottom right “hide keyboard” button, and scroll dropdown list of actions. Further selecting desired action does not execute it, instead hidden on-screen keyboard popups back, putting focus to combobox input field, and scrolling dropdown list back to top. This making tricky to access “Jupyter Commands” actions in this manner, especially to those at the bottom of the list.

**To Reproduce**
1. Open any notebook
2. Tap on notebook name to open notebook menu
3. Select “Jupyter Commands”, on-screen keyboard appears
4. Hide on-screen keyboard
5. Scroll down list of actions and select any to execute
6. Observe described behaviour

**Expected behavior**
Selecting any action when on-screen keyboard is hidden should immediately execute that action.

**Environment:**
 - Device: iPad Pro 11" 2nd gen (2020), without hw keyboard, dark mode
 - OS version: iPadOS 15.0.2
 - App version: 1.3.14 (6557)

**Comment by alexstaravoitau** [comment]
Thanks for reporting — Jupyter Commands menu is carried over from the standard Jupyter interface, and looks a bit out of place in Juno to be honest. I was thinking of removing it as a part of upcoming editor UI redesign, but I'll see if I could get it to work and keep around for a bit longer.

**Comment by afedotov** [comment]
Yep, I agree. This menu looks out of place and unhandy now, especially for touchscreen device without hardware keyboard. And the best way is to think over and redesign it.

**Comment by alexstaravoitau** [comment]
Closing the issue as the _Jupyter Commands_ menu is no longer available in Juno.
