### ISSUE TITLE
Add useful combo actions to quick access menu

### ISSUE THREAD

**Issue by afedotov** [rationalmatter/Juno-Issue-Tracker#284]
**Is your feature request related to a problem?**

Yes. I think about it while messing around with issues #282 and #283

**Describe the solution you'd like**

I think it will be handy for users without hardware keyboard, who cannot use keyboard shortcuts.

1. Add useful combo actions within some kind of quick access menu, notebook menu e.g. At least something like ⏩ button in Jupyter Lab which restarts kernel, clears all output and reruns all cells.
2. Maybe in general make this menu customisable, allow add custom quick actions with bindings to Jupyter Commands. Just like keyboard shortcuts, but for users without hardware keyboard.

**Comment by alexstaravoitau** [comment]
Thanks for reporting — I'll see what I can do, specifically the ⏩ button does seem to be used a lot in desktop Jupyter. 

Meanwhile, you can change the default 'Run' button action by press-and-holding it (there is no 'Restart and Run All' option there though I"m afraid).

**Comment by alexstaravoitau** [comment]
Juno 2.1 is now live on App Store, with a whole set of bug fixes and improvements — there is now a *Restart and Run All* option, which you can either use as the floating button action, or add to the iPadOS 16's customisable toolbar.
