### ISSUE TITLE
Add some buttons to iPad on-screen keyboard extension for easer code editing

### ISSUE THREAD

**Issue by afedotov** [rationalmatter/Juno-Issue-Tracker#285]
**Is your feature request related to a problem?**

No. This is just for easer code editing without hardware keyboard on iPad.

**Describe the solution you'd like**

It would be nice to add to iPadOS on-screen keyboard extension some buttons for more convenient code editing. At least these:

- Delete Line button
- Delete Word button
- Comment Line button

IMHO they are more useful than existing “add cell”, “split cell” and “move cell” which are available anyway from “lightning” menu.

BTW, take a look at these keyboard buttons layout, they overlaps (iPad 11” 2nd gen, iPadOS 15.0.2):

![D1B63104-14ED-4D10-8FE3-74385F35E4C9](https://user-images.githubusercontent.com/4266693/137647791-299ecb8c-348c-44b2-9a0a-7b9ef163a82a.jpeg)

**Comment by alexstaravoitau** [comment]
Thanks for reporting, I will look into this. At the very least the icons shouldn't overlap of course — I'll think about those actions too, perhaps I could add some new ones.

**Comment by alexstaravoitau** [comment]
Juno 2.1 is now live on App Store, with a whole set of on-screen keyboard bug fixes and improvements (among other things).
