### ISSUE TITLE
Error when importing 'nullcontext' from ‘contextlib'

### ISSUE THREAD

**Issue by wantMoreSleep** [rationalmatter/Juno-Issue-Tracker#286]
Missing name when I tried this
`from contextlib import nullcontext`. This is part of the bigger problem when I tried to `import dask`.

**Comment by alexstaravoitau** [comment]
Hi @wantMoreSleep, is this related to Juno or Juno Connect? If it's about Juno, how did you install `contextlib` — was it via Juno's package installer, or did you put the module files into the *site-packages* folder?

**Comment by wantMoreSleep** [comment]
`contextlib` is a built-in library of Python, so that shouldn’t be installed with external effort. And yes it’s Juno, not remote environment. I worked around this issue by using older version of Dask library.

**Comment by alexstaravoitau** [comment]
Ah I see — looks like `nullcontext` was not available in Python 3.6, which Juno uses. We are currently working on upgrading Juno's environment to Python 3.9 or 3.10, so hopefully this will resolve the issue. I'll close this ticket for now.
