### ISSUE TITLE
Program crash

### ISSUE THREAD

**Issue by aeiwz** [rationalmatter/Juno-Issue-Tracker#287]
I can’t run my project because program crash. The program shuts down when the code is executed.

**Comment by alexstaravoitau** [comment]
Thanks for reporting @aeiwzxIII — I'm assuming this is about Juno, not Juno Connect? Do you have a code example reproducing the crash? This would help immensely.

**Comment by alexstaravoitau** [comment]
Juno 2.1 is now live on App Store, fixing a whole set of crashes — hopefully, including this one. Feel free to reopen the issue if it still happens.
