### ISSUE TITLE
Installing package from git repo

### ISSUE THREAD

**Issue by thipokKub** [rationalmatter/Juno-Issue-Tracker#289]
**Is your feature request related to a problem? Please describe.**
From [issue #11 ](https://github.com/rationalmatter/Juno-Issue-Tracker/issues/11), Juno can install pure python package from PyPi. However it could be a bit more versatile if it can install package from git repo because sometime the package bundle from PyPi isn't updated

**Describe the solution you'd like**
Add url ui box for something to include installing python package via git repository

**Comment by alexstaravoitau** [comment]
Thanks for reporting @thipokKub — interesting, I haven't thought of this use case. I'll see how this can be added; meanwhile, you should be able to do this manually by downloading the repo as zip and unpacking into the *site-packages* directory in Juno's on-device storage. I understand it would be easier if Juno could do this automatically in package installer though.

**Comment by thipokKub** [comment]
Thanks, I am able to install the package with the method you provided. However, it is a bit tricky to run `setup.py` file from the repo, but eventually I've gotten it done (using `%cd` magic command, then run python script)
