### ISSUE TITLE
Add biopython

### ISSUE THREAD

**Issue by LucasCRK** [rationalmatter/Juno-Issue-Tracker#291]
Hi,
Could you please add biopython, It failed to install from source when I tried to add it

https://github.com/biopython/biopython

https://biopython.org/https://biopython.org/

thank you.

**Comment by alexstaravoitau** [comment]
Thanks for reporting @LucasCRK — I'll close this as a duplicate of #28 (apologies it take a while to go through the backlog of package requests).
