### ISSUE TITLE
Juno crashes when switching focus after opening blank notebook in iPadOS 15.4 beta

### ISSUE THREAD

**Issue by lukewiebe** [rationalmatter/Juno-Issue-Tracker#297]
Here’s what happens:

1. Open Juno in split view with any other app
2. Open a brand new notebook
3. Tap any text input on the other app
4. Juno crashes

I’m testing on an iPad Pro 12.9 2018 with keyboard attached, running iPadOS 15.4 public beta.

**Comment by alexstaravoitau** [comment]
Thanks for reporting @lukewiebe — I'm looking into this.

**Comment by alexstaravoitau** [comment]
This should now be fixed in the latest releases (Juno 1.3.15 and Juno Connect 1.6.10).

**Comment by lukewiebe** [comment]
Wow, thanks for the quick turnaround!
