### ISSUE TITLE
Add FlowCal

### ISSUE THREAD

**Issue by HX422** [rationalmatter/Juno-Issue-Tracker#298]
FlowCal: https://github.com/taborlab/FlowCal
This package is used for analyzing flow cytometry data. It would be awesome if this would be added to Juno, greatly increasing my research productivity!

**Comment by alexstaravoitau** [comment]
Looks like FlowCal is a pure Python package, and should work. The App Store version of Juno shows an error when trying to install it, so you may need the latest Juno *beta*, where I've fixed a couple of things around packages installation — please ping me at beta@juno.sh, and I'll add you to our TestFlight.

That said, when I try to import FlowCal it complains about a missing tkinter module, which could be a bigger issue, see here: https://github.com/rationalmatter/Juno-Issue-Tracker/issues/226#issuecomment-752989714. But perhaps you could find a way to use flowcal without tkinter?

**Comment by HX422** [comment]
Hi,
 Thanks so much for such a quick follow up! I tried the beta, and I am able
to install FlowCal, however, I am not able to import it due to tkinter. I
understand tkinter comes packaged with python 3, and there is no pip
package of it to install it afterwards, so I guess at the moment this isn’t
working for me.

Still, thanks so much for your help, I still love the app!

-Harold

**Comment by alexstaravoitau** [comment]
Yes, sadly Tkinter is not available for iOS, and porting it won't be easy either: it's a desktop UI framework, which relies on desktop interactions and interface components. Those will be hard to translate to iOS and touch screens. I'll close this issue for now, as FlowCal is a pure Python package — you can follow the progress of UI  frameworks here, I suppose: https://github.com/rationalmatter/Juno-Issue-Tracker/issues/226 (although I'm not sure if/when this could be resolved).
