### ISSUE TITLE
Add scikit-learn

### ISSUE THREAD

**Issue by desilinguist** [rationalmatter/Juno-Issue-Tracker#3]
**What is the name of the package?**

http://scikit-learn.org/stable/index.html

**Comment by danbricedatascience** [comment]
Hi, What is the status for Scikit-Learn ? will it be part of Juno 1.2 ?

**Comment by navoshta** [comment]
@danbricedatascience Not in 1.2 I'm afraid, but it will get released in one of the follow-up releases. Scikit-learn is going to be our next priority when SciPy is out the door.

**Comment by navoshta** [comment]
Scikit-learn is now available in Juno 1.2.7 available on TestFlight — please send an e-mail to beta@juno.sh if you're not on our beta channel, but would like to help test it. 🙂

**Comment by navoshta** [comment]
Juno 1.2.8 has been released to App Store — it now comes with Scikit-learn pre-installed. 🎉
