### ISSUE TITLE
Juno crashes and close when reopenning after long time in background

### ISSUE THREAD

**Issue by jaswdr** [rationalmatter/Juno-Issue-Tracker#306]
**Describe the bug**
Every time I reopen Juno after it is in background for a couple of hours it crashes and closes.

**To Reproduce**
1. Open Juno
1. Open any notebook
1. Lock your device
1. Wait a couple of hours
1. Come back and unlock your device
1. Reopen Juno

**Expected behavior**
I'm expecting that Juno doesn't crashes and just work.

**Screenshots**
Not applicable since the program crashes.

**Environment (please complete the following information):**
 - Device: iPad Pro 11" 3rd Generation
 - iOS version: 15.3.1
 - App version 1.3.15 (6561)

**Comment by alexstaravoitau** [comment]
Thanks for reporting @jaswdr — this is something we've been looking into, and it should get addressed with the Python runtime upgrade (we're currently upgrading it to 3.10). I don't have an ETA I'm afraid, but let me know if you would like to join our beta channel meanwhile (ping me at beta@juno.sh).

**Comment by jaswdr** [comment]
Most recent version of Juno (TestFlight) seems to have fixed this issue. For multiple times I was able to keep a notebook open, minimize, and after hours reopen it without Juno crashing.
