### ISSUE TITLE
Update built-in version of Scikit learn

### ISSUE THREAD

**Issue by jaswdr** [rationalmatter/Juno-Issue-Tracker#307]
**Is your feature request related to a problem? Please describe.**
The built-in version of Scikit learn package is already old and some cool features from the new versions of this package are not available. Like for example the toy dataframes that could be used in a lot of situations.

**Describe the solution you'd like**
Update the built-in version of the scikit-learn package to the most recent version.

**Comment by alexstaravoitau** [comment]
Yep agreed, we're going to look into upgrading the packages in the embedded environment shortly after we migrate to Python 3.10.

**Comment by alexstaravoitau** [comment]
Juno 2.1 with upgraded Scikit-learn is now available on TestFlight (and will soon make its way to the App Store).
