### ISSUE TITLE
Images in Markdown blocks are not shown

### ISSUE THREAD

**Issue by gilbertfrancois** [rationalmatter/Juno-Issue-Tracker#308]
**Describe the bug**
When I use one of the ways to show an image in markdown: 
- `[title](url_to_image)`
- `<img src="url_to_image">`
only an empty placeholder is shown.
- Changing relative path to full path does not help.
- Same behaviour for png and jpg.
- Juno Connect has access to the files. In the file explorer, the file can be found.

**To Reproduce**
1. Create a notebook
2. Set the cell to *markdown* and add an image with one of the methods described in the previous section. Make sure the image exists at the given path.
3. Activate the cell and see the result.

**Screenshots**

_Figure 1: Juno Connect with empty image._

![930F1450-762B-4EEC-92F1-BE8B76EBF5B3](https://user-images.githubusercontent.com/15607023/156128361-d0dd03b7-4bf9-4cd1-aeab-aa615c771f02.png)

---

_Figure 2: Safari with SSH Tunnel showing expected behaviour._

![994E2E3E-55DD-4ACE-8A43-99B23F5A19C2](https://user-images.githubusercontent.com/15607023/156128375-8630a2a5-34eb-4946-8009-0d4cf02a0272.jpeg)

---

**Environment (please complete the following information):**
 - Device: iPad Pro 12.9" (4th gen)
 - iOS version: iPadOS 15.2.1
 - App version 1.6.10

**Comment by alexstaravoitau** [comment]
Thanks for reporting @gilbertfrancois, I will look into this. Although it looks like this is not a Juno Connect issue, but a Jupyter one — images in markdown cells don't work on desktop either over SSH. The reason it works for you is likely because you opened JupyterLab, not Jupyter Notebook (you can try loading `localhost:8889/tree` instead of `localhost:8889` to verify this).

**Comment by gilbertfrancois** [comment]
Hi @navoshta, thank you for the insights. I now understand what is causing this and have the solution. It was indeed a problem by Jupyter Notebook / Lab, not a problem of Juno Connect. I found the proper way to include the right file path and write it down below for future reference, in case someone else has the same issue.

The way to solve it is to think of the path as URL from the root of the Jupyter server, not as path of the filesystem of the computer. As an example, let the notbook be at: `<project_path>/mynotebook.ipynb` and the image at `<project_path>/myimage.png`. One can check if the image is accessible in the browser by:

```
http://localhost:8888/files/myimage.png
```

Note the `/files` argument in the url. If that is the case, one can include an image in the Jupyter Notebook as:

```
![label](/files/myimage.png)
```

or 

```
<img src="/files/myimage.png">
```

This solution works for **Jupyter Lab**, **Jupyter Notebook** and **Juno Connect**. 

Thanks for the great support. I will close the github issue as resolved.

---
_Figure 1: Jupyter Connect showing the image in Markdown._

![D00FC941-5401-420B-A1FA-B6232F1829AF](https://user-images.githubusercontent.com/15607023/156764065-8dbe472a-8060-4eaa-adbb-b5348f4a4278.png)
---

**Comment by alexstaravoitau** [comment]
Interesting — thank you for sharing @gilbertfrancois 👍
