### ISSUE TITLE
Add "Caps Lock" as override for the Esc key

### ISSUE THREAD

**Issue by jaswdr** [rationalmatter/Juno-Issue-Tracker#309]
**Is your feature request related to a problem? Please describe.**
Is not related to a problem, just an enhancement.

**Describe the solution you'd like**
When using the Apple magic keyboard and writing a notebook is rare to write some large text in uppercase, that's why I commonly use the Caps Lock as the equivalent for the Esc key. I believe that adding it as an option to override in the settings would be realy useful.

**Comment by alexstaravoitau** [comment]
Hey @jaswdr — the in-app override options are somewhat obsolete these days to be honest, as you can now configure the keys in the iPadOS Settings app (including mapping Caps Lock to Esc). Go to _Settings_ -> _General_ -> _Keyboards_ -> _Hardware Keyboard_ -> _Modifier Keys_ -> _Caps Lock Key_ and select *Escape*.
