### ISSUE TITLE
Add SQLAlchemy

### ISSUE THREAD

**Issue by eddo888** [rationalmatter/Juno-Issue-Tracker#311]
please allow the python native bits to install
skip the c native bits
will still work with sqlite db
that is  95% of the user base right there
works in PyTo and Pythonista for ipad and iphone

**Comment by eddo888** [comment]
sorry, not a bug, is a feature request

**Comment by eddo888** [comment]
#enhancement

**Comment by alexstaravoitau** [comment]
Thanks for reporting @eddo888, I will look into this. If it's going to work without native extensions, this should be easy to add.

**Comment by alexstaravoitau** [comment]
You should now be able to install SQLAlchemy using Juno's package manager — it will install the pure Python wheel distribution without native extensions.
