### ISSUE TITLE
Cannot install sympy on lastes iteration of juno

### ISSUE THREAD

**Issue by ProfCelia** [rationalmatter/Juno-Issue-Tracker#313]
**Describe the bug**
![Docs  Juno](https://user-images.githubusercontent.com/36567756/162473181-65aaef1d-895b-4d3f-8277-e76df51f6c19.png)

**To Reproduce**
1. click on heading to get to install packages link
2. fill in sympy
3. after installation: Import sympy as sym
4. See Attached.

**Expected behavior**
expect to have sympy package loaded and usable

**Screenshots**
See screen shot above

**Environment (please complete the following information):**
 - Device: [ iPad Pro 12.9”)
 - iOS version: [iOS 15.4.1
 - App version [1.4.2]

**Comment by alexstaravoitau** [comment]
Thanks for reporting @ProfCelia, looks like the latest SymPy release requires Python 3.7 or newer, whereas Juno currently ships with Python 3.6. 

You can still install and use SymPy in Juno, but you may need to select a slightly older release — probably any which is not the most recent one. We are working on upgrading our Python environment though, so hopefully will release an update with a new Python soon-ish.

**Comment by alexstaravoitau** [comment]
Juno 2.1 with Python 3.10 is now available on TestFlight (and will soon make its way to the App Store).
