### ISSUE TITLE
add pymc3

### ISSUE THREAD

**Issue by lmatute** [rationalmatter/Juno-Issue-Tracker#314]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Comment by alexstaravoitau** [comment]
Thanks for reporting @lmatute — looks like pymc3 itself is a pure Python package and should not be a problem. It must be missing some of its dependencies though; there is already a package request for Theano here: #294, and there could be more. I'll close this issue as a duplicate for now.
