### ISSUE TITLE
numpy.random.Generator

### ISSUE THREAD

**Issue by waikho** [rationalmatter/Juno-Issue-Tracker#316]
numpy.random.Generator

**Comment by alexstaravoitau** [comment]
Thanks for reporting @waikho — `numpy.random.Generator` will become available when we upgrade NumPy to a recent release. I suppose you could use the legacy `numpy.random.RandomState` for now, although not sure how useful that would be.

**Comment by alexstaravoitau** [comment]
Juno 2.1 with updated NumPy is now live on App Store.
