### ISSUE TITLE
from __future__ import annotations: not working

### ISSUE THREAD

**Issue by connorferster** [rationalmatter/Juno-Issue-Tracker#317]
It seems that packages which opt to use the new stringified type annotations cannot run in juno.

Love the juno app. Excellent UI design!

**Comment by alexstaravoitau** [comment]
Thanks @connorferster — looks like `annotations` is only being available in `__future__` from Python 3.7 [(PEP563)](https://www.python.org/dev/peps/pep-0563/#enabling-the-future-behavior-in-python-3-7), and Juno currently comes with Python 3.6. We are working on the upgrade, and Juno will switch to Python 3.10 some time this year, arriving as a free app update.
