### ISSUE TITLE
Hide server list sidebar

### ISSUE THREAD

**Issue by fredmonroe** [rationalmatter/Juno-Issue-Tracker#325]
Apologies if there is already a way to do this, i couldn’t find one

I’d like to be able to toggle the server list sidebar in Juno connect open/closed to make more room for my notebook on screen. Is this possible?

A keyboard shortcut would be great

**Comment by fredmonroe** [comment]
I’m an idiot and just realized it closed when i open a notebook

**Comment by alexstaravoitau** [comment]
No worries @313v — btw I do plan to make the servers sidebar hide-able, too (i.e. when you're not editing a notebook).
