### ISSUE TITLE
Doesn’t recognize .ipynb in iCloud

### ISSUE THREAD

**Issue by allengwinn** [rationalmatter/Juno-Issue-Tracker#328]
**Describe the bug**
When you try to edit an ipynb in iCloud, it is greyed out. It looks like Juno doesn’t recognize it anymore. This is in the latest iOS version for iPad.

The file type (Get Info) shows it to be “data”. So it may not recognize that file extension.

You can still get the file to open if you tap a few times. It runs OK in Juno, but the app thinks it can’t open it.

**To Reproduce**
1. Navigate to iCloud Drive2. 
2. Navigate to the directory where your ipynb file is located3. 
3. You’ll notice it is greyed out!

**Expected behavior**.

**Screenshots**

**Environment (please complete the following information):**
 - Device: iPad Air 2022 5th gen
 - iOS version: 15.7
 - App version latest from app store

**Comment by alexstaravoitau** [comment]
Hi @allengwinn — apologies for a late reply. I've tried Juno release from the App Store and it seems to show and open iCloud files fine, although based on your info (thanks for the details by the way!) it sounds like maybe the file association got broken. This is handled by the system, and if that's the issue Juno can't do much about it I'm afraid. I'd say try restarting your device, and perhaps delete and re-install Juno — hopefully this will get the file association "unstuck".

**Comment by allengwinn** [comment]
Yeah it looks like the later versions of iOS don't handle to associations too cleverly. Carnets just shows everything associated. You may have to do this. I tried uninstalling and rebooting. Did not help.

Even in the local directory it is broken.



Allen Gwinn

**Comment by alexstaravoitau** [comment]
Juno 3.0 is now live on the App Store, and it uses its own file browser—which hopefully resolves this issue. Feel free to reopen or submit a new one if the issue still happens.
