### ISSUE TITLE
Shift on iOS keyboard I’d Caps-Lock

### ISSUE THREAD

**Issue by a1ex5** [rationalmatter/Juno-Issue-Tracker#33]
When using the on-screen keyboard, pressing Shift (⇧) locks the keyboard in Caps mode until you press it again. 

It should capitalise only the next key you press, unless you double-tap (and “Enable Caps Lock” is enabled in Keyboard Preferences). Double-tapping in Juno obviously switches Caps mode on and off again.

Shift and Caps-Lock behave normally with a hardware keyboard. 

This on an iPhone 8 Plus. 

Edit: Just noticed that the same thing happens in the online Juno app.

**Comment by navoshta** [comment]
Yep, apparently this is a WebKit issue — which appears to be fixed in iOS 13. I'll see if I can come up with a workaround for iOS 12, otherwise just give it a couple of weeks until iOS 13 comes out.
