### ISSUE TITLE
Option to disable cell toolbar

### ISSUE THREAD

**Issue by globophobe** [rationalmatter/Juno-Issue-Tracker#333]
**Is your feature request related to a problem? Please describe.**

Basically, I bought Juno to read books written in Jupiter notebooks. Particularly, in dark mode the cell toolbar is distracting

![965695D4-6740-4556-BD04-2F3B47ED8C60](https://user-images.githubusercontent.com/891192/206884214-30850dfb-1631-4796-a071-d0db9c3dece8.png)

**Describe the solution you'd like**

An option to turn off the cell toolbar

**Comment by alexstaravoitau** [comment]
Thanks for reporting @globophobe — judging by the screenshot this is Juno, not Juno Connect? I will fix in the next release, thanks for reporting.

**Comment by alexstaravoitau** [comment]
Juno 2.1 with the fix is now live on App Store.
