### ISSUE TITLE
Syntax highlighting for complex numbers

### ISSUE THREAD

**Issue by Moooongo** [rationalmatter/Juno-Issue-Tracker#338]
Numbers such as 1+2j are complex numbers using built-in complex type. Currently the letter j in the number is not highlighted the same color as the number 2.

**Comment by alexstaravoitau** [comment]
Thanks for reporting @Moooongo — could you please attach a screenshot with an example? I've checked briefly, and it seemed to be highlighted correctly (same as in desktop Jupyter), although perhaps I'm missing something.

Also, which app is it? Is it Juno or Juno Connect?

**Comment by Moooongo** [comment]
@navoshta 
I have Juno version 2.0.12 (7324)
In this screen, the number 1e13 (line 13) is highlighted correctly with the letter 'e', same as the rest of the number;
the number 0j (line 17-19) is not highlighted correctly.

![IMG_0037](https://user-images.githubusercontent.com/51526111/217912334-f29ff70a-351f-4cd1-95d1-e6227677d7a2.jpeg)

**Comment by alexstaravoitau** [comment]
Looks like it's because of the `0` imaginary part — as long as it's non-zero (e.g. `+1j`) or is a `float` (e.g. `+0.0j`), it's highlighted fine. Highlighting is done by CodeMirror, so you may need to file this issue in the upstream repo: https://github.com/codemirror/codemirror5
