### ISSUE TITLE
Add backtesting

### ISSUE THREAD

**Issue by Tumppu74** [rationalmatter/Juno-Issue-Tracker#339]
https://kernc.github.io/backtesting.py/

**Comment by alexstaravoitau** [comment]
Thanks for reporting @Tumppu74, Backtesting looks like a pure Python package, however Juno still fails to install it for some reason — I will look into this. 

Meanwhile, you should be able to install it manually by unpacking the distribution from PyPI into the *site-packages* directory in Juno's on-device directory.

**Comment by alexstaravoitau** [comment]
Backtesting is now a pre-installed package in Juno 2.1.3 (available on TestFlight)
