### ISSUE TITLE
Package Request

### ISSUE THREAD

**Issue by ParzivalWins** [rationalmatter/Juno-Issue-Tracker#34]
**What is the name of the package?**
How do you insert packages into folder /site-packages ?

Here's a list of requested packages:
pandas
Tensorflow
Sklearn
Scipy

Thank you in advance.

**Comment by navoshta** [comment]
Please, search existing issues for packages that have already been requested (and upvote if you want them, too). Also, please create one issue per package — so that others can vote for each individually, and it's easier for me to prioritise.
