### ISSUE TITLE
Networkx import error

### ISSUE THREAD

**Issue by rpehlm** [rationalmatter/Juno-Issue-Tracker#340]
Warning: New user!!!
Steps:
- Used the package manager to install Networkx version 3.0 (have also tried 2.8)
- In an ipynb file tried to import with 'import networkx as nx'
- Running the cell generates:
  ImportError                               Traceback (most recent call last)
<ipython-input-1-f17d728e971c> in <module>
----> 1 import networkx as nx

/var/mobile/Containers/Data/Application/6AB0C4A5-C3F5-4966-A324-EC18A33F4ED2/Documents/site-packages/networkx/__init__.py in <module>
     59 from networkx import utils
     60 
---> 61 from networkx import classes
     62 from networkx.classes import filters
     63 from networkx.classes import *

/var/mobile/Containers/Data/Application/6AB0C4A5-C3F5-4966-A324-EC18A33F4ED2/Documents/site-packages/networkx/classes/__init__.py in <module>
----> 1 from .graph import Graph
      2 from .digraph import DiGraph
      3 from .multigraph import MultiGraph
      4 from .multidigraph import MultiDiGraph
      5 from .ordered import *

/var/mobile/Containers/Data/Application/6AB0C4A5-C3F5-4966-A324-EC18A33F4ED2/Documents/site-packages/networkx/classes/graph.py in <module>
      9 """
     10 from copy import deepcopy
---> 11 from functools import cached_property
     12 
     13 import networkx as nx

ImportError: cannot import name 'cached_property'

**Environment:**
 - Device: iPad model A2696 (2022)
 - iOS version: 16.3
 - App version: 2.0.12 (7324)

**Comment by alexstaravoitau** [comment]
Thanks for reporting @rpehlm — this is likely because of Python 3.6. I'm reasonably close to releasing Juno with Python 3.10, ping me at beta@juno.sh and I'll add you to our TestFlight, so that you can give it a go. 😇

**Comment by rpehlm** [comment]
Looks like you fixed it.
Thanks!

**Comment by alexstaravoitau** [comment]
No worries @rpehlm — closing the issue, as Juno with Python 3.10 should be released soon anyway.
