### ISSUE TITLE
Version 2.1.2 not saving new content on existing notebooks

### ISSUE THREAD

**Issue by lmatute** [rationalmatter/Juno-Issue-Tracker#345]
**Describe the bug**
Using a fresh notebook saving works fine. Using previously saved notebooks with the previous version to 2.1.2 will not  properly save modifications.

**To Reproduce**
1. Open an older notebook
2. Create a new chunk of code or text or delete an existing chunk
3. Exit the notebook
4. Re open the notebook and notice it is in the same state without you latest modifications

**Expected behavior**
All changes should be in the edited notebook

**Screenshots**
If applicable, add screenshots or a screen recording to help explain your problem.

**Environment (please complete the following information):**
 - Device: [e.g. iPad Pro 11"]
 - iOS version: [e.g. iOS 12.2]
 - App version [e.g. 1.0.0]

**Comment by alexstaravoitau** [comment]
Thanks for reporting @lmatute — I'll look into it. I'm assuming this is about Juno, not Juno Connect.

Which iOS/device is it btw?

**Comment by lmatute** [comment]
Yes , JunoiPad Pro 3rd generation 11 inch iOS 16.3.1LuisOn Mar 3, 2023, at 11:08 AM, Alex Staravoitau ***@***.***> wrote:﻿
Thanks for reporting @lmatute — I'll look into it. I'm assuming this is about Juno, not Juno Connect.
Which iOS/device is it btw?

**Comment by alexstaravoitau** [comment]
This should be fixed in Juno 2.1.3 by related changes — but please feel free to reopen if you notice this still happens @lmatute.
