### ISSUE TITLE
Juno Crashes at Start

### ISSUE THREAD

**Issue by mrkungfu** [rationalmatter/Juno-Issue-Tracker#349]
**Describe the bug**
Juno crashes when trying to execute the app.

**To Reproduce**
On the Home Screen, tap on the Juno app icon.

**Expected behavior**
Juno opens. :)

**Environment (please complete the following information):**
 - Device: iPad Pro 12.9" (6th gen/M2)
 - iOS version: 16.4 but also 16.3.1
 - App version: I assume 2.0.12 per the App Store

**Comment by alexstaravoitau** [comment]
Hi @mrkungfu — apologies for a super-late reply. Did you have Juno installed before by any chance? Or did you just install it from the App Store? Does reinstalling it from scratch help at all?

Juno 2.1 will be released on App Store soon with a lot of under the hood changes, perhaps you would like to check out 2.1 beta meanwhile — ping me at beta@juno.sh, and I'll add you to our TestFlight.

**Comment by alexstaravoitau** [comment]
Hey @mrkungfu — Juno 2.1 is now live on App Store, hopefully fixing the crashes. Let me know if they still happen (feel free to reopen this issue).
