### ISSUE TITLE
Cannot access through SSH to different notebook servers hosted in the same machine

### ISSUE THREAD

**Issue by jfzo** [rationalmatter/Juno-Issue-Tracker#351]
**Describe the bug**

I added two Jupyter servers hosted in the same machine but accessed through different ports. Both connections are set with SSH port forwarding.
The problem is that once I connect to one server, both connections end forwarded to that port hence it’s impossible to establish a connection to the other server. 

**To Reproduce**

1. Add two Jupyter servers having the same IP address but in different ports. 
2. Enable port forwarding.
3. Pick one of both and start the connection.
4. After a successful connection, attempt to connect to the second server.

**Expected behavior**
This second connection will forward you to the first jupyter server instead to the second one.

**Screenshots**
Four screenshots are attached. Two with the port forwarding configuration and two with the resulting URL in both servers.

First jupyter server.
<img width="580" alt="first_connection" src="https://user-images.githubusercontent.com/10759410/229668834-01fbe669-f125-4627-a41a-4b29e4984ab6.png">

Second jupyter server (same remote host than the previous one).
<img width="580" alt="second_connection" src="https://user-images.githubusercontent.com/10759410/229668839-e90bc18a-30f5-470f-a520-0b7b276cecdd.png">

After connecting to the first server, works ok.
<img width="612" alt="first_connection_url" src="https://user-images.githubusercontent.com/10759410/229668847-84f8a5a9-e4a4-47fa-a2a7-ab9903141099.png">

When attempting a connection to the second, the same local URL is used.
<img width="632" alt="second_connection_url" src="https://user-images.githubusercontent.com/10759410/229668844-93544d2a-7132-4333-ad9e-b181273ed6a5.png">

**Environment (please complete the following information):**
 - Device: [e.g. iPad Pro 11"]
 - iOS version: [e.g. iOS 12.2]
 - App version [e.g. 1.0.0]

**Comment by jfzo** [comment]
I just realized it was already reported on [issue 337](https://github.com/rationalmatter/Juno-Issue-Tracker/issues/337).

**Comment by alexstaravoitau** [comment]
Thanks for reporting @jfzo — yes you are right, looks like it's the same issue. I'll close this one as a duplicate, but this is certainly something I will be looking into for the next Juno Connect release.
