### ISSUE TITLE
Add Langchain

### ISSUE THREAD

**Issue by jmontrose** [rationalmatter/Juno-Issue-Tracker#352]
Langchain

https://github.com/hwchase17/langchain

Installs fine, but fails import trying to load SQLAlchemy  (requested by someone else in #311 )

**Comment by alexstaravoitau** [comment]
Thanks for reporting @jmontrose — you should be able to install both Langchain and SQLAlchemy using Juno's package manager now (although not sure if Langchain has any other dependencies).

**Comment by jmontrose** [comment]
Thanks!  SQLAlchemy loaded up fine 👍

Looks like the next langchain dependency is numexpr, and probably not so quick :)

Filed in #354

**Comment by alexstaravoitau** [comment]
Thanks for reporting @jmontrose — yes, numexpr may be a bit more tricky, but it's certainly on the roadmap.
