### ISSUE TITLE
ipycanvas package is not working

### ISSUE THREAD

**Issue by onsi** [rationalmatter/Juno-Issue-Tracker#358]
**Describe the bug**
The [ipycanvas](https://ipycanvas.readthedocs.io/en/latest/index.html#) package installs but does not show any rendered output.

**To Reproduce**
1. Install ipycanvas using Juno’s built-in package manger
2. Create a new notebook with this code in a single cell:

```python
from ipycanvas import Canvas

canvas = Canvas(width=200, height=200)

canvas.fill_rect(25, 25, 100, 100)
canvas.clear_rect(45, 45, 60, 60)
canvas.stroke_rect(50, 50, 50, 50)

canvas
```

**Expected behavior**
An image should appear as output.  Instead, nothing appears.  Is ipycanvas supported?  Do I need to do anything differently on my end?

**Environment (please complete the following information):**
 - Device: M2 iPad Pro 13”
 - iOS version: 16.5.1
 - App version: latest( fresh install)

**Comment by alexstaravoitau** [comment]
Thanks for reporting @onsi — Juno's package manager is the issue here, I'm afraid. Looks like it doesn't install all the necessary data the package comes with, hence ipycanvas functionality is broken. 

I will embed ipycanvas as a pinned package in the next Juno release, and will then upgrade package manager to properly handle package data (this will need more work under the hood, so will arrive a bit later).

**Comment by onsi** [comment]
thanks! looking forward to the next release - and all the best as you fix the package manager

**Comment by lethall** [comment]
I just purchased both Juno (2.1.8) and Juno Connect (1.6.13). I was disappointed to find that this problem - reported 7 months ago - was not addressed in this version which was released 2 months ago.

**Comment by lethall** [comment]
@alexstaravoitau - what is the data which is missing from ipycanvas? I have it installed on my Jupyter server (where it works fine) so I copied it from the site-packages of my server to the Juno site-packages on my iOS device. The entire contents of these directories were copied:
![image](https://github.com/rationalmatter/Juno-Issue-Tracker/assets/3585064/824cebc6-500b-4a8f-a4f4-a221e62af573)

It made no change. Still no error - but no output, either.

**Comment by alexstaravoitau** [comment]
@lethall — apologies it's taking a while. So, the ipycanvas requires copying some data folders in addition to the directories on your screenshot, and Juno's package manager doesn't support those (yet).

There's a new Juno beta build waiting for review on TestFlight, it will pin ipycanvas package (among a few other things), and drawing should work fine there. Let me know if you would like to join our TestFlight, alternatively this version will be available on App Store soon, too.

**Comment by lethall** [comment]
Thank you Alex. Yes I would like to help with the Test Flight version.

That said, I'm curious about the data folders. I use another package (SkyField) which has a problem in its dependent sgp4 library which requires a tweak on iOS to work around an import error. I was able to copy the workaround from the site-packages of another installation into Juno's and successfully make the tweak. I tried copying the ipycanvas package in the same way but it still produced no output.

**Comment by alexstaravoitau** [comment]
@lethall The missing data is not in the site-packages directory, unfortunately... It needs to be copied into the location that is not user-accessible.

Please ping me at beta@juno.sh, and I'll add your email to TestFlight.

**Comment by lethall** [comment]
Thanks for fixing this in the 2.3.1 beta. The ipycanvas package is ideal for making simple parametric figures. I notice that it doesn't work with the new "preview" feature (which is terrific, BTW!) but that isn't a problem, IMHO.

**Comment by alexstaravoitau** [comment]
> I notice that it doesn't work with the new "preview" feature (which is terrific, BTW!) but that isn't a problem, IMHO.

@lethall — interesting! Thanks for reporting, I'll see if I can get them to show up in previews, too.

**Comment by lethall** [comment]
Hi Alex,Unfortunately, ipycanvas output is broken in v2.3.2.I see that the doctest stdout is fixed in v2.3.2 but running doctest.testmod() is not discovering the tests in the module. Not a big deal for me.- LeeOn Feb 17, 2024, at 9:40 AM, Alex Staravoitau ***@***.***> wrote:﻿

I notice that it doesn't work with the new "preview" feature (which is terrific, BTW!) but that isn't a problem, IMHO.

@lethall — interesting! Thanks for reporting, I'll see if I can get them to show up in previews, too.

**Comment by alexstaravoitau** [comment]
@lethall Is ipycanvas output broken in 2.3.2 when you open and run the notebook, or only in notebook previews? (I didn't get to fixing them in previews yet I'm afraid).

**Comment by lethall** [comment]
The original problem of not showing output has returned when executing the cells in an open notebook.On Mar 6, 2024, at 7:46 AM, Alex Staravoitau ***@***.***> wrote:﻿
@lethall Is ipycanvas output broken in 2.3.2 when you open and run the notebook, or only in notebook previews? (I didn't get to fixing them in previews yet I'm afraid).

**Comment by alexstaravoitau** [comment]
@lethall Ah OK—apologies, I will look into this and fix in the next update.

**Comment by lethall** [comment]
Yay! 3.0.0 fixes it again. Looks good.On Mar 6, 2024, at 8:29 AM, Alex Staravoitau ***@***.***> wrote:﻿
@lethall Ah OK—apologies, I will look into this and fix in the next update.

**Comment by alexstaravoitau** [comment]
Juno 3.0 with pinned ipycanvas is now available on the App Store.
