### ISSUE TITLE
Add **XGBClassifier**

### ISSUE THREAD

**Issue by Dorota-Toskania** [rationalmatter/Juno-Issue-Tracker#361]
**What is the name of the package?**
A name or link to the Python package you think should be pre-installed in Juno. Mind that you can install pure Python packages from PyPI in Juno — those that can be successfully installed won't be embedded in the app.

**Comment by alexstaravoitau** [comment]
Thanks for reporting @Dorota-Toskania — there's already a request for XGBoost (https://github.com/rationalmatter/Juno-Issue-Tracker/issues/210), so I'll close this issue as a duplicate. I don't have an ETA I'm afraid, but XGBoost is a popular request and is on the roadmap.
