### ISSUE TITLE
ios 9.3.6

### ISSUE THREAD

**Issue by JuliosSur** [rationalmatter/Juno-Issue-Tracker#366]
I recently bought a used iPad which is about 10years old and runs on not updatable ios 9.3.6. while i knew that it wouldnt run all the apps im astonished at the audacity of apples fraud. really almost none of the apps i would like to use works although i know the hardware didnt change so mich that ios 10 or higher wouldnt run. also why am i not able to install older versions? luckily enough, verbtex, an app that connects with a latex compiler online runs on the ipad which is a good use for writing math texts. i would also love to use juno and happily pay another 20 or what if there was a version available that runs on ios 9.3.6.

**Comment by alexstaravoitau** [comment]
I understand it's annoying @JuliosSur, but I'm afraid I won't be able to get Juno to run on iOS 9 or even iOS 10. Unfortunately, the app uses far too many APIs that are only available on recent versions of the OS.
