### ISSUE TITLE
Add **opencv**

### ISSUE THREAD

**Issue by Haliturey** [rationalmatter/Juno-Issue-Tracker#369]
I can find “opencv” on pypi but Juno couldn’t see this package in app. By the way I couldn’t add “opencv” to June via manually. I have a project and I couldn’t work for missing packages. Could you please solve it urgently ?

**Comment by alexstaravoitau** [comment]
Thanks for reporting @Haliturey — I'll close this issue as a duplicate of #109. OpenCV is a popular request, and we will be looking into adding it to Juno very soon.
