### ISSUE TITLE
Failed to display notebook

### ISSUE THREAD

**Issue by sanga-yoon** [rationalmatter/Juno-Issue-Tracker#371]
**Describe the bug**
The Jupyter Notebook page shows that the app failed to display the notebook. (File tree works without any problem.)

**To Reproduce**
1. Connect to any running Jupyter server
2. Authenticate, then click any notebook, regardless of whether it is already running or newly made in Juno Connect. 

**Expected behavior**
Jupyter notebook opens. 

**Screenshots**
![image](https://github.com/rationalmatter/Juno-Issue-Tracker/assets/48780831/60eb6c61-42a9-4cea-a954-5417eab2db7b)

**Environment (please complete the following information):**
 - Device: iPhone 14 Pro
 - iOS version: iOS 17.0.3
 - App version 1.6.13 (6738)

**Comment by alexstaravoitau** [comment]
Hi @hojun-y — could you please take a look a these issues, and see if anything looks similar? #268 and #365.

I suspect you may be connecting to a server running JupyterLab >4.0 or Jupyter Notebook >7.0, in which case you may need to install `nbclassic` and update your connection settings (see [this comment](https://github.com/rationalmatter/Juno-Issue-Tracker/issues/365#issuecomment-1676341107)).

**Comment by sanga-yoon** [comment]
@alexstaravoitau 
The app works again after installing `nbclassic`.
Thanks for your support.
