### ISSUE TITLE
Add **Tensorflow**

### ISSUE THREAD

**Issue by M-alturk** [rationalmatter/Juno-Issue-Tracker#375]
**Tensorflow**

https://github.com/tensorflow/tensorflow/tags

**Comment by alexstaravoitau** [comment]
Thanks for reporting @M-alturk — TensorFlow is a long-standing request, and there is already an issue for it here: #39. I'll close this one as a duplicate.

I'm certainly planning to look into adding TensorFlow, but this is likely a huge job which will take a lot of effort and time. We are currently focusing on resolving more of the "low hanging fruit" package requests, but I do plan to look into bringing PyTorch or TensorFlow at some point.
