### ISSUE TITLE
Juno Crashing in the Background

### ISSUE THREAD

**Issue by iamrecursion** [rationalmatter/Juno-Issue-Tracker#377]
**Describe the bug**
I have a notebook that should not be using significant amounts of memory, especially on an M2 iPad Pro with 16GB of memory, but that nevertheless is getting killed in the background by iOS whenever tabbed away from for any appreciable length of time.

**To Reproduce**
1. Create a basic notebook
2. Go to the home screen
3. Wait 3 minutes
4. Re-open Juno and see that it's restarting

**Expected behavior**
Juno stays active in these circumstances.

**Screenshots**
If applicable, add screenshots or a screen recording to help explain your problem.

**Environment (please complete the following information):**
 - Device: iPad Pro (12.9-inch) (6th generation)
 - iOS version: 17.1.1
 - App version: 2.1.7 (8310)

**Comment by alexstaravoitau** [comment]
Thanks for reporting, @iamrecursion. As a general rule, iOS will suspend apps in the background after approximately 30 seconds — regardless of how much memory they use. That said, it looks like Juno crashes when being suspended, which shouldn't happen.

I'll be looking into this as part of the next big Juno update, which has some updates to background persistence among other things. The beta testing will start within a week or two; let me know if you would like to join our TestFlight and check it out early. You can reach out to [beta@juno.sh](mailto:beta@juno.sh) if you want to join the beta channel.

**Comment by iamrecursion** [comment]
Yeah I'd expect it to be suspended, rather than start from the app loading screen again when I go back to it. It's a bit disruptive!

Yeah I'd love to join the TestFlight; I've sent an email to that email!

**Comment by alexstaravoitau** [comment]
I've added you @iamrecursion. A new beta build is currently pending Apple review on TestFlight — it should have the background crash fixed.

**Comment by iamrecursion** [comment]
This does indeed appear to have fixed it! Awesome!
