### ISSUE TITLE
Pydantic import error

### ISSUE THREAD

**Issue by lmatute** [rationalmatter/Juno-Issue-Tracker#378]
On loading pydantic with the command "from pydantic import DataModel" with Juno  I get an import error

**To Reproduce**
1. From pydantic import dataModel
2. The error "ImportError: cannot import name 'TypeAliasType' from 'typing_extensions'" appears

 - Device: [e.g. iPad Pro 11"]
- APP version [2.17]
 - iOS version: [e.g. OS 17.1.1]

**Comment by alexstaravoitau** [comment]
Thanks for reporting @lmatute — does this work on desktop for you? Could you please share a more complete code example perhaps? 

From what I see, I don't think pydantic module exports a `DataModel` type, but perhaps I'm missing something.

**Comment by lmatute** [comment]
Alex,The example should state "from pydantic import BaseModel". In any case the error is still the same.Here are a few simple lines copied from the application that runs on my desktop:import pandas as pdimport numpy as npimport operatorfrom pydantic import BaseModelAnd.... I get the error.LuisOn Nov 29, 2023, at 9:01 AM, Alex Staravoitau ***@***.***> wrote:﻿
Thanks for reporting @lmatute — does this work on desktop for you? Could you please share a more complete code example perhaps?
From what I see, I don't think pydantic module exports a DataModel type, but perhaps I'm missing something.

**Comment by alexstaravoitau** [comment]
Hey @lmatute — a new Juno beta build should be available on TestFlight soon with pydantic fixed. Not sure if you're on our TestFlight, ping me at beta@juno.sh if you would like to join the beta channel.

**Comment by lmatute** [comment]
Alex,Using the Juno beta I tried "import pydantic"  but do get the same error:ImportError: cannot import name 'TypeAliasType' from 'typing_extensions'LuisOn Dec 4, 2023, at 7:19 AM, Alex Staravoitau ***@***.***> wrote:﻿
Hey @lmatute — a new Juno beta build should be available on TestFlight soon with pydantic fixed. Not sure if you're on our TestFlight, ping me at ***@***.*** if you would like to join the beta channel.

**Comment by alexstaravoitau** [comment]
@lmatute This seems to work on the latest App Store release and TestFlight builds. Could you please try backing up your documents, deleting Juno from your device and installing from scratch (either from App Store or TestFlight)?

**Comment by lmatute** [comment]
Problem solved! I followed your instructions and it works. Many thanks, LuisOn Dec 9, 2023, at 8:44 AM, Alex Staravoitau ***@***.***> wrote:﻿
@lmatute This seems to work on the latest App Store release and TestFlight builds. Could you please try backing up your documents, deleting Juno from your device and installing from scratch (either from App Store or TestFlight)?
