### ISSUE TITLE
Unexpected behavior when trying to select an autocomplete suggestion on latest TestFlight Beta

### ISSUE THREAD

**Issue by kylefmohr** [rationalmatter/Juno-Issue-Tracker#379]
**Describe the bug**
Hello! This quick screen capture should help demonstrate:

https://github.com/rationalmatter/Juno-Issue-Tracker/assets/6644803/d8063fec-f4c6-4902-915f-1288345eab8f

The gist is that when I type `im`, an autocomplete menu pops up, and suggests "import" as the highlighted suggestion. I'd like to choose this selection, but neither `tab` nor the `->|`  button complete the autofill, instead adding two spaces.

**Expected behavior**
In my opinion, the blue `->|` symbol reads to me as a suggestion to press tab. I noticed I could tap on the blue arrow symbol, but this doesn't feel very streamlined.

**Environment (please complete the following information):**
 - Device: iPad Pro 11" 2nd Gen
 - iPadOS 17.2
 - Juno v. 2.2.0 (8792) via TestFlight

Thank you again for the opportunity to beta test Juno! This upcoming release seems to have a lot of potential, and is very exciting to me.

**Comment by alexstaravoitau** [comment]
Thanks for reporting @kylefmohr — this should be fixed in the new build.

**Comment by kylefmohr** [comment]
Can confirm, thanks for the quick fix!
