### ISSUE TITLE
Changing color scheme doesn't update text

### ISSUE THREAD

**Issue by dnigendac** [rationalmatter/Juno-Issue-Tracker#38]
**Describe the bug**
Changing color scheme doesn't update text. If I select "Dark"  once I get thrown back to the config modal "Light" is shown instead.

**To Reproduce**
1. Go to 'Configuration'
2. Tap on 'Color Scheme'
3. Choose 'Dark' and get returned to Configuration automatically.
4. Color scheme still shows "Light"

**Expected behavior**
Color scheme should show "Dark" in this case. Note that closing Configuration and reopening does show "Dark" as expected.

**Environment (please complete the following information):**
 - Device: iPad Pro 11"
 - iOS version: iOS 12.4.1
 - App version 1.0.4

**Comment by navoshta** [comment]
Thanks, same goes for Esc mapping selection — it will be fixed in the next release (spotted this too late! 😭)

**Comment by dnigendac** [comment]
No worries, I was excited too when I saw Pandas support so don't blame you for releasing this quickly 😀

**Comment by navoshta** [comment]
This should be fixed in Juno 1.1 and Juno Connect 1.4.
