### ISSUE TITLE
Could you add in support for other languages as well?

### ISSUE THREAD

**Issue by keys-i** [rationalmatter/Juno-Issue-Tracker#387]
I would really love to use Julia and R on Juno as well

**Comment by alexstaravoitau** [comment]
Hi @radhesh1 — there are no concrete plans at the moment, but I wouldn't rule it out in future. This would be a fairly ambitious task though, so I wouldn't expect it anytime soon I'm afraid. 

I'll close the issue for now, and will update Juno's FAQ to mention plans for adding other languages.

**Comment by keys-i** [comment]
thanks i hope you guys do
