### ISSUE TITLE
Notebook json gets minified on save

### ISSUE THREAD

**Issue by drewcassidy** [rationalmatter/Juno-Issue-Tracker#393]
**Describe the bug**
When Juno saves a notebook, it minifies the json down to a single line. This differs from the usual jupyter desktop implementation. This makes working through a git repo somewhat annoying when switching between Juno and a desktop client.

**To Reproduce**
1. Open a jupyter notebook made on another platform
2. Make a change
3. Save the notebook
4. Open in a text editor. everything has been compacted down to 1 line

**Expected behavior**
The only thing changed in the JSON should be what was changed in Juno, not the whole file
**Environment (please complete the following information):**

 - Device: M2 iPad pro 11”
 - iOS version: iPadOS 17.3.1
 - App version 3.0.1

**Comment by alexstaravoitau** [comment]
Thanks for reporting @drewcassidy — this will be fixed in the next update.

**Comment by alexstaravoitau** [comment]
This should be fixed in Juno 3.1 (now available on the App Store).
