### ISSUE TITLE
.tpl Files are hidden

### ISSUE THREAD

**Issue by dideldudeldei** [rationalmatter/Juno-Issue-Tracker#399]
**Describe the bug**
tpl files doesn’t show up in file manager. Even with show hidden files enabled

**Environment (please complete the following information):**
 - Device: [e.g. iPad Pro 11"]
 - iOS version: [e.g. iOS 17.4.1]
 - App version [e.g. 3.0.1]

**Comment by alexstaravoitau** [comment]
Thanks for reporting @dideldudeldei—I will look into this.

**Comment by alexstaravoitau** [comment]
Apologies, I forgot to update this issue, but the fix should have made it to the App Store by now.
