### ISSUE TITLE
Add seaborn

### ISSUE THREAD

**Issue by desilinguist** [rationalmatter/Juno-Issue-Tracker#4]
**What is the name of the package?**

https://seaborn.pydata.org/

**Comment by navoshta** [comment]
Seems to install OK with Juno's [new package installer](https://github.com/rationalmatter/Juno-Issue-Tracker/issues/37#issuecomment-529098898), but apparently it requires SciPy — which has native extensions, and is, in general, a more serious issue to tackle. There's already #25 for SciPy though, so closing this one.
