### ISSUE TITLE
White text on white background while in Dark file browser

### ISSUE THREAD

**Issue by dnigendac** [rationalmatter/Juno-Issue-Tracker#40]
**Describe the bug**
It's hard to discern text when typing it in the file browser when in Dark mode, as text is white on white.

**To Reproduce**
1. Enable Dark Mode.
2. Browse documents
3. Long press on a document to rename it
4. Try to figure out what the text says :)

**Expected behavior**
Text should be white on dark background (or failing that, black on white).

**Screenshots**
![There's some text here, I swear](https://user-images.githubusercontent.com/4257488/64478811-d1e5a880-d162-11e9-877c-ff540189a8ca.jpeg)

**Environment (please complete the following information):**
 - Device: iPad Pro 11"
 - iOS version: iOS 12.4.1
 - App version 1.0.4

**Comment by navoshta** [comment]
This should be resolved now (apologies for a super-late reply!).
