### ISSUE TITLE
Juno app will not open

### ISSUE THREAD

**Issue by dkhundley** [rationalmatter/Juno-Issue-Tracker#401]
**Describe the bug**
App will not open. Immediately closes on attempting to open.

**To Reproduce**
1. Attempt to open the app

**Expected behavior**
The app opening as normal

**Screenshots**
See this video: https://x.com/dkhundley/status/1791214567042789520?s=61

**Environment (please complete the following information):**
 - Device: iPad Pro M4 13”
 - iOS version: iOS 17.5
 - App version: 3.0.1

**Comment by dkhundley** [comment]
No issue with Juno Connect, fortunately!

**Comment by alexstaravoitau** [comment]
Leaving a comment in case anyone stumbles on the same issue: if the device has been restored from backup recently, please try deleting Juno and reinstalling from App Store. This should be fixed in 3.1 (currently in beta).
