### ISSUE TITLE
Crashes on Launch

### ISSUE THREAD

**Issue by jdstanhope** [rationalmatter/Juno-Issue-Tracker#404]
**Describe the bug**
Clicking on the icon the splash screen briefly appears then goes away.  

**To Reproduce**
1. Launch app

**Expected behavior**
App launches.

**Screenshots**
If applicable, add screenshots or a screen recording to help explain your problem.

**Environment (please complete the following information):**
 - Device: iPad Pro 13-inch (M4)
 - iOS version: iPadOS 17.5.1
 - App version 3.0.1
 - I am using stage manager and more space.

**Comment by alexstaravoitau** [comment]
Please, check #401: if your device has been restored from backup recently, try reinstalling Juno. This should also be fixed in 3.1 (now available on the App Store).

**Comment by alexstaravoitau** [comment]
Closing for now—feel free to reopen if the issue persists, and I'll be happy to investigate further.
