### ISSUE TITLE
Problem with 'reliability package'

### ISSUE THREAD

**Issue by brodzirp1** [rationalmatter/Juno-Issue-Tracker#408]
**Downloaded reliability package ver 08.16 **
Package not working with Juno
**Screenshots**
![image](https://github.com/rationalmatter/Juno-Issue-Tracker/assets/62778468/2ba1ad63-e29f-448b-9d4f-355cc24ea772)
![image](https://github.com/rationalmatter/Juno-Issue-Tracker/assets/62778468/7ef202b2-ee61-4f6a-b65a-b16bcea8ac99)
![image](https://github.com/rationalmatter/Juno-Issue-Tracker/assets/62778468/b0d168cd-c466-40b4-b26c-faa7b04ebf2b)

**Comment by alexstaravoitau** [comment]
Hi @brodzirp1, I've tried installing Reliability and its dependencies, and one of them fails to install unfortunately—it's the `mplcursors` package. Keep in mind that some of the pinned dependencies seem to be too old for Reliability 0.8.16, so you may need to install an earlier version.

Looks like when all dependencies are available, Reliability should be working fine—I'll close this issue in favour of this one: https://github.com/rationalmatter/Juno-Issue-Tracker/issues/410
