### ISSUE TITLE
Allow ProxyJump SSH option

### ISSUE THREAD

**Issue by dpo** [rationalmatter/Juno-Issue-Tracker#412]
**Is your feature request related to a problem? Please describe.**

The machine running my Jupyter server is not directly accessible from the outside world, but instead must be accessed by first SSH’ing into another machine.

**Describe the solution you'd like**

Allowing the `ProxyJump` SSH configuration option so that two SSH configurations can be used, one for each machine.

**Comment by alexstaravoitau** [comment]
Thanks for reporting @dpo—looks like this is a duplicate of #386? Feel free to reopen otherwise.
