### ISSUE TITLE
No es posible sacar tu proprio archivo de texto del environment

### ISSUE THREAD

**Issue by AmePelliccia** [rationalmatter/Juno-Issue-Tracker#414]
**Describe the bug**

**To Reproduce**
2. Tap on '....'

**Expected behavior**

**Screenshots**
If applicable, add screenshots or a screen recording to help explain your problem.

**Environment (please complete the following information):**
 - Device: [e.g. iPad Pro 11"]
 - iOS version: [e.g. iOS 12.2]
 - App version [e.g. 1.0.0]

**Comment by alexstaravoitau** [comment]
Sounds like a duplicate of #46, feel free to reopen otherwise.
