### ISSUE TITLE
ipywidgets interactive widgets do not refresh but add a new widget

### ISSUE THREAD

**Issue by callms** [rationalmatter/Juno-Issue-Tracker#415]
**Describe the bug**
When using widgets from `ipywidgets`, the widgets such as sliders work. However, instead of refreshing the current plot, they re-create a new one every time we interact with them.

**To Reproduce**
1. Use the following cell:
```python
from ipywidgets import interact, interactive, fixed, interact_manual
import ipywidgets as widgets

import matplotlib.pyplot as plt

import numpy as np

def logics(p):
    fig, gnt = plt.subplots(figsize=(6,2))
    gnt.broken_barh([(p, 1-p)], (0, 1), facecolors='tab:red')
    
interact(logics, p=widgets.FloatSlider(min=0, max=1, step=0.05, value=0.5))
```
2. Interact with the slider
3. Notice how the plot re-renders everytime

**Expected behavior**
The plot should update in place

**Screenshots**
<img width="1600" alt="image" src="https://github.com/user-attachments/assets/1624b9d5-fd49-447b-9dab-48958cfd9681">

**Environment (please complete the following information):**
 - Device: iPad Pro M4 13"
 - iOS version: 17.5.1
 - App version: 3.1.0

**Comment by alexstaravoitau** [comment]
IIRC you need to call `plt.show()` at the end of your `logics()` function to update the plot interactively.

**Comment by callms** [comment]
Thanks @alexstaravoitau , it looks like it works. Closing!
