### ISSUE TITLE
Block Uncomment Bug with certain files

### ISSUE THREAD

**Issue by DocSK** [rationalmatter/Juno-Issue-Tracker#419]
I am trying to uncomment blocks of example python script code for a MIT Python course. The lines of code are commented in conventional style beginning with "# ". Instead of uncommenting and removing the "# ", the Juno editor inserts an additional "# " at the beginning of each line of commented code,also inserts an extra new line between each line of code and also comments out the inserted extra lines!

The same file and code uncomment correctly in Anaconda Spyder on a Windows 11 laptop and Textastic on the same iPad I am running Juno on suggesting there is a bug in Juno in coping with these particular script files. 

1. Go to https://ocw.mit.edu/courses/6-100l-introduction-to-cs-and-programming-using-python-fall-2022/resources/mit6_100l_f22_lec03_code_py/

to download a representative script file for lecture 3.

2. Insert cursor in a line of code which is commented out (e.g. the While Loop example at top of script) to bring up the Juno floating toolbar. Mark a block of commented code and tap on the "#" icon in the toolbar.
3. The code will be formatted incorrectly as described above.

 - Device: iPad Pro 11" M4
 - iOS version: iOS 17.6.1
 - App version: 3.2.0 (9235)

**Comment by DocSK** [comment]
I think the issue may be due to some sort of Windows / Mac encoding used in the files which Juno cannot cope with. 

If I open the file in Pythonista 3 (latest version) and make some minor edit so that the file gets saved by Pythonista and then open the file in Juno, then the Uncomment / Comment behaves as it should.

The bottom line is that if Textastic and Pythonista can cope with the file, then so should Juno.

I have purchased 3 iPadOS Python IDEs (Juno, Pythonista, Pyto) to learn Python and currently none of them can do Uncomment  / Comment in any reliable and satisfactory fashion. Extremely frustrating!😫

I hope this can be fixed quickly. I really don’t want to have to resort to using a Windows laptop having just upgraded to a new £1500 iPad Pro.

**Comment by alexstaravoitau** [comment]
Thanks for reporting @DocSK — this will be fixed in the next Juno update.

**Comment by alexstaravoitau** [comment]
Closing as the fix has made it to the App Store in one of the recent builds.
