### ISSUE TITLE
Add ability to manage installed packages

### ISSUE THREAD

**Issue by tlockney** [rationalmatter/Juno-Issue-Tracker#42]
**Describe the solution you'd like**
The package installer is a nice touch, but there's no easy/obvious way to manage packages after they're installed or even see what has been installed. At this point, it requires creating a notebook and interrogating the environment, unless I'm missing some other option.

**Comment by navoshta** [comment]
Yes, this is certainly in the backlog. 

In its current form, package installer is completely stateless — it doesn't track previously installed packages (apart from those that are pre-installed), and lets the user manage them manually. It installs everything into _/site-packages_ directory in app's on-device storage, overwriting whatever package version is already installed there. Managing packages is supposed to be handled manually right now: if you would like to remove a package, simply delete its folder in _/site-packages_. 

This installer is not ideal, but should be a tad easier than manually downloading/unpacking/extracting sources/copying into Juno. I'll leave this issue open, until proper package management is implemented. In the meantime, I agree that installer's behaviour can be confusing — I'm yet to come up with a proper way to communicate all this to the user. Let me know if you have any ideas!

**Comment by alexstaravoitau** [comment]
Juno 1.5 now comes with a package manager (currently available in beta on TestFlight) — please reach out to [beta@juno.sh](mailto:beta@juno.sh) if you would like to help test it. 🙃
