### ISSUE TITLE
Naming/Renaming Notebooks

### ISSUE THREAD

**Issue by gphilpott-com** [rationalmatter/Juno-Issue-Tracker#44]
**Is your feature request related to a problem? Please describe.**

First things first. Very new to Juno and Working Copy so apologies in advance if an easy way to name notebooks already exists.

Using Juno beta app on iPadOS beta with Working Copy for GitHub on iPad Pro.
 When using Juno, with working copy via the files app, I have two choices to create a notebook:
1. Tap the “+” icon in the upper right of the screen
2. Tap the “create document” icon at the top of the file list

Both choices create the notebook fine but neither provide a way to change the notebook name from “untitled”  easily.  

Going into Working copy you can rename the file, but is there a way to name a notebook from with in Juno easily.  

**Describe the solution you'd like**

Tapping the “untitled” next to the notebook icon at the top center of the screen could provide dialog to rename notebook.

**Comment by navoshta** [comment]
Yep, this should be possible: Juno has the same file managing features as iOS's Files app: tap and hold the file and select "Rename", or tap file title on iPadOS (iOS/iPadOS 13).

Please, feel free to reopen if I misunderstood.
