### ISSUE TITLE
Restart every time i switch to another app and return back to Juno

### ISSUE THREAD

**Issue by Rygor83** [rationalmatter/Juno-Issue-Tracker#48]
**Describe the bug**

I work in Juno. My document is opened. Then i need to read help about a function i use. i switch to Safari. One minute later i return back to Juno. Juno is restarting: clack screen with Juno logo, document browser. I need to open document again. 

**Expected behavior**
I wish i could return back to already opened document and continue working with it. 

**Environment (please complete the following information):**
 - Device: iphone Xs
 - iOS version: ios 13.1
 - App version: 1.1.0 (4127)

**Comment by navoshta** [comment]
Unfortunately, iOS doesn't allow extensive background activity — so Juno's internals (Python interpreter, Jupyter server, etc.) will be stopped/purged eventually, exact time subject to available memory, battery level (probably) and other factors. 

That said, I'm looking into ways to allow it running longer in background, or perhaps restoring state in a clever manner — but this means also restoring variables and loaded modules, which could be tricky.

**Comment by Rygor83** [comment]
Thank you for your answer. Looking forward for this possibility in future!

**Comment by navoshta** [comment]
@Rygor83 Juno 1.2 is now waiting for TestFlight review, and should be available in the next few days — please send an e-mail to beta@juno.sh if you would like to help test it! Although it will likely still get purged by the OS while in background (even if a bit less aggressively), Juno will now attempt to fully restore its context when reopened, making this process more seamless.
