### ISSUE TITLE
Selection not visible in dark mode

### ISSUE THREAD

**Issue by christianbrodbeck** [rationalmatter/Juno-Issue-Tracker#49]
**Describe the bug**
Since the latest update, I can’t see the text selection. I’m using dark mode. Editing etc. works as normal (i.e. I can copy/paste selected text), it is just not displayed properly.

**To Reproduce**
1. Use dark mode
2. Select some text

**Screenshots**

In the screenshot, several lines of code are selected:

![IMG_0238](https://user-images.githubusercontent.com/145771/65768588-5642a000-e0ff-11e9-926e-63be01584c71.png)

**Environment (please complete the following information):**
 - Device: iPad Pro (12.9-inch) (2nd generation)
 - iOS version: 13.1
 - App version 1.4.0

**Comment by navoshta** [comment]
Thanks for reporting — seems like text selection in WebKit views has changes in iOS 13, and needs some additional handling. I will look into this.

**Comment by navoshta** [comment]
This should now be fixed for both apps in Juno 1.1.1 and Juno Connect 1.4.1.
