### ISSUE TITLE
Reading files from iCloud Drive

### ISSUE THREAD

**Issue by yaroslavyaroslav** [rationalmatter/Juno-Issue-Tracker#50]
There’s lack of reading files from iCloud Drive. I mean, I can open notebook from any place in iCloud Drive but I can’t read any data within it except app folder. So it’ll be great to be able to add external folders to app from iCloud Drive like it’s made in IA Writer or Working Copy.

**Comment by navoshta** [comment]
If I understand correctly, you should be able to do that already, but the notebook needs to be in that folder, too. Basically, you can currently grant access to notebook directory, if it happens to reside outside of app's folder — you will see a folder icon with a lock and instructions on how to grant access to it.

That said, I agree that there should be a way to grant access to _arbitrary_ folder from notebook, not only to notebook dir — this is on the roadmap. Please, feel free to reopen if I misunderstood.
