### ISSUE TITLE
Cursor move by swipes disable keyboard input

### ISSUE THREAD

**Issue by yaroslavyaroslav** [rationalmatter/Juno-Issue-Tracker#51]
**Describe the bug**
Keyboard input disables after using system multitouch gesture of the cursor movement on iPad (Probably the same thing happens with 3D Touch on iPhone).

**To Reproduce**
1. Select any row in a notebook in the edit mode.
2. Make move cursor multitouch gesture (two fingers swiping on the keyboard)
3. Try to enter any key in the row from the keyboard.
4. The app fails to enter any key until a notebook restart.

**Expected behavior**
To enter a letter by virtual keyboard. 

**Screenshots**
[Video of the issue](https://yadi.sk/i/FOrwvir7p1V2GQ)

**Environment (please complete the following information):**
 - Device: iPad Air 3rd gen
 - iOS version: iOS 13.1
 - App version 1.0.0

**Comment by navoshta** [comment]
Thanks for reporting, I will look into this.

**Comment by navoshta** [comment]
This should now be fixed in both apps, including versions available on the App Store.
