### ISSUE TITLE
Cannot use https when using port forwarding

### ISSUE THREAD

**Issue by peterhob** [rationalmatter/Juno-Issue-Tracker#53]
**Describe the bug**
When using the port forwarding, ssl error will show in the server. As I figured out, it is because the default url when using port forwarding in Juno is http not https. This can be easily fixed by adding a https switch like the one in the normal http connection.

**To Reproduce**
Set up the Jupiter server using SSL, then using Juno's port forwarding to connect. You will sure find it could not connect.

**Expected behavior**
A simple workaround is to stop using ssl in the Jupiter server.

**Environment (please complete the following information):**
 - Device: iPad pro
 - iOS version: iOS 13.1.1
 - App version 1.4.0

**Comment by navoshta** [comment]
Yes, Juno uses HTTP by default, as I was mainly thinking of port forwarding to `localhost`, which most users won't access using SSL anyway. I agree though, there should be an option to enable HTTPS if needed. I will look into this, thanks for reporting!

**Comment by navoshta** [comment]
@peterhob Juno Connect 1.5 is now in beta with an option to enable HTTPS for port forwarding connections — if you would like to help test it, please send the e-mail address you use with your Apple ID to beta@juno.sh 😉

**Comment by peterhob** [comment]
Sounds great. Will do.😀

Thanks for making such a handy tool.

**Comment by navoshta** [comment]
Juno Connect 1.5 is now live on App Store, so closing the issue. 🚀
