### ISSUE TITLE
Cannot open any notebooks

### ISSUE THREAD

**Issue by elwarren** [rationalmatter/Juno-Issue-Tracker#55]
**Describe the bug**
Cannot open a notebook after saving. 
Cannot open a notebook from the examples folder. 

**To Reproduce**
1. Creating new notebook results in file named Untitled. 
2. Can execute code. 
3. Saves ok. 
4. When attempting to open, file is greyed out. 
5. Long press does nothing. 

**Expected behavior**
Should be able to open a notebook. 

**Screenshots**
If applicable, add screenshots or a screen recording to help explain your problem.
![54E00528-3FA0-4607-B40B-8DE76A99504E](https://user-images.githubusercontent.com/117653/65928700-fa14a000-e3cc-11e9-9e40-e8d2945e2e1f.png)
![D92A793D-E447-4737-97AA-246C53CF4CE9](https://user-images.githubusercontent.com/117653/65928701-fa14a000-e3cc-11e9-9744-a2471fbe64c2.png)
![D67169F2-C431-4B7C-8414-F16B212B01EC](https://user-images.githubusercontent.com/117653/65928702-fa14a000-e3cc-11e9-9ab2-811247cc564c.png)

**Environment (please complete the following information):**
 - Device: iPhone xr
 - iOS version: ios 12.4
 - App version 1.1.0 (4127)

**Comment by elwarren** [comment]
This also happens on iPad mini.

**Comment by navoshta** [comment]
@elwarren, it sounds like you have another app installed, which is abusing iOS file association, claiming Jupyter Notebook format (which is public and open) as their own, preventing other apps from using it. Do you have this app installed by any chance? https://apps.apple.com/app/id1326802832

**Comment by elwarren** [comment]
Yes, I do have that installed. Just uninstalled it and restarted phone. Can open notebooks now. Thanks for fast response!

**Comment by banesullivan** [comment]
Also happened to me on my iPad Pro... screen capture [here](https://www.dropbox.com/s/8qsvgtghkneyntg/Video%20Oct%2006%2C%208%2043%2029%20PM.mp4?dl=0) (I might delete that video in a month or so)

I found out that the app [Notebook Master for Jupyter](https://apps.apple.com/us/app/notebook-master-for-jupyter/id1326802832) was causing the conflict for me:
