### ISSUE TITLE
Cannot rename notebook after create 

### ISSUE THREAD

**Issue by elwarren** [rationalmatter/Juno-Issue-Tracker#56]
**Describe the bug**
Cannot rename notebook after create 

**To Reproduce**
1. Create notebook
2. Tap on Untitled at top
3. Change name to Test
4. Error renaming file private/var/mobile/Containers/Data/Application/...

**Expected behavior**
Should rename file

**Screenshots**
If applicable, add screenshots or a screen recording to help explain your problem.

**Environment (please complete the following information):**
 - Device: iPhone xr
- iOS version: ios 12.4
- App version 1.1.0 (4127)

**Comment by elwarren** [comment]
Also happens ipad mini

**Comment by navoshta** [comment]
Thanks for reporting @elwarren — I'll fix this in the next release, meanwhile I suggest renaming via file browser (press and hold on file on iPhone, tap notebook title on iPad).

**Comment by elwarren** [comment]
Now that my other issue 55 is resolved, I can use file browser to long press and rename notebooks. Before that was resolved the long press did nothing. This is an acceptable workaround. Thanks!

**Comment by navoshta** [comment]
This should now be fixed.
