### ISSUE TITLE
Word wrap in code cells

### ISSUE THREAD

**Issue by elwarren** [rationalmatter/Juno-Issue-Tracker#57]
**Is your feature request related to a problem? Please describe.**
 When editing long lines of code the edit window must scroll right. This is difficult when working on large programs. This is especially difficult on a vertical portrait orientation iPhone. The ouput window already does wrap output. 

**Describe the solution you'd like**
Config option to enable/disable wrapping long lines in code cell text box.

**Comment by navoshta** [comment]
Thanks @elwarren, I'll see if there's a quick way to add this, otherwise it will need to wait till we introduce a few more native components to notebook editor.

**Comment by alexstaravoitau** [comment]
Closing as recent Juno releases added a word wrapping setting.
