### ISSUE TITLE
Won’t Start Notebook

### ISSUE THREAD

**Issue by DaveKT** [rationalmatter/Juno-Issue-Tracker#59]
Prior to version 1.4.0 all connections to my self hosted Juypter notebooks worked flawlessly. After updating to version 1.4.0 I can connect to the server but the notebooks won’t open. All connection settings are identical between the instances. Using python 3.6 kernel.

Steps
1. Open app
2. Connect to Jupyter notebook running on remote server
3. Attempt to open ipynp notebook. 
4. Hangs.

Jupyter version is 4.4.0 

Juno Connect Hangs
![IMG_1678](https://user-images.githubusercontent.com/16257495/66063661-b454f600-e4f8-11e9-98a1-154ea19ad9dd.png)

Same Jupyter Instance is working via the browser
![IMG_1681](https://user-images.githubusercontent.com/16257495/66063720-d2baf180-e4f8-11e9-9073-0a2a721d47c1.png)

**Comment by DaveKT** [comment]
Just a quick additional note. I decided to buy Juno (stand-alone edition) and try to connect to my notebook via FileExplorer. Works like a champ. Some paths changed but that’s easy to remedy. Also, the execution is MUCH faster when working with the notebook locally. Only downside to this approach is that I’ll have to manually maintain parity between the server files and the local ones.  Hoping connect gets sorted out soon.

**Comment by navoshta** [comment]
Hi @DaveKT — what kind of authentication are you using on this Jupyter server? Is it just plain Jupyter Notebook token/password auth, or is it perhaps a JupyterHub server with additional authentication steps/redirects?

Also, 4.4.0 sounds like a fairly old distribution (assuming it's Jupyter Notebook), would you consider upgrading it to at least Jupyter Notebook 5.x.x? (IIRC the most recent version is 6.x.x).

**Comment by DaveKT** [comment]
I'm using simple password.

So I updated to version 6.0.0 and now everything seems to be working again. Interesting.

For future reference this is a known good configuration.

Server Information:
Jupyter notebook.
The version of the notebook server is: 6.0.0
The server is running on this version of Python:
Python 3.7.3 (default, Mar 27 2019, 22:11:17) 
[GCC 7.3.0]

Thank you for your help!
