### ISSUE TITLE
Unable to delete file

### ISSUE THREAD

**Issue by avidiotic** [rationalmatter/Juno-Issue-Tracker#6]
**Describe the bug**
I opened a new Python3 notebook. After declaring a numpy array and plotting it, I was unable to delete it. I was able to replicate this with another notebook with only the numpy import code. 

**To Reproduce**
1. Create a new Python3 notebook
2. Run a cell with import numpy as np
3. Shut down the notebook 
4. Delete the notebook 

**Expected behavior**
The notebook should be deleted. 

**Screenshots**
![A0D94EF4-0BBE-4F89-AD99-112A597C3EF9](https://user-images.githubusercontent.com/9115751/57271413-f47c8d80-70ac-11e9-8bbf-3675716c806a.png)

**Environment (please complete the following information):**
 - Device: iPhone XR
 - iOS version: 12.2 (16E227)
 - App version: 1.0.0

**Comment by navoshta** [comment]
Should be fixed in Juno 1.0.2
