### ISSUE TITLE
Multiple Notebooks/Spaces

### ISSUE THREAD

**Issue by banesullivan** [rationalmatter/Juno-Issue-Tracker#61]
**Is your feature request related to a problem? Please describe.**

It would be awesome if there was a way to open multiple notebooks at once and be able to leverage iPadOS 13’s new multiple spaces feature - is there a status on this feature?

**Describe the solution you'd like**

A way to open more that one notebook at a time within a single instance of the app and then it would also be cool to have a way to have multiple instances of the Juno app using iPadOS 13’s new multitasking features.

**Comment by nipunbatra** [comment]
Look forward to the multi-window support. Many thanks for the awesome work :)

**Comment by nipunbatra** [comment]
Look forward to the multi-window support. Many thanks for the awesome work 🥇

**Comment by alexstaravoitau** [comment]
Apologies it took a while, but multiple windows support is now available in Juno beta on TestFlight — please reach out to beta@juno.sh if you would like to help test it. 🙃

**Comment by alexstaravoitau** [comment]
Juno 1.4.2 with multi-window support is now live on the App Store 🚀
