### ISSUE TITLE
Can’t highlight on iPad

### ISSUE THREAD

**Issue by abdu1993** [rationalmatter/Juno-Issue-Tracker#64]
**Describe the bug**
Used to be able to drag the highlight with touch by finger on the iPad. Now the only way to drag a highlight is to use the left and right arrows, the two dots that appear at the beginning and end of a highlighted string are not there anymore in the latest update to jupyter connect. 

**To Reproduce**
1. Tap on text to highlight
2. Once the text is highlighted, the 2 dots that used to appear to extend the highlight, do not appear. 

**Expected behavior**
Want to have the ability to drag the highlight to expand the selected text.

**Screenshots**
If applicable, add screenshots or a screen recording to help explain your problem.

**Environment (please complete the following information):**
 - Device: [iPad Pro 12.9”]
 - iOS version: [iOS 13.2]
 - App version [1.4
![23036146-3DAA-4E7F-98F3-DC9CD2CD54C0](https://user-images.githubusercontent.com/45926965/66616017-b5d78b80-eb94-11e9-9778-622f0fa8be7f.png)
![0DC80CE5-8927-4D46-8005-683596372C0D](https://user-images.githubusercontent.com/45926965/66616018-b5d78b80-eb94-11e9-97f4-9777f4e43808.png)

]

**Comment by navoshta** [comment]
Thanks for reporting @abdu1993. I think this is related to WebKit handling selection differently in iOS 13; it's likely related to #49, too. I will look into this.

**Comment by Sakelariev** [comment]
I confirm this bug for both apps - Juno and Juno Connect and it started after I updated to Ipad OS (iOS 13). Before that highlighting worked like in any other iOS app. My device is iPad 6.

**Comment by mauceri** [comment]
This renders the application unusable....

**Comment by navoshta** [comment]
This should now be fixed for both apps in Juno 1.1.1 and Juno Connect 1.4.1.
