### ISSUE TITLE
Add LXML 

### ISSUE THREAD

**Issue by sleemCode** [rationalmatter/Juno-Issue-Tracker#66]
Could Not find a supported distribution for LXML.

**Comment by navoshta** [comment]
Yes, unfortunately LXML has compiled C code, which can't be installed externally due to platform restrictions. I'll look into re-compiling it for iOS and embedding in Juno.

**Comment by sleemCode** [comment]
That would be awesome, thank you.

**Comment by JacobShin0601** [comment]
is this issue resolved?

**Comment by navoshta** [comment]
@JacobShin0601 No, it's still open. There are a couple of other libraries we would like to add to Juno before starting on LXML, but it's certainly high on the list of priorities.

**Comment by simondamkjaer** [comment]
+1

**Comment by navoshta** [comment]
LXML is now available in a TestFlight build for Juno 1.3.0 — if anyone would like to help test it, please reach out to beta@juno.sh, and I'll add you to our beta list. 😉

Thanks everyone for your patience!

**Comment by navoshta** [comment]
Juno 1.3 with LXML is now live on App Store 🚀
