### ISSUE TITLE
Can’t open any notebook

### ISSUE THREAD

**Issue by gsalesga** [rationalmatter/Juno-Issue-Tracker#69]
**Describe the bug**
I can’t select any notebook in any drive. Device rebooted many times. Juno reinstalled. Files app reinstalled.

**To Reproduce**
1. Open the app. It’s not possible to select any notebook.

**Expected behavior**
Select a file and open it.

**Screenshots**
![IMG_7046](https://user-images.githubusercontent.com/24577355/67437010-1bddfd00-f5f0-11e9-85e1-203c4a528ded.jpeg)

**Environment (please complete the following information):**
 - Device: iPad Air 2
 - iOS version: 13.1
 - App version 1.1.1

**Comment by NarciH** [comment]
Hi, I have the same problem.

**Comment by navoshta** [comment]
@gsalesga, @NarciH: please take a look at #55 — perhaps you have another app installed, which is abusing iOS file association mechanisms? A likely candidate is [Notebook Master](https://apps.apple.com/app/id1326802832).

**Comment by gsalesga** [comment]
Resolved! Thank you!
