### ISSUE TITLE
Cannot delete notebook

### ISSUE THREAD

**Issue by sausheong** [rationalmatter/Juno-Issue-Tracker#7]
**Describe the bug**
Cannot delete notebooks after they have been created.

**To Reproduce**
Select notebook, click on delete icon and then ok.

**Expected behavior**
Notebook deleted

**Screenshots**
![IMG_0088](https://user-images.githubusercontent.com/5962/57272596-e89dc500-70c6-11e9-9da1-48c4de62b7eb.png)

**Environment (please complete the following information):**
 - Device: iPad Pro 11"
 - iOS version:  iOS 12.2
 - App version: 1.0.0

**Comment by navoshta** [comment]
Should be fixed in Juno 1.0.2
