### ISSUE TITLE
AWS EC2 connection error

### ISSUE THREAD

**Issue by phidodido** [rationalmatter/Juno-Issue-Tracker#70]
I have Jupyter running on an AWS EC2 instance. I have created and installed the SSL certificate on my iPad with this guide [Accessing Jupyter on iOS over HTTPS](https://juno.sh/ssl-self-signed-cert/).

When I try to connect with Juno, the app gives this error:
`The network connection was lost.`

On the server side I get this error: 
`SSL Error on 10 ('127.0.0.1', 49150): [SSL: HTTP_REQUEST] http request (_ssl.c:852)`

Connecting to Jupyter works fine with the browser on my Macbook.

**Comment by navoshta** [comment]
Hi @phidodido, are you sure HTTPS is enabled for your server configuration? What does the resulting URL look like in server configuration screen, and what does connection checker say? (it's at the bottom of all editable settings).

**Comment by phidodido** [comment]
@navoshta 
> are you sure HTTPS is enabled for your server configuration? 
```
[I 01:47:37.140 LabApp] The Jupyter Notebook is running at:
[I 01:47:37.140 LabApp] https://ip-xxx-xxx-xx-xxx:8888/
```

> What does the resulting URL look like in server configuration screen,
```
SSH user@11.222.33.444:8888
```

> what does connection checker say? (it's at the bottom of all editable settings).
```
Clear Session
Disconnect SSH Tunnel
Delete Server
```

**Comment by navoshta** [comment]
Hi @phidodido 

Are you sure HTTPS is enabled for your server configuration _in Juno Connect_? As in: is Juno Connect trying to reach your server via HTTP or HTTPS? If you have configured your Jupyter instance to serve over HTTPS with an SSL certificate, HTTPS switch should be enabled in server configuration screen:

![IMG_86D690CBA30B-1](https://user-images.githubusercontent.com/1111935/67681535-6f03d700-f985-11e9-9616-943b0d38fd52.jpeg)

Connection checker is this small section at the bottom of the screenshot, which displays the resulting URL Juno Connect will be connecting to. It also checks if provided URL is reachable (the test URL in the screenshot isn't, obviously — yours should say "Reachable" in green). Verify that this URL starts with "https://" for your server configuration.

**Comment by phidodido** [comment]
@navoshta With AWS EC2 I need to use “Local port forwarding” as the connection type. There is no HTTPS switch when selecting local port forwarding.

**Comment by navoshta** [comment]
@phidodido Ah OK, in that case you don't need to follow [Accessing Jupyter on iOS over HTTPS](https://juno.sh/ssl-self-signed-cert/), instead refer to [Connect to Jupyter server using SSH port forwarding](https://juno.sh/ssh-tunnel-to-jupyter-server/) tutorial. Of course nothing is stopping you from using both port forwarding _and_ SSL, but usually it's OK to connect to your Jupyter server over HTTP (i.e. without SSL) in that case, as your connection is secured with SSH anyway.

If you still would like to simultaneously use both SSH tunnelling _and_ SSL, Juno Connect will not support this up until 1.5.0 is released (as port forwarding connections are forced to use HTTP currently) — you need to use either one or the other. 

Alternatively, you can either disable SSL in Jupyter (i.e. don't provide certificates when you launch Jupyter on your server), or connect to your server over HTTPS directly (you will likely need to configure your EC2 to accept incoming connections). The latter is less secure, and I recommend sticking with port forwarding.

**Comment by phidodido** [comment]
@navoshta Thanks it works now! It makes sense to use HTTP with SSH.

Now I just have to wait for the text file editing feature before I can move my workflow to Juno :)

**Comment by navoshta** [comment]
Great! Yes, text files editing is on the roadmap (although can't tell when it will be available unfortunately).
