### ISSUE TITLE
File disappeared from app and was replaced with another untitled file

### ISSUE THREAD

**Issue by ProfCelia** [rationalmatter/Juno-Issue-Tracker#76]
Description
I had been working for the last two days on an notebook on the Logistic equation and so entitled, it used NumPy, matplotlib, and SymPy.
I also had an untitled notebook that I used for trying out various ideas for the main note book. I had been switching apps to refer to use other apps. This has not caused problems in the past. But the last time I used it the the contents of my Logistic equation notebook were replaced with the content of the untitled notebook. I can’t seem to find a way to recover.

**To Reproduce**
This has only happened once, so I don’t know how to reproduce the behavior

**Expected behavior**
I expect the content of files not to be replaced.

**Screenshots**
If applicable, add screenshots or a screen recording to help explain your problem.

**Environment (please complete the following information):**
 - Device: [e.g. iPad Pro 11"]
 - iOS version: [e.g. iOS 13.2]
 - App version [1.1.1]

**Comment by navoshta** [comment]
Hi @celiarees, was this notebook stored in "Introductory Notebooks" directory by any chance? This directory is re-created with each app update (in case there are changes in intro notebooks for new library versions, for instance), so I wouldn't recommend storing anything there that's meant to last. 

The app has been recently updated to version 1.1.1, so I'm guessing your iPad auto-updated Juno, and contents of your "Introductory Notebooks" directory got overwritten. My apologies if that's indeed what happened, I'll see how I can make the non-persistent nature of this folder more apparent to the user.
