### ISSUE TITLE
App restarting each time I come back to it in iPadOS

### ISSUE THREAD

**Issue by jmbenedetto** [rationalmatter/Juno-Issue-Tracker#79]
**Describe the bug**
Each time I change apps in IPadOS, when I come back to Juno, after a couple of minutes it restarts. I then have to reopen the file I was working on.

**To Reproduce**
1. Open Juno app
2. Press home button
3. Wait 30 seconds
4. Come back to Juno

**Expected behavior**
I expect Juno to stay open when I change apps.

**Screenshots**

**Environment (please complete the following information):**
 - Device: [e.g. iPad Pro 9.4 2016"]
 - iOS version: [e.g. iOS 13.1.3]
 - App version [e.g. 1.1.1]

**Comment by navoshta** [comment]
Sadly, this is how iOS treats apps while those are in background, see #48. 

I have an idea of how this could be handled a bit better on the app side by restoring state in some common cases — I'm currently working on it, so hopefully you will see some improvements in the next release!

**Comment by navoshta** [comment]
@jmbenedetto Juno 1.2 is now waiting for TestFlight review, and should be available in the next few days — please send an e-mail to beta@juno.sh if you would like to help test it! Although it will likely still get purged by the OS while in background (even if a bit less aggressively), Juno will now attempt to fully restore its context when reopened, making this process more seamless.

**Comment by navoshta** [comment]
Juno 1.2 is now live on App Store — although OS may still kill the app while in background (it's just the way iOS and iPadOS handle 3rd party apps), Juno will now re-launch faster and, more importantly, will attempt to restore its context, including open notebook, directory permissions and even interpreter session (imported modules and variables). 

I'm closing this issue for now, as there is not much I can do about the OS behaviour, but please feel free to reopen (or perhaps submit a new one), if any of our counter-measures are not working as expected.
