### ISSUE TITLE
Remap Caps Lock to Esc

### ISSUE THREAD

**Issue by baldwint** [rationalmatter/Juno-Issue-Tracker#80]
Would you please consider adding the caps lock key as an additional Esc key binding for hardware keyboards?

It is nice to have Control and Option remapped, but for muscle memory’s sake I’d like to match what I use on the Mac (where I use Control and Option for other things).

**Comment by navoshta** [comment]
@baldwint, thanks for reporting — yep, this is certainly something I want to add eventually. Unfortunately, this will likely need to wait until a notebook editor rewrite, as currently it partially relies on WebKit components for notebook editing. This makes specifically Caps Lock hard to handle — there is a number of potential workarounds, but nothing robust and future-proof as far as I know. I'll keep an eye on what iOS allows though, and if this could be added earlier.

**Comment by navoshta** [comment]
Now that iPadOS allows configuring Caps Lock as Esc on a system level, I don't think it's worth it implementing this in the app — so closing the issue. Feel free to reopen if I'm missing anything though.
