### ISSUE TITLE
Constantly crashing on iPad Pro

### ISSUE THREAD

**Issue by ApoorvDP** [rationalmatter/Juno-Issue-Tracker#81]
Juno app crashes within 5 seconds on my iPad Pro 11 (2018). Using iPadOS 13.2.2
Juno Connect is working fine.

Seems to be specific to iPadOS, since the Juno app works fine on my iPhone XS Max running iOS 13.2.2

**Comment by navoshta** [comment]
Hi @ApoorvDP, sorry to hear that, just to clarify — the app crashes while it's in foreground and loading, right? Asking as I can't reproduce this on any of my devices (and I don't see any fresh crash logs matching description unfortunately).

**Comment by ApoorvDP** [comment]
Yes, that is correct. It doesn't even get to the loading screen, just crashes instantly.
I don't think it's a RAM management issue, as someone else listed on the tracker.

I made a brief screen recording, which you can see at:
https://colostate-my.sharepoint.com/:v:/g/personal/apoorvp_colostate_edu/ESArNOAIE6RFjAe-03AbWw4BlIHMDVgz7JXkzEtIgP-XzQ?e=vP4Rve

Please let me know what other details you require.
As I mentioned previously, it's an iPad Pro 11 (2018), running iPadOS 13.2.2

**Comment by navoshta** [comment]
Thanks for the recording @ApoorvDP — that looks very odd! Could you please try deleting it and fresh-install again? Did you participate in Juno beta by any chance?

**Comment by ApoorvDP** [comment]
Damn, that was the simplest fix of all time. Can’t believe I was so dumb I didn’t try that.

Thank you for the help, and sorry for wasting your time.

Keep up the great work, we all appreciate your apps a lot!

**Comment by navoshta** [comment]
No worries, and glad you got it working! I'm still curious why it was crashing though... I'll keep an eye on similar reports.
