### ISSUE TITLE
Paste pop up menu  doesn’t show when keeping pressed the selection as other IOS

### ISSUE THREAD

**Issue by jceresearch** [rationalmatter/Juno-Issue-Tracker#82]
**Describe the bug**
I copied some text from another app in my iPhone   but when trying to paste it in a cell of a new notebook it doesn’t show the paste pop up balloon. Using the new iOS gesture of three fingers spreading did paste. 

I just now tried the same with my iPad and it worked, still a fraction slow to show up the balloon but still natural. In the iphone it just doesn’t register and I am trying all kind of variations .
I dont have any screen protector, and i was able to copy using the same pressing gesture in another app, so it is not that I dont manage to press properly to activate the behaviour.
(I appreciate that coding in an iPhone may not be the expected use case, it was just me trying to pass the time and trying an idea).

 
**To Reproduce**
Try to copy and paste some text into a brand new cell in an iphone.

**Expected behavior**
Paste balloon should appear.

**Screenshots**
If applicable, add screenshots or a screen recording to help explain your problem.

**Environment (please complete the following information):**
 - Device: [e.g. iPad Pro 11"] iPhone 11 pro max
 - iOS version: [e.g. iOS 12.2] 13.1.3
 - App version [e.g. 1.0.0] 1.1.1.

**Comment by navoshta** [comment]
@jceresearch Thanks for reporting, I'll take a look — does this happen with every notebook, or only when you create a new one?

**Comment by jceresearch** [comment]
I just tried to paste a small piece of text to a new cell of an existing notebook and I couldn’t  invoke the balloon... the cursor did gett bigger and moving  a bit to the right and back , but no balloon.

Once I add data , it eventually shows the balloon for pasting.
plus from there on it does show fine in an empty cell... still the cursor jumps around a bit

could it be that the first invocation of the “press” balloon in a notebook takes a bit more time than with other typical  iOS text composing app?

Anyway, the 3-finger spread gesture works, and the press gesture does seem to eventually work after poking the screen enough times ... so probably a non issue after all.

That said given how fiddly can be to paste stuff (position the cursor) any chance of adding those as buttons in the virtual keyboard? 

Thanks in any case for replying 
Cheers

**Comment by navoshta** [comment]
> could it be that the first invocation of the “press” balloon in a notebook takes a bit more time than with other typical  iOS text composing app?

Hmm, it's odd that this behaviour seems to only happen on empty cells — I'll see what could be breaking here. Juno partially relies on Jupyter's UI for displaying notebook editor, so there are a few places where things could go wrong (including Apple's WebKit!).

**Comment by navoshta** [comment]
@jceresearch I know this issue has been reported for Juno, but it should now be fixed in latest Juno Connect beta (1.5.1) — let me know if you would like to be added to Testflight (and send me your Apple ID to beta@juno.sh). Alternatively, I can let you know when there's a Juno beta to test.

**Comment by jceresearch** [comment]
Thanks Alex, perhaps for the Juno beta?, I am not using the Connect lately
:)
Cheers!
JC

**Comment by navoshta** [comment]
@jceresearch Sure, I'll post here when Juno beta is available.

**Comment by navoshta** [comment]
@jceresearch Juno 1.2 is now waiting for TestFlight review, and should be available in the next few days — please send an e-mail to beta@juno.sh if you would like to help test it!

**Comment by navoshta** [comment]
This should now be fixed in Juno 1.2 and Juno Connect 1.5 (live on App Store).
