### ISSUE TITLE
Unload from memory too quickly

### ISSUE THREAD

**Issue by jceresearch** [rationalmatter/Juno-Issue-Tracker#83]
**Describe the bug**
While using Juno, if I switch to another application to do something (main button back to main screen and , say google something, and back after a Minute or so) , it fully loads again, i need to go back to opening the notebook etc.
Not sure if this is a but or more of a feature request (some sort of persistence).

**To Reproduce**
Leave the application and come back after some time (one minute or so) and it would relaunch completely.

**Expected behavior**
I expect being able to switch applications to do research or doing something else and come back and continue working. 

**Screenshots**
If applicable, add screenshots or a screen recording to help explain your problem.

**Environment (please complete the following information):**
 - Device: iPad Air 3rd gen
 - iOS version: 13.1.3
 - App version 1.1.1

**Comment by navoshta** [comment]
@jceresearch Sadly, this is how iOS treats apps while those are in background, see #48.

I have an idea of how this could be handled a bit better on the app side by restoring state in some common cases — I'm currently working on it, so hopefully you will see some improvements in the next release!

**Comment by navoshta** [comment]
@jceresearch Juno 1.2 is now waiting for TestFlight review, and should be available in the next few days — please send an e-mail to beta@juno.sh if you would like to help test it! Although it will likely still get purged by the OS while in background (even if a bit less aggressively), Juno will now attempt to fully restore its context when reopened, making this process more seamless.

**Comment by navoshta** [comment]
Juno 1.2 is now live on App Store — although OS may still kill the app while in background (it's just the way iOS and iPadOS handle 3rd party apps), Juno will now re-launch faster and, more importantly, will attempt to restore its context, including open notebook, directory permissions and even interpreter session (imported modules and variables). 

I'm closing this issue for now, as there is not much I can do about the OS behaviour, but please feel free to reopen (or perhaps submit a new one), if any of our counter-measures are not working as expected.

**Comment by jceresearch** [comment]
Thanks! I ve been using the beta and indeed it recovers and the experience is much better... i could actually complete a routine.
That said it is still a noticeable limitation, i have to run again the cells.  i hope ios fixes it... i code little snippets in the ipad and i do a lot of googling to find out answers and my way around, the app gets killed a mere few seconds after leaving it. the only workaround i ve found has been using split view or floating browser. Could having some sort of embedded tab/frame with a browser (kind of what reddit does) be possible for a quick search?
In any case, thanks for working on this, and hopefully it will keep developing into a fantastic tool
cheers

**Comment by navoshta** [comment]
Thanks @jceresearch — sure, in-app browser makes sense I suppose, and I'll see how this could be added. I doubt it will be easier to use than Safari in slide-over/split-screen modes though, but it could become a configurable option, for instance.

**Comment by jceresearch** [comment]
I agree,  it would be a workaround till ios becomes a better multitasking device, for now we are stuck with those split view and floating, 
i personally find the floating windows a pain, too narrow for understanding pieces of code when word wrapped or too tiny zoom; i end up screwing the gestures all the time (invoking, swiping out, and back in), same with trying to activate and adjust the split view, also often the link goes to an app ... i actually deleted the stackoverflow app to ensure i don’t go to the app (not very good anyway).

you might want to have a look at ithoughts mindmap app.. it has a “research” feature ib the  contextual menu which prompts a barebones browser, i actually use it often to search for clip art and reinsert.. i found it pretty seamless.
When i sent some suggestions there the developer found the time to respond, maybe he will kindly give you some ideas about implementation.

In the end it is about understanding the most common use case of your userbase, i tend to use it to google around to understand how to solve a specific problem and adapt/build a small piece that works,  to then add/code it properly in my laptop. If that is the typical use, then something like an embedded search could add value. otherwise, yeah, we will survive with the floating windows :) 

thanks for coming back!
jc
