### ISSUE TITLE
Juno connect cant connect to CoCalc after update

### ISSUE THREAD

**Issue by johnmiller111980** [rationalmatter/Juno-Issue-Tracker#85]
**Describe the bug**
Cant connect tot CoCalc afer update. 
Connecting 5 4 3 2 1 and again ang again

Tested on both iphone and ipad. Las version of IOS and Juno Connect

**Comment by navoshta** [comment]
@johnmiller111980 Judging by description, your CoCalc API key got invalidated. Unfortunately, CoCalc's API doesn't provide a way to check if that is indeed the case, so all Juno can do is try using an existing key a few times, and after a number of unsuccessful attempts it will give up, invalidate the local copy of the key and display a login screen to obtain a new one.

I suggest that you log out from CoCalc and log in again — this will likely be the best way to fix this. If the issue persists, please do let me know and I will see what else could go wrong.

**Comment by johnmiller111980** [comment]
Thank you vm for help. 
All is working now!
