### ISSUE TITLE
paperspace.com notebook integration

### ISSUE THREAD

**Issue by markolonius** [rationalmatter/Juno-Issue-Tracker#86]
Feature request for integration with paperspace.com notebooks.  Now that they offer free GPU options I think it would be perfect to pair with Juno Connect.  They seem to be able to run on standard Jupyter notebooks and have a sharable link.  Any help I can provide further just point me in the direction!

**Comment by navoshta** [comment]
Thanks @markolonius, it's on the list of services to integrate with! If they indeed provide an endpoint with standard Jupyter interface, this would make the integration much easier (and therefore it will be likely to get picked up soon 🙂).

**Comment by markolonius** [comment]
I was able to get a notebook connected on paperspace gradient notebooks.  

1. Start the notebook under the paperspace gradient notebook dashboard
2. Once running, open V1 (Classic) notebook that should launch Jupiter lab
3. Copy the URL and use that for the server address when adding a server to Juno
4. Delete the port number and don't forget to enable https then the server should be reachable!
5. It will ask you to log into your paperspace account
6. Open your Jupyter notebooks

It is a bit cumbersome because the URL changes every time you start the paperspace gradient notebook server.  Would be nice to see some better integration like the Azure notebooks and cocalc, but not sure how possible that is.  Now knowing there is a easily identifiable Jupyter endpoint hopefully may help?

**Comment by navoshta** [comment]
Thanks for sharing @markolonius! Sounds like it should be _relatively_ easy to integrate with it, even better if they have some sort of API to get this endpoint URL. We're a bit busy with Juno at the moment, but Paperspace sounds like the best candidate for the next Juno Connect backed integration.

**Comment by jayweiler** [comment]
Just curious if this integration is still on the roadmap? Thanks!

**Comment by navoshta** [comment]
@jayweiler Yep, certainly — although I still don't have ETA I'm afraid. There are a number of other features we planned for Juno Connect first, but when we get to adding new integrations, Paperspace will likely be the first one we will look into.

**Comment by navoshta** [comment]
Juno Connect 1.6.3 adds experimental Paperspace Gradient support — it's currently in beta, but if you would like to help test it, please send an email to beta@juno.sh and I will add you to our TestFlight! 😉

**Comment by navoshta** [comment]
Experimental Paperspace Gradient support has been released to App Store, so I'm closing this ticket for now — feel free to reopen or submit a new one if you spot any issues with it.
