### ISSUE TITLE
Notebook restarts after sleep (or app switch)

### ISSUE THREAD

**Issue by gsportelli** [rationalmatter/Juno-Issue-Tracker#88]
**Describe the bug**
I was working with Juno on a notebook in split view with another app, then I left the iPad and came back after it went in sleep mode. When I unlocked the iPad and went back to the split screen, Juno restarted and the notebook was lost.

**To Reproduce**
1. Open Juno in split mode with, e.g., the iOS Notes app. 
2. Create a new notebook and insert and run some cells
3. Leave the iPad until it goes to sleep mode
4. Go back to the Notes app or to the Juno app clicking on the app bar

**Expected behavior**
I would expect both the Notes app and the Juno app to show the last app status with the unchanged documents. I see instead the Notes app with the working document (as expected) but Junos restarts without saving a working copy of the notebook. Note that I’ve observed the same behaviour when switching apps, Juno restarts most of the times I leave the window.

**Environment (please complete the following information):**
 - Device: iPad Pro 12.9 latest version as of 11/2019
 - iOS version: 13.2.2
 - App version 1.1.1 (4128)

**Comment by gsportelli** [comment]
Curiously, the notebook I had lost reappeared in the recent notebooks a couple of hours later.

**Comment by navoshta** [comment]
@gsportelli Sorry you are seeing this! Yes the notebook itself shouldn't have been deleted — even if it was opened in place, the changes are always saved before the app goes to background. Where was it located when you opened it? Did the file have the last changes saved when you recovered it afterwards? Was it in the same location?

As per Juno restarting: sadly, this is how iOS treats apps while those are in background, see #48 — and Juno in particular has a significant resources footprint, so it's usually the first candidate to get purged by the OS. However, I'm currently making sure Juno keeps running for as long as possible without restarting, and even when it does get restarted it restores its context (may be a bit tricky with current variables though). Either way, hopefully you'll see some improvements in that area with Juno's next update. 😉

**Comment by gsportelli** [comment]
I opened it as a new notebook without selecting any location (I think I didn't follow the suggestion to unlock the folder).
It has something saved, can't say for sure how much did I lost (as it was my first use, I was just experimenting).
Anyway, the app looks very good, thanks for your work!

**Comment by navoshta** [comment]
@gsportelli Juno 1.2 is now waiting for TestFlight review, and should be available in the next few days — please send an e-mail to beta@juno.sh if you would like to help test it! Although it will likely still get purged by the OS while in background (even if a bit less aggressively), Juno will now attempt to fully restore its context when reopened, making this process more seamless.

**Comment by navoshta** [comment]
Juno 1.2 is now live on App Store — although OS may still kill the app while in background (it's just the way iOS and iPadOS handle 3rd party apps), Juno will now re-launch faster and, more importantly, will attempt to restore its context, including open notebook, directory permissions and even interpreter session (imported modules and variables). 

I'm closing this issue for now, as there is not much I can do about the OS behaviour, but please feel free to reopen (or perhaps submit a new one), if any of our counter-measures are not working as expected.
