### ISSUE TITLE
Problem renaming notebook

### ISSUE THREAD

**Issue by Arjitc12** [rationalmatter/Juno-Issue-Tracker#9]
**Describe the bug**
After renaming the notebook I can only see my notebook renamed after I relaunch my jupyter notebook.

**To Reproduce**
1. Rename Notebook 
2. And then save
3. You could still see the previous name until you relaunch App

Environment (please complete the following information):
 - Device: iPhone 7
 - iOS version:  iOS 12.2
 - App version  1.0.0

**Comment by navoshta** [comment]
Should be fixed in Juno 1.0.2
