### ISSUE TITLE
Ipywidgets support for Juno

### ISSUE THREAD

**Issue by ekul00** [rationalmatter/Juno-Issue-Tracker#92]
ipywidgets currently installs without error but the widgets fail to render when run. 

The feature request is to get ipywidgets to operate correctly in the notebook editor :)

**Comment by navoshta** [comment]
Thanks @ekul00 — I will look into this (it will likely apply to both Juno and Juno Connect).

**Comment by reichardtj** [comment]
Same here, iypidgets installs but does not render. Getting the widgets to work would be great!

**Comment by mppowell** [comment]
Adding another +1 to this. I would love to be able to use widgets in the Juno ecosystem!

**Comment by metabacchi** [comment]
Some widgets seem to work in Juno Connect (int_slider), albeit with refresh problems. The exact same notebook does not display the slider in Juno.

**Comment by LukaPitamic** [comment]
yes!!!! 
Juno's value increases 100x if `ipywidgets` are implemented. Speed and efficiency of data analysis is capped without customisable UI which `ipywidgets` so elegantly solve.

**Comment by navoshta** [comment]
Thanks @metabacchi, @LukaPitamic — worry not, ipywidgets are certainly on the TODO list! 😉 

Meanwhile, perhaps you could provide code examples of where ipywidgets currently fail (and how they are expected to behave)? This would help with development/testing a bit, but either way ipywidgets are on the roadmap, and I'm planning to start looking into them shortly.

**Comment by LukaPitamic** [comment]
@navoshta great, you don't know how so may of us are looking forward to this.
How are they expected to behave:

1. the **ipywidgets** imports without errors by enterpreting the code
`import ipywidgets as widgets`
2. however in Jupyter Notebook or Jupyter Lab additional extension is loaded:
Notebook: `jupyter nbextension enable --py widgetsnbextension`
JupyterLab: `jupyter labextension install @jupyter-widgets/jupyterlab-manager`
...to render widgets properly.

IMHO what is needed is a Juno specific "plugin" to do the same job.

For example the following code produces "widget" - horizontal interactive slider as cell notebook output which communicates with a kernel.
![image](https://user-images.githubusercontent.com/34914144/76587896-65ea5100-64b3-11ea-8e69-c4d3dc018ca7.png)

**Comment by metabacchi** [comment]
Juno Connect:
(the slider is there, with limited functionalities: no label in dark more, no sliding - you can only click on the slider to move the cursor there)
<img width="810" alt="Screenshot 2020-03-13 at 18 53 18" src="https://user-images.githubusercontent.com/57687483/76647206-9f2acb80-655c-11ea-8329-b19b7cd093ba.png">

Juno:
(no slider at al)
<img width="810" alt="Screenshot 2020-03-13 at 18 54 26" src="https://user-images.githubusercontent.com/57687483/76647259-ba95d680-655c-11ea-9943-45a57f44cd13.png">

**Comment by LukaPitamic** [comment]
@metabacchi WTG! I wasn't aware slider is actually rendered if Juno is connected to outside Jupyter server. We're not that far from we want to be, huh? Thumbs up @navoshta

**Comment by navoshta** [comment]
Thanks @LukaPitamic, @metabacchi — this helps a lot!

**Comment by navoshta** [comment]
@ekul00 @reichardtj @LukaPitamic @metabacchi @mppowell `ipywidgets` are now available in Juno 1.2.6, which is out on TestFlight — please ping me on beta@juno.sh if you would like to help test it! 🙃

**Comment by ekul00** [comment]
Brilliant thanks @navoshta that’s great news. I’d like to have a poke around with that in the next week or so. I’ll email you :)

**Comment by navoshta** [comment]
Ipywdigets are now available in Juno 1.2.6, which is out on App Store! 🎉 

If something is not working as expected, please open a new issue or ping me on feedback@juno.sh. 🙃
