### ISSUE TITLE
Can't paste into cells

### ISSUE THREAD

**Issue by dbrehmer** [rationalmatter/Juno-Issue-Tracker#93]
**Describe the bug**
Maybe this would be considered a feature request, but it is so essential that I consider it a bug: It does not seem to be possible to paste into a cell from the clipboard. Is it possible that I just didn't figure out how to do it? It would also be a bug if it is so difficult to figure it out :)

**To Reproduce**
1. Copy some code from a website that you would like to add to your notebook cell.
2. Go to your notebook in Juno, if it is still running and iOS has not killed it.
3. Try to paste the copied code from the clipboard into the cell.
4. Nothing happens.

**Expected behavior**
I expected to be able to paste code from the clipboard into cells of the Jupyter notebook.

**Environment (please complete the following information):**
Device: iPhone 11 Pro Max

**Comment by navoshta** [comment]
Thanks for reporting @dbrehmer — that's certainly a bug! Does the "Paste" bubble show up at all? Or it simply doesn't do anything when you tap it?

**Comment by dbrehmer** [comment]
Nothing comes up when I tap. When I keep trying and do a long tap it
selects the empty contents of the cell, but still no bubble.

I just tried again, and I found a way to get it to come up - if I enter
some text and select it then the bubble sometimes comes up. I still have to
tap a few times. I have never gotten it to come up for an empty cell though.

The behavior for selecting text is also a little strange. I don't seem to
be able to double tap then drag to make a selection. Only tap and hold
somewhere not close to the cursor allows me to select a word, then I can
drag the ends to cover a wider selection. I am not sure about the Apple
guidelines for how this is supposed to work, but I know that is written up
somewhere and probably something you should check against.

Thanks for a very useful product though. I am really happy to have found it
and appreciate the amount of work that goes into developing a product like
this!

Thanks,

-Dan

**Comment by navoshta** [comment]
Thanks for clarification — I have a feeling this is something specific to iOS 13, actually.

**Comment by simardcasanova** [comment]
I have the exact same bug. It currently makes Juno Connect unusable. Any news on a fix?

**Comment by simardcasanova** [comment]
Also, in a text cell the cursor kept going at the beginning when I’m attempting to erase everything by typing repeatedly on delete. I don’t know if it’s related though.

**Comment by navoshta** [comment]
@simardcasanova No workaround for now I'm afraid, as I'm still yet to look into this. Meanwhile, if behaviour improved in recent iOS releases please let me know. This might be one of those issues which are largely out of my control (I will still try to find a workaround regardless though).

As per the cursor jumping to the beginning — probably not related, but if you could make a quick screen recording that would help.

**Comment by simardcasanova** [comment]
@navoshta Just retried to paste, still broken. Once again, without pasting, Juno Connect is unusable.

The cursor jumping seems fixed though.

**Comment by navoshta** [comment]
@simardcasanova @dbrehmer I know this issue has been reported for Juno, but it should now be fixed in latest Juno Connect beta (1.5.1) — let me know if you folks would like to be added to Testflight (and send me your Apple IDs to beta@juno.sh). Alternatively, I can let you know when there's a Juno beta to test.

**Comment by navoshta** [comment]
@simardcasanova @dbrehmer Juno 1.2 is now waiting for TestFlight review, and should be available in the next few days — please send an e-mail to beta@juno.sh if you would like to help test it, and if you haven't joined the Juno Connect beta already. Juno 1.2 will have the same behaviour around edit menu as Juno Connect 1.5.

**Comment by navoshta** [comment]
This should now be fixed in Juno 1.2 and Juno Connect 1.5 (live on App Store).
