### ISSUE TITLE
Suggestions blocks cursor up and down moving.

### ISSUE THREAD

**Issue by yaroslavyaroslav** [rationalmatter/Juno-Issue-Tracker#94]
**Describe the bug**
When i move in code with the external keyboard on every arrow hit juno shows completion suggestion which takes out control and makes unable to move upward neither downwards.

**To Reproduce**
1. Go to multiline code cell in edit mode
2. Move in the middle of the word 
3. Meet the complete suggestion of the word that is already suggested
4. Fail to move up and down within the cell since the up and down arrows are locked by completion result popup

**Expected behavior**
To not provide suggestions if not letter button were tapped.

**Screenshots**
![E66ACDD4-B5B1-454A-A456-ABD058AF9B57](https://user-images.githubusercontent.com/16612247/69611376-b346cd80-103e-11ea-8ce1-26a2f9576bf9.jpeg)

**Environment (please complete the following information):**
 - Device: iPad Air (3)
 - iOS version: iOS 13.2.3
 - App version 1.4.1

**Comment by navoshta** [comment]
Thanks for reporting @yaroslavyaroslav — yep, sounds like a bug. This will be fixed in the next release.

**Comment by navoshta** [comment]
@yaroslavyaroslav Juno Connect 1.5 is now in beta with keyboard navigation fixed — if you would like to help test it, please send the e-mail address you use with your Apple ID to beta@juno.sh 😉

**Comment by yaroslavyaroslav** [comment]
I dunno where should i send bug reports for the beta, so i’m sending it to that mail yet. 



With beat regards,
Yaroslav

**Comment by navoshta** [comment]
@yaroslavyaroslav Thanks! Yep, email will do.

**Comment by navoshta** [comment]
The fix should now be available on App Store, too.
