### ISSUE TITLE
Autocomplete rarely duplicates letter

### ISSUE THREAD

**Issue by yaroslavyaroslav** [rationalmatter/Juno-Issue-Tracker#95]
**Describe the bug**
Sometimes (quite rarely) combination of typed word and tab key on the external keyboard hit leads to this: `printr` which result of `pr` + `Tab` key hit.

**To Reproduce**
I can’t figure out the exact steps which guarantee leads to that issue neither have a screenshot yet, but i suppose this is the bug that should be reported at least in that kind of lack of information. Maybe, some folks that met it too will provide some additional info.

**Environment (please complete the following information):**
 - Device: iPad Air (3) + external apple keyboard
 - iOS version: 13.2.3
 - App version 1.4.1

**Comment by navoshta** [comment]
Hmm, I'll need to look into that one. Possibly a silly question, but the suggestion you see in the autocompleter says "print" in that case (without trailing "r") , right?

**Comment by yaroslavyaroslav** [comment]
Yep, suggestion shows usual `print` and the execution fails with undefined var with `printr`.
