### ISSUE TITLE
Can’t open notebooks

### ISSUE THREAD

**Issue by tkvad** [rationalmatter/Juno-Issue-Tracker#97]
I have a fresh install of Juno on a brand new iPad Pro generation 3 running IOS 13.2.3 which can’t open any notebooks other than new notebooks created in Juno is greyed our(as https://github.com/rationalmatter/Juno-Issue-Tracker/issues/55 https://GitHub.com/rationalmatter/Juno-Issue-Tracker/issues/63 https://github.com/rationalmatter/Juno-Issue-Tracker/issues/69)
All notebooks are greyed out see attached screenshot
The difference here is I don’t have Notebook Master for Jupyeter (or anything else programming, python or Jupyeter) installed. Installed apps also in a screenshot
<img width="1024" alt="Screenshot 2019-12-01 at 11 49 09" src="https://user-images.githubusercontent.com/6440028/69913525-b3750d80-1430-11ea-811e-ebda072b9df2.png">

<img width="1024" alt="Junoscreenshot" src="https://user-images.githubusercontent.com/6440028/69913484-537e6700-1430-11ea-8802-e797c130bc95.png">

**Comment by navoshta** [comment]
Hmm that looks very odd @tkvad — judging by the screenshot, the behaviour is the same, as in: Juno failed to register as a handler for notebooks with the system; it doesn't even pick up the document icon Juno provides for Jupyter notebooks. Could you please try restarting the device, and fresh-installing Juno (i.e. delete and install from scratch)?

**Comment by tkvad** [comment]
Tried both same result, though stranger and stranger, Juno can see all its own sample files but anything I have created or sourced from elsewhere.

**Comment by navoshta** [comment]
@tkvad When Juno sees its sample files, do they have a Jupyter icon, or just a text preview instead (as in your second screenshot)? What happens if you try to open a notebook in place from another app, for example choose "Open in Juno" in Files app?

**Comment by tkvad** [comment]
Ok very odd. Its own notebooks have the Jupyter icon and from file manager can be opened in Juno, files from anywhere else are txt preview and don’t show opening in Juno as an option. Looks like this might be IOS doing something odd with the .ipynb extension.

**Comment by navoshta** [comment]
OK I'm honestly at a loss here @tkvad, I have a crazy suggestion though: you did mention that you don't have Notebook Master installed (it's the app that usually causes this behaviour, as it has .ipynb file association misconfigured). Could you _try installing it_, and see if that makes any difference? No way iOS will get any more confused than it already is. 🙂

Also, it would make sense to try installing Notebook Master and Juno in various order, as it seems that when iOS has contradicting information about file association, it tends to let the first app installed handle it.

**Comment by tkvad** [comment]
Stranger still, Notebook Master can see and open Juno sample files and files created in Juno but not ones from anywhere else but as expected with it installed Juno can't open anything

**Comment by navoshta** [comment]
@tkvad Perhaps try removing both, updating to iOS 13.3 and re-installing Juno? Frankly, I'm not sure what to suggest further: file association is handled by the OS, and there isn't much I can do at this point. 😔

**Comment by roloow** [comment]
I'm having the same problem, I had installed Notebook Master, then I uninstall it and bought Juno, now I can only open Jupyter Files created from Juno or open them in Juno from the file explorer but inside Juno app they are not selecteable.

**Comment by navoshta** [comment]
@roloow sorry to hear that: it does seem like iOS erroneously "cached" app association it had with Jupyter notebooks. As I mentioned in other tickets, Notebook Master abuses this association by claiming .ipynb as their own proprietary file format, therefore iOS won't let any other app handle it. 

Which iOS are you running? Could you please try rebooting the device and re-installing Juno from scratch (i.e. deleting and installing again)?

**Comment by tkvad** [comment]
Ipad updated, Juno deleted, re-downloaded and re-installed still the same, looks like Juno is a total waste of money. As I said this was a brand new ipad and other than routine stuff like office and email apps Juno was the first thing I installed.

**Comment by alexstaravoitau** [comment]
@tkvad Sorry about that — I suggest that you contact App Store support to get a refund. Something is clearly broken with file association on your device, and I can only assume it's an iOS issue that may get fixed in future betas/releases.

**Comment by tkvad** [comment]
Ahh well, Apple refusing to process a refund for reasons they won't explain, nevermind hopefully the next version will work!

**Comment by navoshta** [comment]
@tkvad I'll make sure to include you in Juno betas (when testing begins) so that you could try it early, too.

**Comment by tkvad** [comment]
Oh and just to add to this I just downloaded Juno to my iphone running IOS 13.3 and have exactly the same problem Juno can open the files that came with it but not ones sourced from elsewhere

**Comment by navoshta** [comment]
@tkvad Very odd! I'll post if I have any ideas of what could be wrong. What about other apps by the way, do they work fine on your devices? More specifically those that use their own file formats — so not PDFs or text files, but rather something like .ipynb.

**Comment by tkvad** [comment]
Hi,Yes most strange, can't say I've encountered problems with any other apps but will have a play over the weekend as I have a few on there that use their own rare file types.David

    On Friday, 17 January 2020, 10:42:27 GMT, Alex Staravoitau <notifications@github.com> wrote:  
 
 
@tkvad Very odd! I'll post if I have any ideas of what could be wrong. What about other apps by the way, do they work fine on your devices? More specifically those that use their own file formats — so not PDFs or text files, but rather something like .ipynb.

**Comment by chadwick-hui** [comment]
Hi, 

I had similar problem as you do, only difference is that the file shown was in a different way:
![69A4B79A-6EF0-4212-956F-A27D99E26E45](https://user-images.githubusercontent.com/38255626/73329098-64bce600-42b0-11ea-8c5e-939c9aaf0de7.jpeg)

maybe you could try this:
1. Open ‘Files’
2. Go to the Folder contains the file you want to open it
3. Long Press the file you want to open
4. Press ‘Share’
5. Scroll the app icons to the right most
6. Press ‘More’
7. Press view in Juno

That worked for me though, not sure whether it works all the same :P
Hope it might help

**Comment by navoshta** [comment]
@chadwick-hui Your issue looks more like #55, could you please take a look and check if you have any conflicting apps? This didn't help @tkvad here (hence it's a separate ticket), but perhaps in your case it will.

**Comment by chadwick-hui** [comment]
@navoshta thanks for the redirection. I actually got the problem solved, just trying to help @tkvad out. As this way seemed working for me :)

**Comment by tkvad** [comment]
> @navoshta thanks for the redirection. I actually got the problem solved, just trying to help @tkvad out. As this way seemed working for me :)

Thanks, doesn't work for me as Juno doesn't appear in the list of apps I can share it to. Looks like Apple have properly borked this!

**Comment by alexstaravoitau** [comment]
Closing the issue, as recent iOS releases seem to have addressed this.
