### ISSUE TITLE
Add CVXOPT

### ISSUE THREAD

**Issue by chr1stopher** [rationalmatter/Juno-Issue-Tracker#99]
Hello,
It would be wonderful if you could consider adding the possibility of porting CVXOPT and to embed it into Juno! 
Thanks in advance 
Christopher

**Comment by navoshta** [comment]
Cvxopt will be available (alongside statsmodels) in the next TestFlight build for Juno 1.3.3 (currently in review) — if anyone would like to help test it, please reach out to beta@juno.sh, and I'll add you to our beta list. 😉

**Comment by navoshta** [comment]
Juno 1.3 with Cvxopt is now live on App Store 🚀
